### Explore A Jain's IEI pipeline
### Julian Moran
### 2026-02-09

In [2]:
import os

from dotenv import load_dotenv

import polars as pl
import numpy as np

# Env
load_dotenv("../.env")
INSTALL_PATH = os.environ["INSTALL_PATH"]

# Missing read permissions

1. `00_run_pipeline.sh`
2. `scripts/05_generate_slurm_file.py`
3. `scripts/06_find_human_foldseek_matches.py`
4. `scripts/07_run_foldseek.py`
5. `scripts/07_submit_run_foldseek.sh`
6. `scripts/08_add_annotations-optimized-new_metrics.py`

In [4]:
# ============================================================
#                             Args
# ============================================================

args = {
    "data_file_foldseek_uniprot": f"{INSTALL_PATH}/data_local/02_FoldSeek_Results_w_Uniprot_matches/2025-07-26_batch_0_annotated.tsv",
    "data_file_GRIID": f"{INSTALL_PATH}/data_local/griid_gene_list/2025-07-30_data_filtered_for_griid_genes.tsv",
    "data_file_gasdermin": f"{INSTALL_PATH}/data_sync/gasdermin/2025-07-26_gasdermin_annotated.tsv",
    "data_file_vipirin": f"{INSTALL_PATH}/data_sync/viperin/2025-07-26_viperin_annotated.tsv",
    "data_file_zorya": f"{INSTALL_PATH}/data_local/zorya/2025-07-27_zorya_annotated.tsv"
}

In [16]:
# ============================================================
#                             In
# ============================================================

data_ann = {}
for key, path in args.items():
    if "data_file_" in key and not "foldseek" in key:
        data_key = key.replace("file_", "")
        data_ann[data_key] = pl.read_csv(
            args[key],
            has_header=True,
            separator="\t",
            schema_overrides={
                "duplicate_count": pl.Int64,
                "rank": pl.Int64,
                "evalue": pl.Float64,
                "cluFlag": pl.Int64,
                "fident": pl.Float64,
                "alnlen": pl.Int64,
                "mismatch": pl.Int64,
                "gapopen": pl.Float64,
                "qstart": pl.Int64,
                "qend": pl.Int64,
                "tstart": pl.Int64,
                "tend": pl.Int64,
                "evalue_foldseek": pl.Float64,
                "bits": pl.Int64,
                "Query_length": pl.Int64,
                "Human_prot_total_length": pl.Int64,
                "Human_domain_percentage": pl.Float64,
                "Query_percentage": pl.Float64,
                "Query_overlap_w_Human_protein": pl.Float64,
                "Target_length": pl.Int64,
                "Bacterial_prot_total_length": pl.Int64,
                "Bacterial_domain_percentage": pl.Float64,
                "Target_percentage": pl.Float64,
                "Target_overlap_w_Bacterial_protein": pl.Float64,
                "Bacterial_Human_Len_Ratio": pl.Float64,
                "Query_Target_Overlap_Length": pl.Float64,
                "Overlap_ratio": pl.Float64,
            },
            infer_schema_length=10000
        )

df_foldseek_uniprot = pl.read_csv(
    args["data_file_foldseek_uniprot"],
    separator="\t",
    has_header=True
)

df_foldseek_uniprot

shape: (6_097, 70)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ accession_ ┆ type  ┆ subtype    ┆ species    ┆ … ┆ Bacterial ┆ Bacterial ┆ Query_Tar ┆ Overlap_r │
│ in_sys     ┆ ---   ┆ ---        ┆ ---        ┆   ┆ _domain_e ┆ _Human_Le ┆ get_Overl ┆ atio      │
│ ---        ┆ str   ┆ str        ┆ str        ┆   ┆ vidence   ┆ n_Ratio   ┆ ap_Length ┆ ---       │
│ str        ┆       ┆            ┆            ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64       │
│            ┆       ┆            ┆            ┆   ┆ str       ┆ f64       ┆ i64       ┆           │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ WP_0012232 ┆ MazEF ┆ MazEF      ┆ Shigella   ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 08.1       ┆       ┆            ┆ dysenteria ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ e,Escheric ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ h…         ┆   ┆           ┆           ┆           ┆           │
│ WP_0034142 ┆ Cas   ┆ CAS_Class1 ┆ Mycobacter ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 96.1       ┆       ┆ -Subtype-I ┆ ium tuberc ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆ II-A       ┆ ulosis,Myc ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ …          ┆   ┆           ┆           ┆           ┆           │
│ WP_0028851 ┆ AbiE  ┆ AbiE       ┆ Klebsiella ┆ … ┆ null      ┆ 0.583174  ┆ 238       ┆ 0.780328  │
│ 55.1       ┆       ┆            ┆ sp. P1927, ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ Klebsiell… ┆   ┆           ┆           ┆           ┆           │
│ WP_0028851 ┆ AbiE  ┆ AbiE       ┆ Klebsiella ┆ … ┆ null      ┆ 0.780051  ┆ 293       ┆ 0.960656  │
│ 55.1       ┆       ┆            ┆ sp. P1927, ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ Klebsiell… ┆   ┆           ┆           ┆           ┆           │
│ WP_0028851 ┆ AbiE  ┆ AbiE       ┆ Klebsiella ┆ … ┆ null      ┆ 0.697941  ┆ 293       ┆ 0.960656  │
│ 55.1       ┆       ┆            ┆ sp. P1927, ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ Klebsiell… ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …     ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ WP_0028851 ┆ AbiE  ┆ AbiE       ┆ Klebsiella ┆ … ┆ null      ┆ 0.780051  ┆ 293       ┆ 0.960656  │
│ 55.1       ┆       ┆            ┆ sp. P1927, ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ Klebsiell… ┆   ┆           ┆           ┆           ┆           │
│ WP_0028851 ┆ AbiE  ┆ AbiE       ┆ Klebsiella ┆ … ┆ null      ┆ 0.697941  ┆ 293       ┆ 0.960656  │
│ 55.1       ┆       ┆            ┆ sp. P1927, ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ Klebsiell… ┆   ┆           ┆           ┆           ┆           │
│ WP_0028851 ┆ AbiE  ┆ AbiE       ┆ Klebsiella ┆ … ┆ null      ┆ 0.784062  ┆ 291       ┆ 0.954098  │
│ 55.1       ┆       ┆            ┆ sp. P1927, ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ Klebsiell… ┆   ┆           ┆           ┆           ┆           │
│ WP_0028851 ┆ AbiE  ┆ AbiE       ┆ Klebsiella ┆ … ┆ null      ┆ 0.690045  ┆ 238       ┆ 0.780328  │
│ 55.1       ┆       ┆            ┆ sp. P1927, ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ Klebsiell… ┆   ┆           ┆           ┆           ┆           │
│ WP_0005576 ┆ MazEF ┆ MazEF      ┆ Klebsiella ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 19.1       ┆       ┆            ┆ aerogenes, ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ Enterobac… ┆   ┆           ┆           ┆           ┆           │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [17]:
data_ann["data_GRIID"]

shape: (258_895, 71)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ accession_ ┆ type   ┆ subtype    ┆ species   ┆ … ┆ Bacterial ┆ Query_Tar ┆ Overlap_r ┆ GRIID_gen │
│ in_sys     ┆ ---    ┆ ---        ┆ ---       ┆   ┆ _Human_Le ┆ get_Overl ┆ atio      ┆ e         │
│ ---        ┆ str    ┆ str        ┆ str       ┆   ┆ n_Ratio   ┆ ap_Length ┆ ---       ┆ ---       │
│ str        ┆        ┆            ┆           ┆   ┆ ---       ┆ ---       ┆ f64       ┆ str       │
│            ┆        ┆            ┆           ┆   ┆ f64       ┆ f64       ┆           ┆           │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ WP_0037345 ┆ RM     ┆ RM_Type_II ┆ Listeria  ┆ … ┆ 1.378495  ┆ 366.0     ┆ 0.787097  ┆ Yes       │
│ 67.1       ┆        ┆            ┆ monocytog ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ enes      ┆   ┆           ┆           ┆           ┆           │
│ WP_2104222 ┆ pAgo   ┆ pAgo_LongA ┆ Dolichosp ┆ … ┆ 0.83856   ┆ 646.0     ┆ 0.894737  ┆ Yes       │
│ 14.1       ┆        ┆            ┆ ermum sp. ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ UHCC      ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ 0315A     ┆   ┆           ┆           ┆           ┆           │
│ WP_2104222 ┆ pAgo   ┆ pAgo_LongA ┆ Dolichosp ┆ … ┆ 0.83856   ┆ 646.0     ┆ 0.894737  ┆ Yes       │
│ 14.1       ┆        ┆            ┆ ermum sp. ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ UHCC      ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ 0315A     ┆   ┆           ┆           ┆           ┆           │
│ WP_0169470 ┆ Cas    ┆ CAS_Class1 ┆ Klebsiell ┆ … ┆ 0.867872  ┆ 569.0     ┆ 0.911859  ┆ Yes       │
│ 78.1       ┆        ┆ -Subtype-I ┆ a pneumon ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆ V-A        ┆ iae,Klebs ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ iel…      ┆   ┆           ┆           ┆           ┆           │
│ WP_0169470 ┆ Cas    ┆ CAS_Class1 ┆ Klebsiell ┆ … ┆ 0.883853  ┆ 591.0     ┆ 0.947115  ┆ Yes       │
│ 78.1       ┆        ┆ -Subtype-I ┆ a pneumon ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆ V-A        ┆ iae,Klebs ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ iel…      ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …      ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ WP_0009808 ┆ Shango ┆ Shango     ┆ Shigella  ┆ … ┆ 8.714286  ┆ 69.0      ┆ 0.821429  ┆ No        │
│ 65.1       ┆        ┆            ┆ dysenteri ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ ae,Escher ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ ich…      ┆   ┆           ┆           ┆           ┆           │
│ WP_0000930 ┆ Shango ┆ Shango     ┆ Escherich ┆ … ┆ 8.611765  ┆ 67.0      ┆ 0.788235  ┆ No        │
│ 92.1       ┆        ┆            ┆ ia coli   ┆   ┆           ┆           ┆           ┆           │
│ WP_0000930 ┆ Shango ┆ Shango     ┆ Escherich ┆ … ┆ 8.714286  ┆ 74.0      ┆ 0.880952  ┆ No        │
│ 92.1       ┆        ┆            ┆ ia coli   ┆   ┆           ┆           ┆           ┆           │
│ WP_0000930 ┆ Shango ┆ Shango     ┆ Escherich ┆ … ┆ 8.611765  ┆ 67.0      ┆ 0.788235  ┆ No        │
│ 92.1       ┆        ┆            ┆ ia coli   ┆   ┆           ┆           ┆           ┆           │
│ WP_0000930 ┆ Shango ┆ Shango     ┆ Escherich ┆ … ┆ 8.714286  ┆ 74.0      ┆ 0.880952  ┆ No        │
│ 92.1       ┆        ┆            ┆ ia coli   ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘