### Explore protein matches
### Julian Moran
### 2026-02-16

In [3]:
import logging
import os

from dotenv import load_dotenv

import polars as pl

# Env
load_dotenv("../.env")
INSTALL_PATH = os.environ["INSTALL_PATH"]

# Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s:%(name)s:%(message)s"
)
logger = logging.getLogger(__name__)

In [30]:
# ============================================================
#                              Args
# ============================================================

args = {
    "data_file_protein_matches_filtExtra": f"{INSTALL_PATH}/results/explore_aJain_iei_pipeline/defense_proteins_filtExtra_n=34.tsv",
    "data_file_protein_matches_filt": f"{INSTALL_PATH}/results/explore_aJain_iei_pipeline/defense_proteins_filt_n=904.tsv",
    "data_dir_alignments": f"{INSTALL_PATH}/data_sync/rcsb_pdb_align",
    "col_pm_cluster_id": "cluster_id",
    "col_pm_defProt_id": "defense_system_protein_id",
    "col_pm_hsProt_id": "protein_id"
}

In [31]:
# ============================================================
#                               In
# ============================================================

pl.Config.set_tbl_rows(10)

df_protein_matches_34 = pl.read_csv(
    args["data_file_protein_matches_filtExtra"],
    separator="\t",
    has_header=True
)

df_protein_matches_904 = pl.read_csv(
    args["data_file_protein_matches_filt"],
    separator="\t",
    has_header=True
)

df_protein_matches_34

shape: (34, 72)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ accession_ ┆ type   ┆ subtype    ┆ species   ┆ … ┆ Query_Tar ┆ Overlap_r ┆ GRIID_gen ┆ Protein_l │
│ in_sys     ┆ ---    ┆ ---        ┆ ---       ┆   ┆ get_Overl ┆ atio      ┆ e         ┆ ength_err │
│ ---        ┆ str    ┆ str        ┆ str       ┆   ┆ ap_Length ┆ ---       ┆ ---       ┆ or        │
│ str        ┆        ┆            ┆           ┆   ┆ ---       ┆ f64       ┆ str       ┆ ---       │
│            ┆        ┆            ┆           ┆   ┆ f64       ┆           ┆           ┆ f64       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ WP_1260382 ┆ RM     ┆ RM_Type_II ┆ Mesorhizo ┆ … ┆ 362.0     ┆ 0.925831  ┆ No        ┆ 0.023018  │
│ 76.1       ┆        ┆            ┆ bium sp.  ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ M9A.F.Ca. ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ ET.…      ┆   ┆           ┆           ┆           ┆           │
│ WP_2080571 ┆ RM     ┆ RM_Type_II ┆ Spiroplas ┆ … ┆ 376.0     ┆ 0.986877  ┆ No        ┆ 0.025575  │
│ 79.1       ┆        ┆            ┆ ma        ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ chinense  ┆   ┆           ┆           ┆           ┆           │
│ WP_0042687 ┆ Wadjet ┆ Wadjet_I   ┆ Bifidobac ┆ … ┆ 1130.0    ┆ 0.969957  ┆ Yes       ┆ 0.042728  │
│ 61.1       ┆        ┆            ┆ terium    ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ animalis  ┆   ┆           ┆           ┆           ┆           │
│ WP_0042687 ┆ Wadjet ┆ Wadjet_I   ┆ Bifidobac ┆ … ┆ 1146.0    ┆ 0.983691  ┆ Yes       ┆ 0.026734  │
│ 61.1       ┆        ┆            ┆ terium    ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ animalis  ┆   ┆           ┆           ┆           ┆           │
│ WP_0008629 ┆ RM     ┆ RM_Type_II ┆ Acinetoba ┆ … ┆ 341.0     ┆ 0.960563  ┆ No        ┆ 0.03794   │
│ 34.1       ┆        ┆            ┆ cter      ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ baumannii ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …      ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ WP_0042687 ┆ Wadjet ┆ Wadjet_I   ┆ Bifidobac ┆ … ┆ 1146.0    ┆ 0.983691  ┆ Yes       ┆ 0.026734  │
│ 61.1       ┆        ┆            ┆ terium    ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ animalis  ┆   ┆           ┆           ┆           ┆           │
│ WP_0174173 ┆ Wadjet ┆ Wadjet_III ┆ Bacillus  ┆ … ┆ 1008.0    ┆ 0.941176  ┆ No        ┆ 0.018332  │
│ 05.1       ┆        ┆            ┆ amyloliqu ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ efaciens, ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ Bac…      ┆   ┆           ┆           ┆           ┆           │
│ WP_2080571 ┆ RM     ┆ RM_Type_II ┆ Spiroplas ┆ … ┆ 366.0     ┆ 0.99187   ┆ No        ┆ 0.03252   │
│ 79.1       ┆        ┆            ┆ ma        ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ chinense  ┆   ┆           ┆           ┆           ┆           │
│ WP_2080571 ┆ RM     ┆ RM_Type_II ┆ Spiroplas ┆ … ┆ 376.0     ┆ 0.986877  ┆ No        ┆ 0.025575  │
│ 79.1       ┆        ┆            ┆ ma        ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ chinense  ┆   ┆           ┆           ┆           ┆           │
│ WP_0042687 ┆ Wadjet ┆ Wadjet_I   ┆ Bifidobac ┆ … ┆ 1130.0    ┆ 0.969957  ┆ Yes       ┆ 0.042728  │
│ 61.1       ┆        ┆            ┆ terium    ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ animalis  ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [33]:
# ============================================================
#                               Summary
# ============================================================

def summarise_protein_matches(
        df: pl.DataFrame
) -> pl.DataFrame:

    logger.info(f"N protein matches: {len(df)}")

    unique_clusters = df[args["col_pm_cluster_id"]].unique()
    logger.info(f"N unique clusters: {len(unique_clusters)}")

    unique_protein_pairs = df[
        [args["col_pm_defProt_id"], args["col_pm_hsProt_id"], args["col_pm_cluster_id"]]
    ].unique().sort("cluster_id")

    logger.info(f"N unique protein pairs: {len(unique_protein_pairs)}")
    logger.info(unique_clusters)

    return unique_protein_pairs

unique_protein_pairs_34 = summarise_protein_matches(df_protein_matches_34)
unique_protein_pairs_904 = summarise_protein_matches(df_protein_matches_904)

INFO:__main__:N protein matches: 34
INFO:__main__:N unique clusters: 3
INFO:__main__:N unique protein pairs: 34
INFO:__main__:shape: (3,)
Series: 'cluster_id' [str]
[
	"A0A1W9R9X2"
	"A0A6I4ZMH2"
	"A0A4P9X374"
]
INFO:__main__:N protein matches: 904
INFO:__main__:N unique clusters: 17
INFO:__main__:N unique protein pairs: 297
INFO:__main__:shape: (17,)
Series: 'cluster_id' [str]
[
	"A0A2E8RBP0"
	"A0A480PGP1"
	"A0A2E7NAI8"
	"A0A2H6NEM0"
	"A0A4Q9LAP2"
	…
	"A0A846H7L1"
	"A0A7S4UXI5"
	"A0A4P9X374"
	"A0A355UP19"
	"E4U3I0"
]

In [36]:
pl.Config.set_tbl_rows(len(unique_protein_pairs_34))

unique_protein_pairs_34

shape: (34, 3)
┌───────────────────────────┬────────────┬────────────┐
│ defense_system_protein_id ┆ protein_id ┆ cluster_id │
│ ---                       ┆ ---        ┆ ---        │
│ str                       ┆ str        ┆ str        │
╞═══════════════════════════╪════════════╪════════════╡
│ A0A411A3U6                ┆ A0A2S1ZR87 ┆ A0A1W9R9X2 │
│ A0A411A3U6                ┆ A0A2S1ZR79 ┆ A0A1W9R9X2 │
│ A0A411A3U6                ┆ Q8IY18     ┆ A0A1W9R9X2 │
│ A0A411A3U6                ┆ Q96SB8     ┆ A0A1W9R9X2 │
│ B8DW98                    ┆ O95347     ┆ A0A4P9X374 │
│ B8DW98                    ┆ B0AZQ4     ┆ A0A4P9X374 │
│ B8DW98                    ┆ A8K984     ┆ A0A4P9X374 │
│ B8DW98                    ┆ B7ZLZ7     ┆ A0A4P9X374 │
│ A0A806FWR7                ┆ A8K984     ┆ A0A4P9X374 │
│ B8DW98                    ┆ Q9UQE7     ┆ A0A4P9X374 │
│ A0A806FWR7                ┆ O95347     ┆ A0A4P9X374 │
│ B8DW98                    ┆ Q86VX4     ┆ A0A4P9X374 │
│ B8DW98                    ┆ B3KMB1     ┆ A0A4P9X374 │
│ A0A806FWR7                ┆ Q86VX4     ┆ A0A4P9X374 │
│ A0A806FWR7                ┆ B0AZQ4     ┆ A0A4P9X374 │
│ A0A806FWR7                ┆ Q9UQE7     ┆ A0A4P9X374 │
│ B8DW98                    ┆ G8JLG1     ┆ A0A4P9X374 │
│ A0A806FWR7                ┆ B7ZLZ7     ┆ A0A4P9X374 │
│ A0A806FWR7                ┆ B3KMB1     ┆ A0A4P9X374 │
│ A0A5B9Y4K1                ┆ Q6ICS7     ┆ A0A6I4ZMH2 │
│ A0A0M2KG49                ┆ A0A0U1U562 ┆ A0A6I4ZMH2 │
│ A0A0H3HBJ4                ┆ A0A0U1U562 ┆ A0A6I4ZMH2 │
│ A0A5B9Y4K1                ┆ O14717     ┆ A0A6I4ZMH2 │
│ A0A0M2KG49                ┆ Q6ICS7     ┆ A0A6I4ZMH2 │
│ A0A0D5YDQ8                ┆ A0A0U1U562 ┆ A0A6I4ZMH2 │
│ A0A3Q8YDX2                ┆ Q6ICS7     ┆ A0A6I4ZMH2 │
│ A0A7U3YA08                ┆ A0A0U1U562 ┆ A0A6I4ZMH2 │
│ A0A0J0ZLL5                ┆ A0A0U1U562 ┆ A0A6I4ZMH2 │
│ A0A5B9Y4K1                ┆ A0A0U1U562 ┆ A0A6I4ZMH2 │
│ C1J0P2                    ┆ O14717     ┆ A0A6I4ZMH2 │
│ A0A0M2KG49                ┆ O14717     ┆ A0A6I4ZMH2 │
│ A0A5K6CLK6                ┆ A0A0U1U562 ┆ A0A6I4ZMH2 │
│ A0A3Q8YDX2                ┆ O14717     ┆ A0A6I4ZMH2 │
│ C1J0P2                    ┆ Q6ICS7     ┆ A0A6I4ZMH2 │
└───────────────────────────┴────────────┴────────────┘

In [37]:
pl.Config.set_tbl_rows(len(unique_protein_pairs_904))

unique_protein_pairs_904

shape: (297, 3)
┌───────────────────────────┬────────────┬────────────┐
│ defense_system_protein_id ┆ protein_id ┆ cluster_id │
│ ---                       ┆ ---        ┆ ---        │
│ str                       ┆ str        ┆ str        │
╞═══════════════════════════╪════════════╪════════════╡
│ Q9RFR9                    ┆ A0A6Q8PFJ4 ┆ A0A1I1GWW8 │
│ Q9RFR9                    ┆ A0A6Q8PGA3 ┆ A0A1I1GWW8 │
│ A0A1Y6A5H7                ┆ O95140     ┆ A0A1I1GWW8 │
│ A0A556BFS8                ┆ A0A6Q8PGA3 ┆ A0A1I1GWW8 │
│ Q9RFR9                    ┆ A0A6Q8PGV8 ┆ A0A1I1GWW8 │
│ A0A556BFS8                ┆ A0A6Q8PGV8 ┆ A0A1I1GWW8 │
│ A0A556BFS8                ┆ O95140     ┆ A0A1I1GWW8 │
│ A0A1Y6A5H7                ┆ A0A6Q8PGV8 ┆ A0A1I1GWW8 │
│ A0A556BFS8                ┆ A0A6Q8PFJ4 ┆ A0A1I1GWW8 │
│ A0A1Y6A5H7                ┆ A0A6Q8PGA3 ┆ A0A1I1GWW8 │
│ Q9RFR9                    ┆ O95140     ┆ A0A1I1GWW8 │
│ A0A1Y6A5H7                ┆ A0A6Q8PFJ4 ┆ A0A1I1GWW8 │
│ A0A411A3U6                ┆ Q96SB8     ┆ A0A1W9R9X2 │
│ A0A411A3U6                ┆ A0A2S1ZR87 ┆ A0A1W9R9X2 │
│ A0A411A3U6                ┆ A0A2S1ZR79 ┆ A0A1W9R9X2 │
│ A0A411A3U6                ┆ Q8IY18     ┆ A0A1W9R9X2 │
│ A0A5C0DWF7                ┆ Q9HCK5     ┆ A0A2A2KXD5 │
│ A0A2K8UJG1                ┆ A0A7P0TA11 ┆ A0A2E7NAI8 │
│ A0A5B9D673                ┆ A0A7P0TA11 ┆ A0A2E7NAI8 │
│ D5EID4                    ┆ A0A7P0TA11 ┆ A0A2E7NAI8 │
│ A0A222EQ20                ┆ B4DT76     ┆ A0A2E7NAI8 │
│ A0A7H5CVR4                ┆ B4DT76     ┆ A0A2E7NAI8 │
│ A0A3G3IIY6                ┆ A0A7P0TA11 ┆ A0A2E7NAI8 │
│ A0A5B9D673                ┆ B4DT76     ┆ A0A2E7NAI8 │
│ Q3A0F3                    ┆ B4DT76     ┆ A0A2E7NAI8 │
│ A0A109D532                ┆ B4DT76     ┆ A0A2E7NAI8 │
│ A0A6P1XY11                ┆ B4DT76     ┆ A0A2E7NAI8 │
│ D5EID4                    ┆ B4DT76     ┆ A0A2E7NAI8 │
│ D1ADX3                    ┆ A0A7P0TA11 ┆ A0A2E7NAI8 │
│ A0A7L4ZQB6                ┆ B4DT76     ┆ A0A2E7NAI8 │
│ U5Q1R3                    ┆ A0A7P0TA11 ┆ A0A2E7NAI8 │
│ I7LJ27                    ┆ A0A7P0TA11 ┆ A0A2E7NAI8 │
│ I7LJ27                    ┆ B4DT76     ┆ A0A2E7NAI8 │
│ A0A222EQ20                ┆ A0A7P0TA11 ┆ A0A2E7NAI8 │
│ Q73LQ7                    ┆ A0A7P0TA11 ┆ A0A2E7NAI8 │
│ A0A5S9F266                ┆ A0A7P0TA11 ┆ A0A2E7NAI8 │
│ A0A2Z2MWB5                ┆ A0A7P0TA11 ┆ A0A2E7NAI8 │
│ A0A2K8UJG1                ┆ B4DT76     ┆ A0A2E7NAI8 │
│ A0A0K1EKA3                ┆ B4DT76     ┆ A0A2E7NAI8 │
│ D1ADX3                    ┆ B4DT76     ┆ A0A2E7NAI8 │
│ A9L1Z3                    ┆ A0A7P0TA11 ┆ A0A2E7NAI8 │
│ A0A5S9F266                ┆ B4DT76     ┆ A0A2E7NAI8 │
│ A0A3G3IIY6                ┆ B4DT76     ┆ A0A2E7NAI8 │
│ A9L1Z3                    ┆ B4DT76     ┆ A0A2E7NAI8 │
│ A0A6P1L2S3                ┆ B4DT76     ┆ A0A2E7NAI8 │
│ L0L185                    ┆ A0A7P0TA11 ┆ A0A2E7NAI8 │
│ A0A2Z2MWB5                ┆ B4DT76     ┆ A0A2E7NAI8 │
│ A0A3Q0KZ59                ┆ B4DT76     ┆ A0A2E7NAI8 │
│ A0A0K1EKA3                ┆ A0A7P0TA11 ┆ A0A2E7NAI8 │
│ A0A6P1XY11                ┆ A0A7P0TA11 ┆ A0A2E7NAI8 │
│ U5Q1R3                    ┆ B4DT76     ┆ A0A2E7NAI8 │
│ Q3A0F3                    ┆ A0A7P0TA11 ┆ A0A2E7NAI8 │
│ A0A3G3IG56                ┆ B4DT76     ┆ A0A2E7NAI8 │
│ A0A3Q0KZ59                ┆ A0A7P0TA11 ┆ A0A2E7NAI8 │
│ A0A3G3IG56                ┆ A0A7P0TA11 ┆ A0A2E7NAI8 │
│ A0A0X3BJA1                ┆ B4DT76     ┆ A0A2E7NAI8 │
│ A0A7H5CVR4                ┆ A0A7P0TA11 ┆ A0A2E7NAI8 │
│ A0A109D532                ┆ A0A7P0TA11 ┆ A0A2E7NAI8 │
│ A0A7G5XFN1                ┆ B4DT76     ┆ A0A2E7NAI8 │
│ A0A7G5XFN1                ┆ A0A7P0TA11 ┆ A0A2E7NAI8 │
│ M9SLJ0                    ┆ A0A7P0TA11 ┆ A0A2E7NAI8 │
│ Q73LQ7                    ┆ B4DT76     ┆ A0A2E7NAI8 │
│ A0A7L4ZQB6                ┆ A0A7P0TA11 ┆ A0A2E7NAI8 │
│ M9SLJ0                    ┆ B4DT76     ┆ A0A2E7NAI8 │
│ A0A6P1L2S3                ┆ A0A7P0TA11 ┆ A0A2E7NAI8 │
│ L0L185                    ┆ B4DT76     ┆ A0A2E7NAI8 │
│ A0A0X3BJA1                ┆ A0A7P0TA11 ┆ A0A2E7NAI8 │
│ A0A2Z5C2A5                ┆ A0A7P0TBC2 ┆ A0A2E8RBP0 │
│ A0A2Z5C2A5                ┆ Q59FC6     ┆ A0A2E8RBP0 │
│ G8X4N1                    ┆ A0A7P0T9U2 ┆ A0A2H6NEM0 │
│ A0A1A9K893                ┆ A0A7P0T9U2 ┆ A0A2H6NEM0 │
│ A0A208XV37                ┆ A0A7P0T9U2 ┆ A0A2H6NEM0 │
│ A0A5R9QEY4                ┆ A0A7P0T9U2 ┆ A0A2H6NEM0 │
│ A0A4Q8LW35                ┆ A0A7P0T9U2 ┆ A0A2H6NEM0 │
│ F4G5K0                    ┆ A0A7P0T9U2 ┆ A0A2H6NEM0 │
│ A0A2S5TG67                ┆ A0A7P0T9U2 ┆ A0A2H6NEM0 │
│ A0A2J5C9H7                ┆ C9J168     ┆ A0A2S9BGI2 │
│ F6FPD4                    ┆ Q9H4L7     ┆ A0A355UP19 │
│ A0A1D7QX01                ┆ Q9H4L7     ┆ A0A355UP19 │
│ A0A6M5UJV8                ┆ Q9H4L7     ┆ A0A355UP19 │
│ A0A6M5UJV8                ┆ B4DLD8     ┆ A0A355UP19 │
│ A0A4P8XGJ0                ┆ Q9H4L7     ┆ A0A355UP19 │
│ A0A0F7PNU1                ┆ B4DLD8     ┆ A0A355UP19 │
│ A0A2D2MBG9                ┆ Q9H4L7     ┆ A0A355UP19 │
│ A0A5J6QTB0                ┆ Q9H4L7     ┆ A0A355UP19 │
│ A0A6N1ASS5                ┆ B4DLD8     ┆ A0A355UP19 │
│ A0A4P8XGJ0                ┆ B4DLD8     ┆ A0A355UP19 │
│ G4T261                    ┆ Q9H4L7     ┆ A0A355UP19 │
│ A0A5B9GHV7                ┆ Q9H4L7     ┆ A0A355UP19 │
│ A0A142CZW3                ┆ B4DLD8     ┆ A0A355UP19 │
│ A0A2U2XIN6                ┆ Q9H4L7     ┆ A0A355UP19 │
│ A6VE70                    ┆ B4DLD8     ┆ A0A355UP19 │
│ A0A2R3IRC4                ┆ Q9H4L7     ┆ A0A355UP19 │
│ A0A2Z3J444                ┆ B4DLD8     ┆ A0A355UP19 │
│ A0A348G322                ┆ B4DLD8     ┆ A0A355UP19 │
│ F6BIK3                    ┆ Q9H4L7     ┆ A0A355UP19 │
│ A0A840BVI6                ┆ Q9H4L7     ┆ A0A355UP19 │
│ A0A2Z3J444                ┆ Q9H4L7     ┆ A0A355UP19 │
│ A0A142NN85                ┆ Q9H4L7     ┆ A0A355UP19 │
│ L0GYV0                    ┆ Q9H4L7     ┆ A0A355UP19 │
│ A0A5J6QTB0                ┆ B4DLD8     ┆ A0A355UP19 │
│ A0A840BVI6                ┆ B4DLD8     ┆ A0A355UP19 │
│ A0A5C1AV28                ┆ B4DLD8     ┆ A0A355UP19 │
│ A0A5B9GHV7                ┆ B4DLD8     ┆ A0A355UP19 │
│ A0A1Z4VRC4                ┆ B4DLD8     ┆ A0A355UP19 │
│ A0A2R3IRC4                ┆ B4DLD8     ┆ A0A355UP19 │
│ A0A140GVI1                ┆ Q9H4L7     ┆ A0A355UP19 │
│ F6BIK3                    ┆ B4DLD8     ┆ A0A355UP19 │
│ A0A2R3QW93                ┆ B4DLD8     ┆ A0A355UP19 │
│ A0A2L0TZN5                ┆ Q9H4L7     ┆ A0A355UP19 │
│ A0A142CZW3                ┆ Q9H4L7     ┆ A0A355UP19 │
│ A0A0K1PGI2                ┆ B4DLD8     ┆ A0A355UP19 │
│ A0A1D7QX01                ┆ B4DLD8     ┆ A0A355UP19 │
│ A0A6N1ASS5                ┆ Q9H4L7     ┆ A0A355UP19 │
│ G4T261                    ┆ B4DLD8     ┆ A0A355UP19 │
│ L0GYV0                    ┆ B4DLD8     ┆ A0A355UP19 │
│ A0A140GVI1                ┆ B4DLD8     ┆ A0A355UP19 │
│ A0A2D2MBG9                ┆ B4DLD8     ┆ A0A355UP19 │
│ A0A2L0TZN5                ┆ B4DLD8     ┆ A0A355UP19 │
│ A0A348G322                ┆ Q9H4L7     ┆ A0A355UP19 │
│ A0A0K1PGI2                ┆ Q9H4L7     ┆ A0A355UP19 │
│ A0A0F7PNU1                ┆ Q9H4L7     ┆ A0A355UP19 │
│ Q2SG57                    ┆ Q9H4L7     ┆ A0A355UP19 │
│ A0A0D5M5G2                ┆ Q9H4L7     ┆ A0A355UP19 │
│ A0A0D5M5G2                ┆ B4DLD8     ┆ A0A355UP19 │
│ F6FPD4                    ┆ B4DLD8     ┆ A0A355UP19 │
│ A0A1Z4VRC4                ┆ Q9H4L7     ┆ A0A355UP19 │
│ A0A2R3QW93                ┆ Q9H4L7     ┆ A0A355UP19 │
│ A0A5J6QBU2                ┆ B4DLD8     ┆ A0A355UP19 │
│ A0A5J6QBU2                ┆ Q9H4L7     ┆ A0A355UP19 │
│ A0A5C1AV28                ┆ Q9H4L7     ┆ A0A355UP19 │
│ A6VE70                    ┆ Q9H4L7     ┆ A0A355UP19 │
│ A0A2U2XIN6                ┆ B4DLD8     ┆ A0A355UP19 │
│ A0A142NN85                ┆ B4DLD8     ┆ A0A355UP19 │
│ Q2SG57                    ┆ B4DLD8     ┆ A0A355UP19 │
│ A0A414Z6D3                ┆ B4DY67     ┆ A0A480PGP1 │
│ A9GZE3                    ┆ B4DY67     ┆ A0A480PGP1 │
│ A0A7J5JBR4                ┆ B4DY67     ┆ A0A480PGP1 │
│ A0A414Z6D3                ┆ Q9NXV9     ┆ A0A480PGP1 │
│ R9HFH2                    ┆ B4DY67     ┆ A0A480PGP1 │
│ R9HFH2                    ┆ Q9NXV9     ┆ A0A480PGP1 │
│ A0A7W4I845                ┆ Q9NXV9     ┆ A0A480PGP1 │
│ A9GZE3                    ┆ Q9NXV9     ┆ A0A480PGP1 │
│ A0A7W4I845                ┆ B4DY67     ┆ A0A480PGP1 │
│ A0A7J5JBR4                ┆ Q9NXV9     ┆ A0A480PGP1 │
│ B8DW98                    ┆ A8K984     ┆ A0A4P9X374 │
│ B8DW98                    ┆ Q86VX4     ┆ A0A4P9X374 │
│ B8DW98                    ┆ O95347     ┆ A0A4P9X374 │
│ B8DW98                    ┆ B7ZLZ7     ┆ A0A4P9X374 │
│ B8DW98                    ┆ B0AZQ4     ┆ A0A4P9X374 │
│ B8DW98                    ┆ Q9UQE7     ┆ A0A4P9X374 │
│ B8DW98                    ┆ E9PD53     ┆ A0A4P9X374 │
│ A0A806FWR7                ┆ B7ZLZ7     ┆ A0A4P9X374 │
│ B8DW98                    ┆ G8JLG1     ┆ A0A4P9X374 │
│ B8DW98                    ┆ Q14683     ┆ A0A4P9X374 │
│ B8DW98                    ┆ Q8NDV3     ┆ A0A4P9X374 │
│ A0A806FWR7                ┆ A0A6Q8PHC3 ┆ A0A4P9X374 │
│ A0A806FWR7                ┆ Q9UQE7     ┆ A0A4P9X374 │
│ B8DW98                    ┆ B3KMB1     ┆ A0A4P9X374 │
│ B8DW98                    ┆ B3KXX5     ┆ A0A4P9X374 │
│ A0A806FWR7                ┆ Q86VX4     ┆ A0A4P9X374 │
│ A0A806FWR7                ┆ B3KMB1     ┆ A0A4P9X374 │
│ A0A806FWR7                ┆ Q14683     ┆ A0A4P9X374 │
│ A0A806FWR7                ┆ B3KXX5     ┆ A0A4P9X374 │
│ A0A806FWR7                ┆ O95347     ┆ A0A4P9X374 │
│ A0A806FWR7                ┆ B0AZQ4     ┆ A0A4P9X374 │
│ A0A806FWR7                ┆ Q8NDV3     ┆ A0A4P9X374 │
│ B8DW98                    ┆ A0A6Q8PHC3 ┆ A0A4P9X374 │
│ A0A806FWR7                ┆ E9PD53     ┆ A0A4P9X374 │
│ A0A806FWR7                ┆ A0A384MR33 ┆ A0A4P9X374 │
│ A0A806FWR7                ┆ G8JLG1     ┆ A0A4P9X374 │
│ A0A806FWR7                ┆ A8K984     ┆ A0A4P9X374 │
│ B8DW98                    ┆ Q9NTJ3     ┆ A0A4P9X374 │
│ B8DW98                    ┆ A0A384MR33 ┆ A0A4P9X374 │
│ A0A806FWR7                ┆ Q9NTJ3     ┆ A0A4P9X374 │
│ A0A3S0HN58                ┆ A8MPP1     ┆ A0A4Q9LAP2 │
│ A0A3S0HN58                ┆ Q2NKM7     ┆ A0A4Q9LAP2 │
│ A0A3S0HN58                ┆ A8MX75     ┆ A0A4Q9LAP2 │
│ A0A2R4NGD3                ┆ P18074     ┆ A0A4Q9LAP2 │
│ A0A2R4NGD3                ┆ A0A804HK53 ┆ A0A4Q9LAP2 │
│ A0A483H222                ┆ A0A804HK53 ┆ A0A4Q9LAP2 │
│ A0A3S0HN58                ┆ D6RA96     ┆ A0A4Q9LAP2 │
│ A0A2R4NGD3                ┆ A8MPP1     ┆ A0A4Q9LAP2 │
│ A0A483H222                ┆ P18074     ┆ A0A4Q9LAP2 │
│ A0A483H222                ┆ Q2NKM7     ┆ A0A4Q9LAP2 │
│ A0A3S0HN58                ┆ P18074     ┆ A0A4Q9LAP2 │
│ A0A2R4NGD3                ┆ A8MX75     ┆ A0A4Q9LAP2 │
│ A0A2R4NGD3                ┆ Q92771     ┆ A0A4Q9LAP2 │
│ A0A483H222                ┆ A8MX75     ┆ A0A4Q9LAP2 │
│ A0A3S0HN58                ┆ Q92771     ┆ A0A4Q9LAP2 │
│ A0A483H222                ┆ D6RA96     ┆ A0A4Q9LAP2 │
│ A0A2R4NGD3                ┆ D6RA96     ┆ A0A4Q9LAP2 │
│ A0A483H222                ┆ Q92771     ┆ A0A4Q9LAP2 │
│ A0A483H222                ┆ A8MPP1     ┆ A0A4Q9LAP2 │
│ A0A2R4NGD3                ┆ Q2NKM7     ┆ A0A4Q9LAP2 │
│ A0A3S0HN58                ┆ A0A804HK53 ┆ A0A4Q9LAP2 │
│ A0A0C7K942                ┆ Q9H8B9     ┆ A0A6C0LXL7 │
│ A0A5P0JA10                ┆ Q9H8B9     ┆ A0A6C0LXL7 │
│ A0A2Z3X8L4                ┆ Q9H8B9     ┆ A0A6C0LXL7 │
│ A0A426EXV0                ┆ Q9H8B9     ┆ A0A6C0LXL7 │
│ A0A2J4ZZZ2                ┆ Q9H8B9     ┆ A0A6C0LXL7 │
│ A0A483GQF5                ┆ Q9H8B9     ┆ A0A6C0LXL7 │
│ A0A3Q8YDX2                ┆ A0A0U1U562 ┆ A0A6I4ZMH2 │
│ A0A0M2KG49                ┆ Q6ICS7     ┆ A0A6I4ZMH2 │
│ C1J0P2                    ┆ B7Z1Y7     ┆ A0A6I4ZMH2 │
│ A0A5K6CLK6                ┆ Q6ICS7     ┆ A0A6I4ZMH2 │
│ A0A2A2XKR4                ┆ A0A0U1U562 ┆ A0A6I4ZMH2 │
│ A0A059Y842                ┆ O14717     ┆ A0A6I4ZMH2 │
│ A0A0H3HBJ4                ┆ B7Z1Y7     ┆ A0A6I4ZMH2 │
│ C1J0P2                    ┆ O14717     ┆ A0A6I4ZMH2 │
│ A0A3Q8YDX2                ┆ B7Z1Y7     ┆ A0A6I4ZMH2 │
│ A0A0H3HBJ4                ┆ O14717     ┆ A0A6I4ZMH2 │
│ O87740                    ┆ O14717     ┆ A0A6I4ZMH2 │
│ A0A059Y842                ┆ Q6ICS7     ┆ A0A6I4ZMH2 │
│ A0A3Q8YDX2                ┆ Q6ICS7     ┆ A0A6I4ZMH2 │
│ A0A5B9Y4K1                ┆ A0A0U1U562 ┆ A0A6I4ZMH2 │
│ A0A0J0ZLL5                ┆ O14717     ┆ A0A6I4ZMH2 │
│ A0A059Y842                ┆ A0A0U1U562 ┆ A0A6I4ZMH2 │
│ C1J0P2                    ┆ Q6ICS7     ┆ A0A6I4ZMH2 │
│ A0A7U3YA08                ┆ B7Z1Y7     ┆ A0A6I4ZMH2 │
│ A0A0J0ZLL5                ┆ B4DQZ2     ┆ A0A6I4ZMH2 │
│ A0A0D5YDQ8                ┆ B4DQZ2     ┆ A0A6I4ZMH2 │
│ A0A5B9Y4K1                ┆ B7Z1Y7     ┆ A0A6I4ZMH2 │
│ A0A2N8U1S8                ┆ Q6ICS7     ┆ A0A6I4ZMH2 │
│ O87740                    ┆ Q6ICS7     ┆ A0A6I4ZMH2 │
│ A0A0H3HBJ4                ┆ Q6ICS7     ┆ A0A6I4ZMH2 │
│ A0A0J0ZLL5                ┆ Q6ICS7     ┆ A0A6I4ZMH2 │
│ A0A2A2XKR4                ┆ Q6ICS7     ┆ A0A6I4ZMH2 │
│ O87740                    ┆ A0A0U1U562 ┆ A0A6I4ZMH2 │
│ A0A5K6CLK6                ┆ A0A0U1U562 ┆ A0A6I4ZMH2 │
│ A0A0J0ZLL5                ┆ B7Z1Y7     ┆ A0A6I4ZMH2 │
│ C1J0P2                    ┆ A0A0U1U562 ┆ A0A6I4ZMH2 │
│ A0A7U3YA08                ┆ Q6ICS7     ┆ A0A6I4ZMH2 │
│ M4NAQ2                    ┆ A0A0U1U562 ┆ A0A6I4ZMH2 │
│ O87740                    ┆ B7Z1Y7     ┆ A0A6I4ZMH2 │
│ A0A2A2XKR4                ┆ B4DQZ2     ┆ A0A6I4ZMH2 │
│ A0A0M2KG49                ┆ B7Z1Y7     ┆ A0A6I4ZMH2 │
│ A0A5K6CLK6                ┆ B4DQZ2     ┆ A0A6I4ZMH2 │
│ A0A2N8U1S8                ┆ A0A0U1U562 ┆ A0A6I4ZMH2 │
│ A0A059Y842                ┆ B4DQZ2     ┆ A0A6I4ZMH2 │
│ A0A059Y842                ┆ B7Z1Y7     ┆ A0A6I4ZMH2 │
│ A0A0D5YDQ8                ┆ Q6ICS7     ┆ A0A6I4ZMH2 │
│ A0A5B9Y4K1                ┆ B4DQZ2     ┆ A0A6I4ZMH2 │
│ M4NAQ2                    ┆ O14717     ┆ A0A6I4ZMH2 │
│ A0A2N8U1S8                ┆ O14717     ┆ A0A6I4ZMH2 │
│ A0A7U3YA08                ┆ A0A0U1U562 ┆ A0A6I4ZMH2 │
│ A0A0M2KG49                ┆ O14717     ┆ A0A6I4ZMH2 │
│ A0A2N8U1S8                ┆ B7Z1Y7     ┆ A0A6I4ZMH2 │
│ M4NAQ2                    ┆ B7Z1Y7     ┆ A0A6I4ZMH2 │
│ A0A0D5YDQ8                ┆ A0A0U1U562 ┆ A0A6I4ZMH2 │
│ A0A2A2XKR4                ┆ O14717     ┆ A0A6I4ZMH2 │
│ A0A3Q8YDX2                ┆ O14717     ┆ A0A6I4ZMH2 │
│ A0A0D5YDQ8                ┆ O14717     ┆ A0A6I4ZMH2 │
│ A0A2N8U1S8                ┆ B4DQZ2     ┆ A0A6I4ZMH2 │
│ A0A5B9Y4K1                ┆ O14717     ┆ A0A6I4ZMH2 │
│ C1J0P2                    ┆ B4DQZ2     ┆ A0A6I4ZMH2 │
│ A0A2A2XKR4                ┆ B7Z1Y7     ┆ A0A6I4ZMH2 │
│ A0A5K6CLK6                ┆ B7Z1Y7     ┆ A0A6I4ZMH2 │
│ A0A5K6CLK6                ┆ O14717     ┆ A0A6I4ZMH2 │
│ A0A5B9Y4K1                ┆ Q6ICS7     ┆ A0A6I4ZMH2 │
│ A0A0D5YDQ8                ┆ B7Z1Y7     ┆ A0A6I4ZMH2 │
│ A0A0J0ZLL5                ┆ A0A0U1U562 ┆ A0A6I4ZMH2 │
│ A0A0H3HBJ4                ┆ A0A0U1U562 ┆ A0A6I4ZMH2 │
│ O87740                    ┆ B4DQZ2     ┆ A0A6I4ZMH2 │
│ A0A3Q8YDX2                ┆ B4DQZ2     ┆ A0A6I4ZMH2 │
│ M4NAQ2                    ┆ B4DQZ2     ┆ A0A6I4ZMH2 │
│ A0A7U3YA08                ┆ B4DQZ2     ┆ A0A6I4ZMH2 │
│ A0A0M2KG49                ┆ A0A0U1U562 ┆ A0A6I4ZMH2 │
│ A0A7U3YA08                ┆ O14717     ┆ A0A6I4ZMH2 │
│ M4NAQ2                    ┆ Q6ICS7     ┆ A0A6I4ZMH2 │
│ A0A0H3HBJ4                ┆ B4DQZ2     ┆ A0A6I4ZMH2 │
│ A0A0M2KG49                ┆ B4DQZ2     ┆ A0A6I4ZMH2 │
│ A7MEH1                    ┆ B3KX98     ┆ A0A7S4UXI5 │
│ A0A0U3JUV3                ┆ B3KX98     ┆ A0A7S4UXI5 │
│ A0A0M4U868                ┆ B3KX98     ┆ A0A7S4UXI5 │
│ K0I5J5                    ┆ B3KX98     ┆ A0A7S4UXI5 │
│ A0A7L6L5R7                ┆ B3KX98     ┆ A0A7S4UXI5 │
│ A0A7T2PI71                ┆ B3KX98     ┆ A0A7S4UXI5 │
│ A0A6L8M512                ┆ B3KX98     ┆ A0A7S4UXI5 │
│ A0A370UZQ6                ┆ B3KX98     ┆ A0A7S4UXI5 │
│ A0A7U4QPM2                ┆ B3KX98     ┆ A0A7S4UXI5 │
│ Q1QC66                    ┆ B3KX98     ┆ A0A7S4UXI5 │
│ A0A6I6W380                ┆ B3KX98     ┆ A0A7S4UXI5 │
│ A0A7G9SRY9                ┆ B3KX98     ┆ A0A7S4UXI5 │
│ A0A515D6D4                ┆ B3KX98     ┆ A0A7S4UXI5 │
│ A0A7S7ADN0                ┆ B3KX98     ┆ A0A7S4UXI5 │
│ G7LQI9                    ┆ B3KX98     ┆ A0A7S4UXI5 │
│ A0A062GSQ6                ┆ B3KX98     ┆ A0A7S4UXI5 │
│ A0A7H9K8N6                ┆ B3KX98     ┆ A0A7S4UXI5 │
│ N8RCV2                    ┆ B3KX98     ┆ A0A7S4UXI5 │
│ Q3Y0J6                    ┆ O43598     ┆ A0A846H7L1 │
│ M4NPS1                    ┆ O43598     ┆ A0A846H7L1 │
│ A0A829F2V1                ┆ O43598     ┆ A0A846H7L1 │
│ A0A1A7S5M2                ┆ O43598     ┆ A0A846H7L1 │
│ A0A6P1GFG5                ┆ Q17R31     ┆ E4U3I0     │
│ A0A0U1RHB2                ┆ A0A669KBB4 ┆ T0L9T3     │
│ X5EGL0                    ┆ A0A669KBB4 ┆ T0L9T3     │
└───────────────────────────┴────────────┴────────────┘