### Explore FoldSeq datasets
### Julian Moran
### 2026-02-03

In [ ]:
import os

import polars as pl

from dotenv import load_dotenv

# Env
load_dotenv("../.env", override=True)
INSTALL_PATH  = os.environ["INSTALL_PATH"]

print(INSTALL_PATH)

In [15]:
# ============================================================
#                           Args
# ============================================================

args = {
    "data_file_cluster_IDs": f"{INSTALL_PATH}/data_sync/foldSeek_1_clusterIDs_n200_000.tsv",
    "data_file_SAP_GO": f"{INSTALL_PATH}/data_sync/foldSeek_3_SAP_GOterms.tsv",
    "data_file_cluster_sims": f"{INSTALL_PATH}/data_sync/foldSeek_6_clusterSims_n200_000.tsv"
}

In [16]:
# ============================================================
#                           In
# ============================================================

df_cluster_IDs = pl.read_csv(
    args["data_file_cluster_IDs"],
    separator="\t",
    has_header=True
)

df_sap_go = pl.read_csv(
    args["data_file_SAP_GO"],
    separator="\t",
    has_header=True
)

df_cluster_sims = pl.read_csv(
    args["data_file_cluster_IDs"],
    separator="\t",
    has_header=True
)

df_cluster_IDs

shape: (200_000, 3)
┌────────────┬────────────┬─────────┐
│ entryID    ┆ repID      ┆ eValue  │
│ ---        ┆ ---        ┆ ---     │
│ str        ┆ str        ┆ i64     │
╞════════════╪════════════╪═════════╡
│ A0A009E921 ┆ A0A009E921 ┆ 1310605 │
│ A0A009F5K6 ┆ A0A009E921 ┆ 1310605 │
│ A0A009E9H3 ┆ A0A009E9H3 ┆ 1310605 │
│ A0A484ZLT0 ┆ A0A009E9H3 ┆ 82979   │
│ A0A009ECR5 ┆ A0A009ECR5 ┆ 1310605 │
│ …          ┆ …          ┆ …       │
│ A0A2H1H4H2 ┆ A0A067MFQ6 ┆ 1276532 │
│ A0A6A5RUW1 ┆ A0A067MFQ6 ┆ 1150837 │
│ A0A6A5UGB0 ┆ A0A067MFQ6 ┆ 147558  │
│ A0A6A6RXS7 ┆ A0A067MFQ6 ┆ 1395130 │
│ A0A067MFS2 ┆ A0A067MFS2 ┆ 930990  │
└────────────┴────────────┴─────────┘

In [9]:
df_cluster_sims

shape: (200_000, 3)
┌────────────┬────────────┬─────────┐
│ entryID    ┆ repID      ┆ eValue  │
│ ---        ┆ ---        ┆ ---     │
│ str        ┆ str        ┆ i64     │
╞════════════╪════════════╪═════════╡
│ A0A009E921 ┆ A0A009E921 ┆ 1310605 │
│ A0A009F5K6 ┆ A0A009E921 ┆ 1310605 │
│ A0A009E9H3 ┆ A0A009E9H3 ┆ 1310605 │
│ A0A484ZLT0 ┆ A0A009E9H3 ┆ 82979   │
│ A0A009ECR5 ┆ A0A009ECR5 ┆ 1310605 │
│ …          ┆ …          ┆ …       │
│ A0A2H1H4H2 ┆ A0A067MFQ6 ┆ 1276532 │
│ A0A6A5RUW1 ┆ A0A067MFQ6 ┆ 1150837 │
│ A0A6A5UGB0 ┆ A0A067MFQ6 ┆ 147558  │
│ A0A6A6RXS7 ┆ A0A067MFQ6 ┆ 1395130 │
│ A0A067MFS2 ┆ A0A067MFS2 ┆ 930990  │
└────────────┴────────────┴─────────┘

In [12]:
df_sap_go

shape: (186_095, 5)
┌────────────┬─────────────────────────────────┬────────────┬─────────┬──────────┐
│ sapID      ┆ sapGO                           ┆ repID      ┆ cluFlag ┆ LCAtaxID │
│ ---        ┆ ---                             ┆ ---        ┆ ---     ┆ ---      │
│ str        ┆ str                             ┆ str        ┆ i64     ┆ str      │
╞════════════╪═════════════════════════════════╪════════════╪═════════╪══════════╡
│ J3KRM4     ┆ GO:0016021;GO:0015267;          ┆ A0A013RMH7 ┆ 3       ┆ 131567   │
│ C9J222     ┆ GO:0043229;GO:0003677;GO:00038… ┆ A0A014PHZ8 ┆ 3       ┆ 2759     │
│ C9JF34     ┆ GO:0043229;GO:0003677;GO:00038… ┆ A0A014PHZ8 ┆ 1       ┆ 2759     │
│ F8WB78     ┆ GO:0043229;GO:0003677;GO:00038… ┆ A0A014PHZ8 ┆ 1       ┆ 2759     │
│ F8WEJ1     ┆ GO:0043229;GO:0003677;GO:00038… ┆ A0A014PHZ8 ┆ 1       ┆ 2759     │
│ …          ┆ …                               ┆ …          ┆ …       ┆ …        │
│ A8K297     ┆ GO:0043229;GO:0005524;GO:00468… ┆ X8J1M2     ┆ 1       ┆ 131567   │
│ E9PC47     ┆ GO:0005829;GO:0016607;GO:00055… ┆ X8J1M2     ┆ 1       ┆ 131567   │
│ P53667     ┆ GO:0005737;GO:0005856;GO:00058… ┆ X8J1M2     ┆ 1       ┆ 131567   │
│ A0A2R8YFK8 ┆ GO:0005737;GO:0030705;GO:00160… ┆ Z4YKY0     ┆ 1       ┆ N/A      │
│ A0A2R8YFV1 ┆ GO:0005737;GO:0030705;GO:00160… ┆ Z4YKY0     ┆ 1       ┆ N/A      │
└────────────┴─────────────────────────────────┴────────────┴─────────┴──────────┘