### Explore A Jain's IEI pipeline
### Julian Moran
### 2026-02-09

In [65]:
import os

from dotenv import load_dotenv
from pathlib import Path

import polars as pl
import numpy as np

# Env
pl.Config.set_tbl_rows(10)
load_dotenv("../.env")
INSTALL_PATH = os.environ["INSTALL_PATH"]

# Pipeline IO

Codebase at `` 

1. DefenseFinder RefSeq IDs --> UniProt IDs
    - DefenseFinder: db of all bacterial genes implicated in antiphage systems
    - RefSeq bacterial accession IDs:   denote a bacterial immunoprotein; often begin with `WP`
    - UniProt access IDs:               denote a protein; e.g. `A0A7P0TAE1_HUMAN`

<br>

2. UniProt IDs --> Foldseek cluster ID

<br>

3. Foldseek cluster ID --> related human cluster ID

<br>

4. UniProt IDs --> UniprotKB annotations

<br>


# Questions

1. How does `01_RefSeq2Uniprot_mapping/` fit into the pipeline?
    - Are data in `01_RefSeq2Uniprot_mapping/` the output from pipeline step 2.?
    - Are data in `griid_gene_list/`, `gasdermin/`, `vipirin/`, `zorya/` prioritized subsets from `01_RefSeq2Uniprot_mapping/`?
    - If so, why are the subsets substantially larger than the original data?
    - `WP_063110969.1`, from `gasdermin/2025-07-26_gasdermin_annotated.xlsx`, is not in `data_local/01_RefSeq2Uniprot_mapping/2025-06-24_RefSeq2Uniprot_mapping.xlsx`

<br>

2. What is the relationship between each UniProt accession number and its corresponding cluster?
    - i.e. in datasets like `zorya/2025-07-27_zorya_annotated.tsv`?


<br>

3. Why do we see identical rows in the annotated data?
    - best to denote rows as `RefSeq_ID`,`UniProt_ID`,`FoldSeq_cluster`,`Similar_human_gene` 
    - e.g. in `zorya/2025-07-27_zorya_annotated.tsv`, see multiple rows for `WP_063192462.1`,`A0A142CZW3`,`A0A142CZW3`,`B4DLD8`


<br>

# Filtering criteria

1. Select for human proteins in same cluster as bacterial
    - `defense_system_cluster_id == cluster_id`
    - in annotated data, `defense_system_cluster_id` denotes the FoldSeek cluster that contains the query DefenseFinder protein
    - in annotated data, `cluster_id` denotes the most-similar target FoldSeek cluster containing a human protein 


2. Select for human proteins closest in AA length to each bacterial protein


2. Select for closest human genes that are in EAGLE definitive



<br>

# Missing read permissions

1. `00_run_pipeline.sh`
2. `scripts/05_generate_slurm_file.py`
3. `scripts/06_find_human_foldseek_matches.py`
4. `scripts/07_run_foldseek.py`
5. `scripts/07_submit_run_foldseek.sh`
6. `scripts/08_add_annotations-optimized-new_metrics.py`

In [4]:
# ============================================================
#                             Args
# ============================================================

args = {
    "data_file_foldseek_uniprot": f"{INSTALL_PATH}/data_local/02_FoldSeek_Results_w_Uniprot_matches/2025-07-26_batch_0_annotated.tsv",
    "data_file_GRIID": f"{INSTALL_PATH}/data_local/griid_gene_list/2025-07-30_data_filtered_for_griid_genes.tsv",
    "data_file_gasdermin": f"{INSTALL_PATH}/data_sync/gasdermin/2025-07-26_gasdermin_annotated.tsv",
    "data_file_vipirin": f"{INSTALL_PATH}/data_sync/viperin/2025-07-26_viperin_annotated.tsv",
    "data_file_zorya": f"{INSTALL_PATH}/data_local/zorya/2025-07-27_zorya_annotated.tsv"
}

In [90]:
# ============================================================
#                             In
# ============================================================

data_ann = {}
for key, path in args.items():
    if "data_file_" in key and not "foldseek" in key:
        data_key = key.replace("data_file_", "")
        data_ann[data_key] = pl.read_csv(
            args[key],
            has_header=True,
            separator="\t",
            schema_overrides={
                "duplicate_count": pl.Int64,
                "rank": pl.Int64,
                "evalue": pl.Float64,
                "cluFlag": pl.Int64,
                "fident": pl.Float64,
                "alnlen": pl.Int64,
                "mismatch": pl.Int64,
                "gapopen": pl.Float64,
                "qstart": pl.Int64,
                "qend": pl.Int64,
                "tstart": pl.Int64,
                "tend": pl.Int64,
                "evalue_foldseek": pl.Float64,
                "bits": pl.Int64,
                "Query_length": pl.Int64,
                "Human_prot_total_length": pl.Int64,
                "Human_domain_percentage": pl.Float64,
                "Query_percentage": pl.Float64,
                "Query_overlap_w_Human_protein": pl.Float64,
                "Target_length": pl.Int64,
                "Bacterial_prot_total_length": pl.Int64,
                "Bacterial_domain_percentage": pl.Float64,
                "Target_percentage": pl.Float64,
                "Target_overlap_w_Bacterial_protein": pl.Float64,
                "Bacterial_Human_Len_Ratio": pl.Float64,
                "Query_Target_Overlap_Length": pl.Float64,
                "Overlap_ratio": pl.Float64,
            },
            infer_schema_length=10000
        )

df_foldseek_uniprot = pl.read_csv(
    args["data_file_foldseek_uniprot"],
    separator="\t",
    has_header=True
)

df_foldseek_uniprot[0:19]

shape: (19, 70)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ accession_ ┆ type  ┆ subtype    ┆ species    ┆ … ┆ Bacterial ┆ Bacterial ┆ Query_Tar ┆ Overlap_r │
│ in_sys     ┆ ---   ┆ ---        ┆ ---        ┆   ┆ _domain_e ┆ _Human_Le ┆ get_Overl ┆ atio      │
│ ---        ┆ str   ┆ str        ┆ str        ┆   ┆ vidence   ┆ n_Ratio   ┆ ap_Length ┆ ---       │
│ str        ┆       ┆            ┆            ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64       │
│            ┆       ┆            ┆            ┆   ┆ str       ┆ f64       ┆ i64       ┆           │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ WP_0012232 ┆ MazEF ┆ MazEF      ┆ Shigella   ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 08.1       ┆       ┆            ┆ dysenteria ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ e,Escheric ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ h…         ┆   ┆           ┆           ┆           ┆           │
│ WP_0034142 ┆ Cas   ┆ CAS_Class1 ┆ Mycobacter ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 96.1       ┆       ┆ -Subtype-I ┆ ium tuberc ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆ II-A       ┆ ulosis,Myc ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ …          ┆   ┆           ┆           ┆           ┆           │
│ WP_0028851 ┆ AbiE  ┆ AbiE       ┆ Klebsiella ┆ … ┆ null      ┆ 0.583174  ┆ 238       ┆ 0.780328  │
│ 55.1       ┆       ┆            ┆ sp. P1927, ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ Klebsiell… ┆   ┆           ┆           ┆           ┆           │
│ WP_0028851 ┆ AbiE  ┆ AbiE       ┆ Klebsiella ┆ … ┆ null      ┆ 0.780051  ┆ 293       ┆ 0.960656  │
│ 55.1       ┆       ┆            ┆ sp. P1927, ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ Klebsiell… ┆   ┆           ┆           ┆           ┆           │
│ WP_0028851 ┆ AbiE  ┆ AbiE       ┆ Klebsiella ┆ … ┆ null      ┆ 0.697941  ┆ 293       ┆ 0.960656  │
│ 55.1       ┆       ┆            ┆ sp. P1927, ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ Klebsiell… ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …     ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ WP_0000644 ┆ Cas   ┆ CAS_Class1 ┆ Shigella   ┆ … ┆ null      ┆ 1.20598   ┆ 195       ┆ 0.647841  │
│ 50.1       ┆       ┆ -Subtype-I ┆ flexneri,E ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆ -E         ┆ scherichia ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ …          ┆   ┆           ┆           ┆           ┆           │
│ WP_0000644 ┆ Cas   ┆ CAS_Class1 ┆ Shigella   ┆ … ┆ null      ┆ null      ┆ 216       ┆ 0.595041  │
│ 50.1       ┆       ┆ -Subtype-I ┆ flexneri,E ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆ -E         ┆ scherichia ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ …          ┆   ┆           ┆           ┆           ┆           │
│ WP_0000644 ┆ Cas   ┆ CAS_Class1 ┆ Shigella   ┆ … ┆ null      ┆ 0.570755  ┆ 216       ┆ 0.595041  │
│ 50.1       ┆       ┆ -Subtype-I ┆ flexneri,E ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆ -E         ┆ scherichia ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ …          ┆   ┆           ┆           ┆           ┆           │
│ WP_0000644 ┆ Cas   ┆ CAS_Class1 ┆ Shigella   ┆ … ┆ null      ┆ 0.594108  ┆ 194       ┆ 0.534435  │
│ 50.1       ┆       ┆ -Subtype-I ┆ flexneri,E ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆ -E         ┆ scherichia ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ …          ┆   ┆           ┆           ┆           ┆           │
│ WP_0000644 ┆ Cas   ┆ CAS_Class1 ┆ Shigella   ┆ … ┆ null      ┆ 0.5671875 ┆ 207       ┆ 0.570248  │
│ 50.1       ┆       ┆ -Subtype-I ┆ flexneri,E ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆ -E         ┆ scherichia ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ …          ┆   ┆           ┆           ┆           ┆           │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [91]:
# ============================================================
#                Clean, stack annotated data
# ============================================================

def remove_dup_rows(df: pl.DataFrame) -> int:
    df_dup_counted = (
        df.group_by(df.columns)
        .len()
    )
    dups_count = (
        df_dup_counted.filter(pl.col("len") > 1)
        .select((pl.col("len") - 1).sum())
        .item()
    )
    print(f"Number of dup rows: {dups_count:,}")
    return df_dup_counted.drop("len"), dups_count


data_ann_cl = {}
for data_key, df in data_ann.items():
    data_ann_cl[data_key], dups_count = remove_dup_rows(df)

    # Write out cleaned version
    if dups_count > 0:
        key = [k for k in args if data_key in k][0]
        out_path = Path(args[key].replace(".tsv", "_cleaned.tsv"))
        data_ann_cl[data_key].write_csv(
            out_path,
            separator="\t",
            include_header=True
        )

df_ann_cl = pl.concat(
    [df for df in data_ann_cl.values()],
    how="diagonal"
)

print(f"Number of rows after cleaning, v-stacking: {len(df_ann_cl):,}")
df_ann_cl

Number of dup rows: 0
Number of dup rows: 0
Number of dup rows: 266
Number of dup rows: 40,578
Number of rows after cleaning, v-stacking: 321,575

shape: (321_575, 71)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ accession ┆ type      ┆ subtype   ┆ species   ┆ … ┆ Bacterial ┆ Query_Tar ┆ Overlap_r ┆ GRIID_ge │
│ _in_sys   ┆ ---       ┆ ---       ┆ ---       ┆   ┆ _Human_Le ┆ get_Overl ┆ atio      ┆ ne       │
│ ---       ┆ str       ┆ str       ┆ str       ┆   ┆ n_Ratio   ┆ ap_Length ┆ ---       ┆ ---      │
│ str       ┆           ┆           ┆           ┆   ┆ ---       ┆ ---       ┆ f64       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ WP_001077 ┆ PsyrTA    ┆ PsyrTA    ┆ Escherich ┆ … ┆ 1.494737  ┆ 361.0     ┆ 0.76      ┆ Yes      │
│ 932.1     ┆           ┆           ┆ ia coli   ┆   ┆           ┆           ┆           ┆          │
│ WP_003159 ┆ Rst_Helic ┆ Rst_Helic ┆ Pseudomon ┆ … ┆ 3.025532  ┆ 174.0     ┆ 0.740426  ┆ No       │
│ 898.1     ┆ aseDUF229 ┆ aseDUF229 ┆ as aerugi ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0         ┆ 0         ┆ nosa      ┆   ┆           ┆           ┆           ┆          │
│ WP_014757 ┆ Cas       ┆ CAS_Class ┆ Thermoana ┆ … ┆ 2.290323  ┆ 307.0     ┆ 0.900293  ┆ No       │
│ 523.1     ┆           ┆ 1-Subtype ┆ erobacter ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ -I-B      ┆ ium       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ aotearoe… ┆   ┆           ┆           ┆           ┆          │
│ WP_003105 ┆ CBASS     ┆ CBASS_III ┆ Pseudomon ┆ … ┆ 0.363636  ┆ 276.0     ┆ 0.907895  ┆ No       │
│ 629.1     ┆           ┆           ┆ as aerugi ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ nosa,Achr ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ omo…      ┆   ┆           ┆           ┆           ┆          │
│ WP_004883 ┆ Gabija    ┆ Gabija    ┆ Azospira  ┆ … ┆ 0.842475  ┆ 356.0     ┆ 0.594324  ┆ No       │
│ 039.1     ┆           ┆           ┆ sp. I09,E ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ nterobact ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ er …      ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ WP_060676 ┆ Zorya     ┆ Zorya_Typ ┆ Fusobacte ┆ … ┆ 1.066335  ┆ 220.0     ┆ 0.364842  ┆ null     │
│ 489.1     ┆           ┆ eII       ┆ rium      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ animalis  ┆   ┆           ┆           ┆           ┆          │
│ WP_013032 ┆ Zorya     ┆ Zorya_Typ ┆ Nitrosoco ┆ … ┆ 1.004975  ┆ 208.0     ┆ 0.344942  ┆ null     │
│ 087.1     ┆           ┆ eII       ┆ ccus halo ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ philus    ┆   ┆           ┆           ┆           ┆          │
│ WP_096365 ┆ Zorya     ┆ Zorya_Typ ┆ Thiohalob ┆ … ┆ 1.27973   ┆ 605.0     ┆ 0.817568  ┆ null     │
│ 920.1     ┆           ┆ eI        ┆ acter thi ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ocyanatic ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ us        ┆   ┆           ┆           ┆           ┆          │
│ WP_128178 ┆ Zorya     ┆ Zorya_Typ ┆ [Pantoea] ┆ … ┆ 1.486448  ┆ 556.0     ┆ 0.793153  ┆ null     │
│ 529.1     ┆           ┆ eI        ┆ beijingen ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ sis       ┆   ┆           ┆           ┆           ┆          │
│ WP_062536 ┆ Zorya     ┆ Zorya_Typ ┆ Psychroba ┆ … ┆ 0.550154  ┆ 565.0     ┆ 0.525581  ┆ null     │
│ 155.1     ┆           ┆ eI        ┆ cter urat ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ivorans   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [94]:
# ============================================================
#                     Filter annotated data
# ============================================================

def filter_data_ann(df: pl.DataFrame) -> pl.DataFrame:

    df = df.filter(
        (pl.col("defense_system_cluster_id") == pl.col("cluster_id")) &
        (pl.col("Organism") == "Homo sapiens (Human)")
    )
    print(f"N rows after filtering: {len(df)}")

    return df

filter_data_ann(df_ann_cl)

N rows after filtering: 904

shape: (904, 71)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ accession_ ┆ type    ┆ subtype   ┆ species   ┆ … ┆ Bacterial ┆ Query_Tar ┆ Overlap_r ┆ GRIID_gen │
│ in_sys     ┆ ---     ┆ ---       ┆ ---       ┆   ┆ _Human_Le ┆ get_Overl ┆ atio      ┆ e         │
│ ---        ┆ str     ┆ str       ┆ str       ┆   ┆ n_Ratio   ┆ ap_Length ┆ ---       ┆ ---       │
│ str        ┆         ┆           ┆           ┆   ┆ ---       ┆ ---       ┆ f64       ┆ str       │
│            ┆         ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆           │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ WP_1281055 ┆ Zorya   ┆ Zorya_Typ ┆ Acetobact ┆ … ┆ 1.001949  ┆ 653.0     ┆ 0.636452  ┆ No        │
│ 40.1       ┆         ┆ eI        ┆ er        ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆           ┆ oryzoeni  ┆   ┆           ┆           ┆           ┆           │
│ WP_1428170 ┆ Zorya   ┆ Zorya_Typ ┆ Rhodofera ┆ … ┆ 1.240363  ┆ 166.0     ┆ 0.188209  ┆ No        │
│ 48.1       ┆         ┆ eI        ┆ x         ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆           ┆ sediminis ┆   ┆           ┆           ┆           ┆           │
│ WP_0139546 ┆ RM      ┆ RM_Type_I ┆ Mycoplasm ┆ … ┆ 0.828645  ┆ 317.0     ┆ 0.978395  ┆ No        │
│ 35.1       ┆         ┆ I         ┆ opsis     ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆           ┆ bovis     ┆   ┆           ┆           ┆           ┆           │
│ WP_1576722 ┆ Zorya   ┆ Zorya_Typ ┆ Chelatoco ┆ … ┆ 0.983235  ┆ 651.0     ┆ 0.652959  ┆ No        │
│ 85.1       ┆         ┆ eI        ┆ ccus sp.  ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆           ┆ CO-6      ┆   ┆           ┆           ┆           ┆           │
│ WP_2189200 ┆ Viperin ┆ Viperin   ┆ Chondromy ┆ … ┆ 1.275591  ┆ 228.0     ┆ 0.897638  ┆ No        │
│ 67.1       ┆         ┆           ┆ ces       ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆           ┆ crocatus  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …       ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ WP_0113974 ┆ Zorya   ┆ Zorya_Typ ┆ Hahella   ┆ … ┆ 0.977583  ┆ 527.0     ┆ 0.525424  ┆ null      │
│ 35.1       ┆         ┆ eI        ┆ chejuensi ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆           ┆ s         ┆   ┆           ┆           ┆           ┆           │
│ WP_0212637 ┆ Zorya   ┆ Zorya_Typ ┆ Pseudomon ┆ … ┆ 0.999014  ┆ 624.0     ┆ 0.615992  ┆ null      │
│ 40.1       ┆         ┆ eI        ┆ as aerugi ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆           ┆ nosa      ┆   ┆           ┆           ┆           ┆           │
│ WP_1747575 ┆ Zorya   ┆ Zorya_Typ ┆ Azospiril ┆ … ┆ 0.946394  ┆ 494.0     ┆ 0.508754  ┆ null      │
│ 29.1       ┆         ┆ eI        ┆ lum       ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆           ┆ oryzae    ┆   ┆           ┆           ┆           ┆           │
│ WP_1511371 ┆ Zorya   ┆ Zorya_Typ ┆ Pseudomon ┆ … ┆ 0.986355  ┆ 555.0     ┆ 0.548419  ┆ null      │
│ 18.1       ┆         ┆ eI        ┆ as lalkua ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆           ┆ nensis    ┆   ┆           ┆           ┆           ┆           │
│ WP_1382246 ┆ Zorya   ┆ Zorya_Typ ┆ Paenibaci ┆ … ┆ 0.892788  ┆ 450.0     ┆ 0.491266  ┆ null      │
│ 88.1       ┆         ┆ eI        ┆ llus      ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆           ┆ algicola  ┆   ┆           ┆           ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘