In [2]:
import logging
import os

from dotenv import load_dotenv
from matplotlib.ticker import FuncFormatter
from matplotlib import pyplot as plt
from pathlib import Path
from typing import Tuple

import numpy as np
import polars as pl

# Env
pl.Config.set_tbl_rows(10)
load_dotenv("../.env")
INSTALL_PATH = os.environ["INSTALL_PATH"]
AF_URL = os.environ["API_URL_ALPHAFOLD_STRUCTPRED"]

# Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s:%(name)s:%(message)s"
)
logger = logging.getLogger(__name__)

### Steps

1. Apply preliminary filtering criteria
2. Apply PyMOL alignment
3. Lookup how SMARCA4, KPNA2 fare

In [10]:
# ────────────────────────────────────────────────────────────
#      Args
# ────────────────────────────────────────────────────────────

THRESHOLD_LENGTH_ERROR = 0.05,
THRESHOLD_OVERLAP_RATIO = 0.9
PYMOL_ALIGN_METHOD = "super"

OUT_DIR_AF = Path(f"{INSTALL_PATH}/data_local/alphafold_structures")
OUT_DIR_PM = Path(f"{INSTALL_PATH}/data_local/pymol_alignments/{PYMOL_ALIGN_METHOD}")

data_file = f"{INSTALL_PATH}/data_local/zorya/2025-07-27_zorya_annotated.tsv"

In [12]:
# ────────────────────────────────────────────────────────────
#      In
# ────────────────────────────────────────────────────────────

OUT_DIR_AF.mkdir(exist_ok=True, parents=True)
OUT_DIR_PM.mkdir(exist_ok=True, parents=True)

df = pl.read_csv(
            data_file,
            has_header=True,
            separator="\t",
            schema_overrides={
                "duplicate_count": pl.Int64,
                "rank": pl.Int64,
                "evalue": pl.Float64,
                "cluFlag": pl.Int64,
                "fident": pl.Float64,
                "alnlen": pl.Int64,
                "mismatch": pl.Int64,
                "gapopen": pl.Float64,
                "qstart": pl.Int64,
                "qend": pl.Int64,
                "tstart": pl.Int64,
                "tend": pl.Int64,
                "evalue_foldseek": pl.Float64,
                "bits": pl.Int64,
                "Query_length": pl.Int64,
                "Human_prot_total_length": pl.Int64,
                "Human_domain_percentage": pl.Float64,
                "Query_percentage": pl.Float64,
                "Query_overlap_w_Human_protein": pl.Float64,
                "Target_length": pl.Int64,
                "Bacterial_prot_total_length": pl.Int64,
                "Bacterial_domain_percentage": pl.Float64,
                "Target_percentage": pl.Float64,
                "Target_overlap_w_Bacterial_protein": pl.Float64,
                "Bacterial_Human_Len_Ratio": pl.Float64,
                "Query_Target_Overlap_Length": pl.Float64,
                "Overlap_ratio": pl.Float64,
            },
            infer_schema_length=10000
        )

df

shape: (99_469, 70)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ accession_ ┆ type  ┆ subtype    ┆ species    ┆ … ┆ Bacterial ┆ Bacterial ┆ Query_Tar ┆ Overlap_r │
│ in_sys     ┆ ---   ┆ ---        ┆ ---        ┆   ┆ _domain_e ┆ _Human_Le ┆ get_Overl ┆ atio      │
│ ---        ┆ str   ┆ str        ┆ str        ┆   ┆ vidence   ┆ n_Ratio   ┆ ap_Length ┆ ---       │
│ str        ┆       ┆            ┆            ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64       │
│            ┆       ┆            ┆            ┆   ┆ str       ┆ f64       ┆ f64       ┆           │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ WP_0631924 ┆ Zorya ┆ Zorya_Type ┆ Geobacillu ┆ … ┆ ['ECO:000 ┆ 0.861933  ┆ 658.0     ┆ 0.75286   │
│ 62.1       ┆       ┆ I          ┆ s sp. JS12 ┆   ┆ 0259|PROS ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ ITE:PS511 ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ 94'…      ┆           ┆           ┆           │
│ WP_0631924 ┆ Zorya ┆ Zorya_Type ┆ Geobacillu ┆ … ┆ ['ECO:000 ┆ 0.861933  ┆ 658.0     ┆ 0.75286   │
│ 62.1       ┆       ┆ I          ┆ s sp. JS12 ┆   ┆ 0259|PROS ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ ITE:PS511 ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ 94'…      ┆           ┆           ┆           │
│ WP_0631924 ┆ Zorya ┆ Zorya_Type ┆ Geobacillu ┆ … ┆ ['ECO:000 ┆ 0.861933  ┆ 658.0     ┆ 0.75286   │
│ 62.1       ┆       ┆ I          ┆ s sp. JS12 ┆   ┆ 0259|PROS ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ ITE:PS511 ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ 94'…      ┆           ┆           ┆           │
│ WP_0631924 ┆ Zorya ┆ Zorya_Type ┆ Geobacillu ┆ … ┆ ['ECO:000 ┆ 0.861933  ┆ 658.0     ┆ 0.75286   │
│ 62.1       ┆       ┆ I          ┆ s sp. JS12 ┆   ┆ 0259|PROS ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ ITE:PS511 ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ 94'…      ┆           ┆           ┆           │
│ WP_0631924 ┆ Zorya ┆ Zorya_Type ┆ Geobacillu ┆ … ┆ ['ECO:000 ┆ 0.861933  ┆ 658.0     ┆ 0.75286   │
│ 62.1       ┆       ┆ I          ┆ s sp. JS12 ┆   ┆ 0259|PROS ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ ITE:PS511 ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ 94'…      ┆           ┆           ┆           │
│ …          ┆ …     ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ WP_0144280 ┆ Zorya ┆ Zorya_Type ┆ Rubrivivax ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 04.1       ┆       ┆ I          ┆ gelatinosu ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ s          ┆   ┆           ┆           ┆           ┆           │
│ WP_0007772 ┆ Zorya ┆ Zorya_Type ┆ Escherichi ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 76.1       ┆       ┆ II         ┆ a coli,Shi ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ gella      ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ flex…      ┆   ┆           ┆           ┆           ┆           │
│ WP_0115132 ┆ Zorya ┆ Zorya_Type ┆ Psychrobac ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 96.1       ┆       ┆ I          ┆ ter cryoha ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ lolentis   ┆   ┆           ┆           ┆           ┆           │
│ WP_0012525 ┆ Zorya ┆ Zorya_Type ┆ Vibrio     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 11.1       ┆       ┆ I          ┆ cholerae   ┆   ┆           ┆           ┆           ┆           │
│ WP_0209595 ┆ Zorya ┆ Zorya_Type ┆ Geobacillu ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 43.1       ┆       ┆ I          ┆ s          ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ genomosp.  ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ 3          ┆   ┆           ┆           ┆           ┆           │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [9]:
# ────────────────────────────────────────────────────────────
#      Clean
# ────────────────────────────────────────────────────────────

def remove_dup_rows(df: pl.DataFrame) -> tuple[pl.DataFrame, int]:
    df_dup_counted = (
        df.group_by(df.columns)
        .len()
    )
    dups_count = (
        df_dup_counted.filter(pl.col("len") > 1)
        .select((pl.col("len") - 1).sum())
        .item()
    )
    return df_dup_counted.drop("len"), dups_count

df_cl, _ = remove_dup_rows(df)
logger.info(f"N rows removed: {_}")

df_cl

INFO:__main__:N rows removed: 40578

shape: (58_891, 70)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ accession_ ┆ type  ┆ subtype    ┆ species    ┆ … ┆ Bacterial ┆ Bacterial ┆ Query_Tar ┆ Overlap_r │
│ in_sys     ┆ ---   ┆ ---        ┆ ---        ┆   ┆ _domain_e ┆ _Human_Le ┆ get_Overl ┆ atio      │
│ ---        ┆ str   ┆ str        ┆ str        ┆   ┆ vidence   ┆ n_Ratio   ┆ ap_Length ┆ ---       │
│ str        ┆       ┆            ┆            ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64       │
│            ┆       ┆            ┆            ┆   ┆ str       ┆ f64       ┆ f64       ┆           │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ WP_1511845 ┆ Zorya ┆ Zorya_Type ┆ Pseudomona ┆ … ┆ ['ECO:000 ┆ 1.20329   ┆ 444.0     ┆ 0.521739  │
│ 85.1       ┆       ┆ I          ┆ s sp.      ┆   ┆ 0259|PROS ┆           ┆           ┆           │
│            ┆       ┆            ┆ C27(2019)  ┆   ┆ ITE:PS511 ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ 92'…      ┆           ┆           ┆           │
│ WP_1281055 ┆ Zorya ┆ Zorya_Type ┆ Acetobacte ┆ … ┆ ['ECO:000 ┆ 2.80109   ┆ 344.0     ┆ 0.9373297 │
│ 40.1       ┆       ┆ I          ┆ r oryzoeni ┆   ┆ 0259|PROS ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ ITE:PS511 ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ 92'…      ┆           ┆           ┆           │
│ WP_1382246 ┆ Zorya ┆ Zorya_Type ┆ Paenibacil ┆ … ┆ ['ECO:000 ┆ 0.8       ┆ 469.0     ┆ 0.512009  │
│ 88.1       ┆       ┆ I          ┆ lus        ┆   ┆ 0259|PROS ┆           ┆           ┆           │
│            ┆       ┆            ┆ algicola   ┆   ┆ ITE:PS511 ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ 92'…      ┆           ┆           ┆           │
│ WP_0130320 ┆ Zorya ┆ Zorya_Type ┆ Nitrosococ ┆ … ┆ null      ┆ 1.004975  ┆ 208.0     ┆ 0.344942  │
│ 87.1       ┆       ┆ II         ┆ cus        ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ halophilus ┆   ┆           ┆           ┆           ┆           │
│ WP_0890679 ┆ Zorya ┆ Zorya_Type ┆ Shewanella ┆ … ┆ null      ┆ 0.966833  ┆ 271.0     ┆ 0.464837  │
│ 50.1       ┆       ┆ II         ┆ bicestrii  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …     ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ WP_1747575 ┆ Zorya ┆ Zorya_Type ┆ Azospirill ┆ … ┆ ['ECO:000 ┆ 1.44494   ┆ 578.0     ┆ 0.860119  │
│ 29.1       ┆       ┆ I          ┆ um oryzae  ┆   ┆ 0259|PROS ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ ITE:PS511 ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ 94'…      ┆           ┆           ┆           │
│ WP_0004241 ┆ Zorya ┆ Zorya_Type ┆ Vibrio     ┆ … ┆ ['ECO:000 ┆ 2.418947  ┆ 375.0     ┆ 0.789474  │
│ 58.1       ┆       ┆ I          ┆ cholerae   ┆   ┆ 0259|PROS ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ ITE:PS511 ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ 92'…      ┆           ┆           ┆           │
│ WP_1491292 ┆ Zorya ┆ Zorya_Type ┆ Bosea sp.  ┆ … ┆ ['ECO:000 ┆ 1.627036  ┆ 360.0     ┆ 0.586319  │
│ 18.1       ┆       ┆ I          ┆ F3-2       ┆   ┆ 0259|PROS ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ ITE:PS511 ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ 92'…      ┆           ┆           ┆           │
│ WP_1525015 ┆ Zorya ┆ Zorya_Type ┆ Labrenzia  ┆ … ┆ ['ECO:000 ┆ 3.300283  ┆ 340.0     ┆ 0.963173  │
│ 41.1       ┆       ┆ I          ┆ sp. THAF82 ┆   ┆ 0259|PROS ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ ITE:PS511 ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ 92'…      ┆           ┆           ┆           │
│ WP_0113974 ┆ Zorya ┆ Zorya_Type ┆ Hahella    ┆ … ┆ ['ECO:000 ┆ 1.118172  ┆ 474.0     ┆ 0.528428  │
│ 35.1       ┆       ┆ I          ┆ chejuensis ┆   ┆ 0259|PROS ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ ITE:PS511 ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ 92'…      ┆           ┆           ┆           │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘