### Explore A Jain's IEI pipeline
### Julian Moran
### 2026-02-09

In [34]:
import os

from dotenv import load_dotenv

import polars as pl
import numpy as np

# Env
pl.Config.set_tbl_rows(10)
load_dotenv("../.env")
INSTALL_PATH = os.environ["INSTALL_PATH"]

# Pipeline IO

1. DefenseFinder RefSeq IDs --> UniProt IDs
    - DefenseFinder: db of all bacterial genes implicated in antiphage systems
    - RefSeq bacterial accession IDs:   denote a bacterial immunoprotein; often begin with `WP`
    - UniProt access IDs:               denote a protein; e.g. `A0A7P0TAE1_HUMAN`

<br>

2. UniProt IDs --> Foldseek cluster ID

<br>

3. Foldseek cluster ID --> related human cluster ID

<br>

4. UniProt IDs --> UniprotKB annotations

<br>


# Questions

1. How does `01_RefSeq2Uniprot_mapping/` fit into the pipeline?
    - Are data in `01_RefSeq2Uniprot_mapping/` the output from pipeline step 2.?
    - Are data in `griid_gene_list/`, `gasdermin/`, `vipirin/`, `zorya/` prioritized subsets from `01_RefSeq2Uniprot_mapping/`?
    - If so, why are the subsets substantially larger than the original data?
    - `WP_063110969.1`, from `gasdermin/2025-07-26_gasdermin_annotated.xlsx`, is not in `data_local/01_RefSeq2Uniprot_mapping/2025-06-24_RefSeq2Uniprot_mapping.xlsx`

<br>

2. What is the relationship between each UniProt accession number and its corresponding cluster?
    - i.e. in datasets like `zorya/2025-07-27_zorya_annotated.tsv`?


<br>

3. Why do we see identical rows in the annotated data?
    - best to denote rows as `RefSeq_ID`,`UniProt_ID`,`FoldSeq_cluster`,`Similar_human_gene` 
    - e.g. in `zorya/2025-07-27_zorya_annotated.tsv`, see multiple rows for `WP_063192462.1`,`A0A142CZW3`,`A0A142CZW3`,`B4DLD8`


<br>

# Filtering criteria

1. Select for human proteins in same cluster as bacterial
    - `defense_system_cluster_id == cluster_id`
    - in annotated data, `defense_system_cluster_id` denotes the FoldSeek cluster that contains the query DefenseFinder protein
    - in annotated data, `cluster_id` denotes the most-similar target FoldSeek cluster containing a human protein 


2. Select for human proteins closest in AA length to each bacterial protein


2. Select for closest human genes that are in EAGLE definitive



<br>

# Missing read permissions

1. `00_run_pipeline.sh`
2. `scripts/05_generate_slurm_file.py`
3. `scripts/06_find_human_foldseek_matches.py`
4. `scripts/07_run_foldseek.py`
5. `scripts/07_submit_run_foldseek.sh`
6. `scripts/08_add_annotations-optimized-new_metrics.py`

In [4]:
# ============================================================
#                             Args
# ============================================================

args = {
    "data_file_foldseek_uniprot": f"{INSTALL_PATH}/data_local/02_FoldSeek_Results_w_Uniprot_matches/2025-07-26_batch_0_annotated.tsv",
    "data_file_GRIID": f"{INSTALL_PATH}/data_local/griid_gene_list/2025-07-30_data_filtered_for_griid_genes.tsv",
    "data_file_gasdermin": f"{INSTALL_PATH}/data_sync/gasdermin/2025-07-26_gasdermin_annotated.tsv",
    "data_file_vipirin": f"{INSTALL_PATH}/data_sync/viperin/2025-07-26_viperin_annotated.tsv",
    "data_file_zorya": f"{INSTALL_PATH}/data_local/zorya/2025-07-27_zorya_annotated.tsv"
}

In [20]:
# ============================================================
#                             In
# ============================================================

data_ann = {}
for key, path in args.items():
    if "data_file_" in key and not "foldseek" in key:
        data_key = key.replace("file_", "")
        data_ann[data_key] = pl.read_csv(
            args[key],
            has_header=True,
            separator="\t",
            schema_overrides={
                "duplicate_count": pl.Int64,
                "rank": pl.Int64,
                "evalue": pl.Float64,
                "cluFlag": pl.Int64,
                "fident": pl.Float64,
                "alnlen": pl.Int64,
                "mismatch": pl.Int64,
                "gapopen": pl.Float64,
                "qstart": pl.Int64,
                "qend": pl.Int64,
                "tstart": pl.Int64,
                "tend": pl.Int64,
                "evalue_foldseek": pl.Float64,
                "bits": pl.Int64,
                "Query_length": pl.Int64,
                "Human_prot_total_length": pl.Int64,
                "Human_domain_percentage": pl.Float64,
                "Query_percentage": pl.Float64,
                "Query_overlap_w_Human_protein": pl.Float64,
                "Target_length": pl.Int64,
                "Bacterial_prot_total_length": pl.Int64,
                "Bacterial_domain_percentage": pl.Float64,
                "Target_percentage": pl.Float64,
                "Target_overlap_w_Bacterial_protein": pl.Float64,
                "Bacterial_Human_Len_Ratio": pl.Float64,
                "Query_Target_Overlap_Length": pl.Float64,
                "Overlap_ratio": pl.Float64,
            },
            infer_schema_length=10000
        )

df_foldseek_uniprot = pl.read_csv(
    args["data_file_foldseek_uniprot"],
    separator="\t",
    has_header=True
)

df_foldseek_uniprot[0:19]

shape: (19, 70)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ accession_ ┆ type  ┆ subtype    ┆ species    ┆ … ┆ Bacterial ┆ Bacterial ┆ Query_Tar ┆ Overlap_r │
│ in_sys     ┆ ---   ┆ ---        ┆ ---        ┆   ┆ _domain_e ┆ _Human_Le ┆ get_Overl ┆ atio      │
│ ---        ┆ str   ┆ str        ┆ str        ┆   ┆ vidence   ┆ n_Ratio   ┆ ap_Length ┆ ---       │
│ str        ┆       ┆            ┆            ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64       │
│            ┆       ┆            ┆            ┆   ┆ str       ┆ f64       ┆ i64       ┆           │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ WP_0012232 ┆ MazEF ┆ MazEF      ┆ Shigella   ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 08.1       ┆       ┆            ┆ dysenteria ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ e,Escheric ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ h…         ┆   ┆           ┆           ┆           ┆           │
│ WP_0034142 ┆ Cas   ┆ CAS_Class1 ┆ Mycobacter ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 96.1       ┆       ┆ -Subtype-I ┆ ium tuberc ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆ II-A       ┆ ulosis,Myc ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ …          ┆   ┆           ┆           ┆           ┆           │
│ WP_0028851 ┆ AbiE  ┆ AbiE       ┆ Klebsiella ┆ … ┆ null      ┆ 0.583174  ┆ 238       ┆ 0.780328  │
│ 55.1       ┆       ┆            ┆ sp. P1927, ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ Klebsiell… ┆   ┆           ┆           ┆           ┆           │
│ WP_0028851 ┆ AbiE  ┆ AbiE       ┆ Klebsiella ┆ … ┆ null      ┆ 0.780051  ┆ 293       ┆ 0.960656  │
│ 55.1       ┆       ┆            ┆ sp. P1927, ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ Klebsiell… ┆   ┆           ┆           ┆           ┆           │
│ WP_0028851 ┆ AbiE  ┆ AbiE       ┆ Klebsiella ┆ … ┆ null      ┆ 0.697941  ┆ 293       ┆ 0.960656  │
│ 55.1       ┆       ┆            ┆ sp. P1927, ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ Klebsiell… ┆   ┆           ┆           ┆           ┆           │
│ WP_0028851 ┆ AbiE  ┆ AbiE       ┆ Klebsiella ┆ … ┆ null      ┆ 0.784062  ┆ 291       ┆ 0.954098  │
│ 55.1       ┆       ┆            ┆ sp. P1927, ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ Klebsiell… ┆   ┆           ┆           ┆           ┆           │
│ WP_0028851 ┆ AbiE  ┆ AbiE       ┆ Klebsiella ┆ … ┆ null      ┆ 0.690045  ┆ 238       ┆ 0.780328  │
│ 55.1       ┆       ┆            ┆ sp. P1927, ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ Klebsiell… ┆   ┆           ┆           ┆           ┆           │
│ WP_0000631 ┆ Cas   ┆ CAS_Class1 ┆ Escherichi ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 76.1       ┆       ┆ -Subtype-I ┆ a albertii ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆ -E         ┆ ,Shigella  ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ …          ┆   ┆           ┆           ┆           ┆           │
│ WP_0002814 ┆ Cas   ┆ CAS_Class1 ┆ Shigella   ┆ … ┆ null      ┆ 1.496241  ┆ 105       ┆ 0.789474  │
│ 00.1       ┆       ┆ -Subtype-I ┆ flexneri,E ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆ -E         ┆ scherichia ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ …          ┆   ┆           ┆           ┆           ┆           │
│ WP_0041778 ┆ AbiE  ┆ AbiE       ┆ Klebsiella ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 09.1       ┆       ┆            ┆ pneumoniae ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ ,Klebsiel… ┆   ┆           ┆           ┆           ┆           │
│ WP_0007528 ┆ Cas   ┆ CAS_Class1 ┆ Shigella   ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 00.1       ┆       ┆ -Subtype-I ┆ flexneri,E ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆ -E         ┆ scherichia ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ …          ┆   ┆           ┆           ┆           ┆           │
│ WP_0000644 ┆ Cas   ┆ CAS_Class1 ┆ Shigella   ┆ … ┆ null      ┆ 0.968     ┆ 32        ┆ 0.088154  │
│ 50.1       ┆       ┆ -Subtype-I ┆ flexneri,E ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆ -E         ┆ scherichia ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ …          ┆   ┆           ┆           ┆           ┆           │
│ WP_0000644 ┆ Cas   ┆ CAS_Class1 ┆ Shigella   ┆ … ┆ null      ┆ 1.043103  ┆ 26        ┆ 0.074713  │
│ 50.1       ┆       ┆ -Subtype-I ┆ flexneri,E ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆ -E         ┆ scherichia ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ …          ┆   ┆           ┆           ┆           ┆           │
│ WP_0000644 ┆ Cas   ┆ CAS_Class1 ┆ Shigella   ┆ … ┆ null      ┆ 1.20598   ┆ 195       ┆ 0.647841  │
│ 50.1       ┆       ┆ -Subtype-I ┆ flexneri,E ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆ -E         ┆ scherichia ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ …          ┆   ┆           ┆           ┆           ┆           │
│ WP_0000644 ┆ Cas   ┆ CAS_Class1 ┆ Shigella   ┆ … ┆ null      ┆ 1.20598   ┆ 195       ┆ 0.647841  │
│ 50.1       ┆       ┆ -Subtype-I ┆ flexneri,E ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆ -E         ┆ scherichia ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ …          ┆   ┆           ┆           ┆           ┆           │
│ WP_0000644 ┆ Cas   ┆ CAS_Class1 ┆ Shigella   ┆ … ┆ null      ┆ null      ┆ 216       ┆ 0.595041  │
│ 50.1       ┆       ┆ -Subtype-I ┆ flexneri,E ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆ -E         ┆ scherichia ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ …          ┆   ┆           ┆           ┆           ┆           │
│ WP_0000644 ┆ Cas   ┆ CAS_Class1 ┆ Shigella   ┆ … ┆ null      ┆ 0.570755  ┆ 216       ┆ 0.595041  │
│ 50.1       ┆       ┆ -Subtype-I ┆ flexneri,E ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆ -E         ┆ scherichia ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ …          ┆   ┆           ┆           ┆           ┆           │
│ WP_0000644 ┆ Cas   ┆ CAS_Class1 ┆ Shigella   ┆ … ┆ null      ┆ 0.594108  ┆ 194       ┆ 0.534435  │
│ 50.1       ┆       ┆ -Subtype-I ┆ flexneri,E ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆ -E         ┆ scherichia ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ …          ┆   ┆           ┆           ┆           ┆           │
│ WP_0000644 ┆ Cas   ┆ CAS_Class1 ┆ Shigella   ┆ … ┆ null      ┆ 0.5671875 ┆ 207       ┆ 0.570248  │
│ 50.1       ┆       ┆ -Subtype-I ┆ flexneri,E ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆ -E         ┆ scherichia ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ …          ┆   ┆           ┆           ┆           ┆           │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [35]:
data_ann["data_GRIID"]

shape: (258_895, 71)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ accession_ ┆ type   ┆ subtype    ┆ species   ┆ … ┆ Bacterial ┆ Query_Tar ┆ Overlap_r ┆ GRIID_gen │
│ in_sys     ┆ ---    ┆ ---        ┆ ---       ┆   ┆ _Human_Le ┆ get_Overl ┆ atio      ┆ e         │
│ ---        ┆ str    ┆ str        ┆ str       ┆   ┆ n_Ratio   ┆ ap_Length ┆ ---       ┆ ---       │
│ str        ┆        ┆            ┆           ┆   ┆ ---       ┆ ---       ┆ f64       ┆ str       │
│            ┆        ┆            ┆           ┆   ┆ f64       ┆ f64       ┆           ┆           │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ WP_0037345 ┆ RM     ┆ RM_Type_II ┆ Listeria  ┆ … ┆ 1.378495  ┆ 366.0     ┆ 0.787097  ┆ Yes       │
│ 67.1       ┆        ┆            ┆ monocytog ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ enes      ┆   ┆           ┆           ┆           ┆           │
│ WP_2104222 ┆ pAgo   ┆ pAgo_LongA ┆ Dolichosp ┆ … ┆ 0.83856   ┆ 646.0     ┆ 0.894737  ┆ Yes       │
│ 14.1       ┆        ┆            ┆ ermum sp. ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ UHCC      ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ 0315A     ┆   ┆           ┆           ┆           ┆           │
│ WP_2104222 ┆ pAgo   ┆ pAgo_LongA ┆ Dolichosp ┆ … ┆ 0.83856   ┆ 646.0     ┆ 0.894737  ┆ Yes       │
│ 14.1       ┆        ┆            ┆ ermum sp. ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ UHCC      ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ 0315A     ┆   ┆           ┆           ┆           ┆           │
│ WP_0169470 ┆ Cas    ┆ CAS_Class1 ┆ Klebsiell ┆ … ┆ 0.867872  ┆ 569.0     ┆ 0.911859  ┆ Yes       │
│ 78.1       ┆        ┆ -Subtype-I ┆ a pneumon ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆ V-A        ┆ iae,Klebs ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ iel…      ┆   ┆           ┆           ┆           ┆           │
│ WP_0169470 ┆ Cas    ┆ CAS_Class1 ┆ Klebsiell ┆ … ┆ 0.883853  ┆ 591.0     ┆ 0.947115  ┆ Yes       │
│ 78.1       ┆        ┆ -Subtype-I ┆ a pneumon ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆ V-A        ┆ iae,Klebs ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ iel…      ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …      ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ WP_0009808 ┆ Shango ┆ Shango     ┆ Shigella  ┆ … ┆ 8.714286  ┆ 69.0      ┆ 0.821429  ┆ No        │
│ 65.1       ┆        ┆            ┆ dysenteri ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ ae,Escher ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ ich…      ┆   ┆           ┆           ┆           ┆           │
│ WP_0000930 ┆ Shango ┆ Shango     ┆ Escherich ┆ … ┆ 8.611765  ┆ 67.0      ┆ 0.788235  ┆ No        │
│ 92.1       ┆        ┆            ┆ ia coli   ┆   ┆           ┆           ┆           ┆           │
│ WP_0000930 ┆ Shango ┆ Shango     ┆ Escherich ┆ … ┆ 8.714286  ┆ 74.0      ┆ 0.880952  ┆ No        │
│ 92.1       ┆        ┆            ┆ ia coli   ┆   ┆           ┆           ┆           ┆           │
│ WP_0000930 ┆ Shango ┆ Shango     ┆ Escherich ┆ … ┆ 8.611765  ┆ 67.0      ┆ 0.788235  ┆ No        │
│ 92.1       ┆        ┆            ┆ ia coli   ┆   ┆           ┆           ┆           ┆           │
│ WP_0000930 ┆ Shango ┆ Shango     ┆ Escherich ┆ … ┆ 8.714286  ┆ 74.0      ┆ 0.880952  ┆ No        │
│ 92.1       ┆        ┆            ┆ ia coli   ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [37]:
data_ann["data_gasdermin"]

shape: (75, 70)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ accession ┆ type      ┆ subtype   ┆ species   ┆ … ┆ Bacterial ┆ Bacterial ┆ Query_Tar ┆ Overlap_ │
│ _in_sys   ┆ ---       ┆ ---       ┆ ---       ┆   ┆ _domain_e ┆ _Human_Le ┆ get_Overl ┆ ratio    │
│ ---       ┆ str       ┆ str       ┆ str       ┆   ┆ vidence   ┆ n_Ratio   ┆ ap_Length ┆ ---      │
│ str       ┆           ┆           ┆           ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ f64       ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ WP_063110 ┆ GasderMIN ┆ GasderMIN ┆ Methyloru ┆ … ┆ null      ┆ null      ┆ 272.0     ┆ 0.951049 │
│ 969.1     ┆           ┆           ┆ brum      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ populi    ┆   ┆           ┆           ┆           ┆          │
│ WP_063110 ┆ GasderMIN ┆ GasderMIN ┆ Methyloru ┆ … ┆ null      ┆ 0.562992  ┆ 275.0     ┆ 0.961538 │
│ 969.1     ┆           ┆           ┆ brum      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ populi    ┆   ┆           ┆           ┆           ┆          │
│ WP_063110 ┆ GasderMIN ┆ GasderMIN ┆ Methyloru ┆ … ┆ null      ┆ 0.576613  ┆ 219.0     ┆ 0.765734 │
│ 969.1     ┆           ┆           ┆ brum      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ populi    ┆   ┆           ┆           ┆           ┆          │
│ WP_063110 ┆ GasderMIN ┆ GasderMIN ┆ Methyloru ┆ … ┆ null      ┆ 0.576613  ┆ 274.0     ┆ 0.958042 │
│ 969.1     ┆           ┆           ┆ brum      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ populi    ┆   ┆           ┆           ┆           ┆          │
│ WP_063110 ┆ GasderMIN ┆ GasderMIN ┆ Methyloru ┆ … ┆ null      ┆ 0.537594  ┆ 278.0     ┆ 0.972028 │
│ 969.1     ┆           ┆           ┆ brum      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ populi    ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ WP_065010 ┆ GasderMIN ┆ GasderMIN ┆ Mesorhizo ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 818.1     ┆           ┆           ┆ bium sp.  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ AA22      ┆   ┆           ┆           ┆           ┆          │
│ WP_239489 ┆ GasderMIN ┆ GasderMIN ┆ Luteitale ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 731.1     ┆           ┆           ┆ a sp.     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ TBR-22    ┆   ┆           ┆           ┆           ┆          │
│ WP_066768 ┆ GasderMIN ┆ GasderMIN ┆ Sphingobi ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 659.1     ┆           ┆           ┆ um xenoph ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ agum      ┆   ┆           ┆           ┆           ┆          │
│ WP_229974 ┆ GasderMIN ┆ GasderMIN ┆ Flavobact ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 382.1     ┆           ┆           ┆ erium sp. ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ F-70      ┆   ┆           ┆           ┆           ┆          │
│ WP_023174 ┆ GasderMIN ┆ GasderMIN ┆ Gloeobact ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 547.1     ┆           ┆           ┆ er kilaue ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ensis     ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [40]:
data_ann["data_vipirin"]

shape: (3_980, 70)
┌────────────┬─────────┬─────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ accession_ ┆ type    ┆ subtype ┆ species    ┆ … ┆ Bacterial_ ┆ Bacterial ┆ Query_Tar ┆ Overlap_r │
│ in_sys     ┆ ---     ┆ ---     ┆ ---        ┆   ┆ domain_evi ┆ _Human_Le ┆ get_Overl ┆ atio      │
│ ---        ┆ str     ┆ str     ┆ str        ┆   ┆ dence      ┆ n_Ratio   ┆ ap_Length ┆ ---       │
│ str        ┆         ┆         ┆            ┆   ┆ ---        ┆ ---       ┆ ---       ┆ f64       │
│            ┆         ┆         ┆            ┆   ┆ str        ┆ f64       ┆ f64       ┆           │
╞════════════╪═════════╪═════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ WP_2189200 ┆ Viperin ┆ Viperin ┆ Chondromyc ┆ … ┆ ['ECO:0000 ┆ 0.936416  ┆ 213.0     ┆ 0.657407  │
│ 67.1       ┆         ┆         ┆ es         ┆   ┆ 259|PROSIT ┆           ┆           ┆           │
│            ┆         ┆         ┆ crocatus   ┆   ┆ E:PS51918' ┆           ┆           ┆           │
│            ┆         ┆         ┆            ┆   ┆ …          ┆           ┆           ┆           │
│ WP_2189200 ┆ Viperin ┆ Viperin ┆ Chondromyc ┆ … ┆ ['ECO:0000 ┆ 0.595588  ┆ 180.0     ┆ 0.555556  │
│ 67.1       ┆         ┆         ┆ es         ┆   ┆ 259|PROSIT ┆           ┆           ┆           │
│            ┆         ┆         ┆ crocatus   ┆   ┆ E:PS51918' ┆           ┆           ┆           │
│            ┆         ┆         ┆            ┆   ┆ …          ┆           ┆           ┆           │
│ WP_2189200 ┆ Viperin ┆ Viperin ┆ Chondromyc ┆ … ┆ ['ECO:0000 ┆ 0.666667  ┆ 120.0     ┆ 0.37037   │
│ 67.1       ┆         ┆         ┆ es         ┆   ┆ 259|PROSIT ┆           ┆           ┆           │
│            ┆         ┆         ┆ crocatus   ┆   ┆ E:PS51918' ┆           ┆           ┆           │
│            ┆         ┆         ┆            ┆   ┆ …          ┆           ┆           ┆           │
│ WP_2189200 ┆ Viperin ┆ Viperin ┆ Chondromyc ┆ … ┆ ['ECO:0000 ┆ null      ┆ 253.0     ┆ 0.780864  │
│ 67.1       ┆         ┆         ┆ es         ┆   ┆ 259|PROSIT ┆           ┆           ┆           │
│            ┆         ┆         ┆ crocatus   ┆   ┆ E:PS51918' ┆           ┆           ┆           │
│            ┆         ┆         ┆            ┆   ┆ …          ┆           ┆           ┆           │
│ WP_2189200 ┆ Viperin ┆ Viperin ┆ Chondromyc ┆ … ┆ ['ECO:0000 ┆ 0.48503   ┆ 256.0     ┆ 0.790123  │
│ 67.1       ┆         ┆         ┆ es         ┆   ┆ 259|PROSIT ┆           ┆           ┆           │
│            ┆         ┆         ┆ crocatus   ┆   ┆ E:PS51918' ┆           ┆           ┆           │
│            ┆         ┆         ┆            ┆   ┆ …          ┆           ┆           ┆           │
│ …          ┆ …       ┆ …       ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ WP_0480977 ┆ Viperin ┆ Viperin ┆ Candidatus ┆ … ┆ null       ┆ null      ┆ 265.0     ┆ null      │
│ 66.1       ┆         ┆         ┆ Methanomet ┆   ┆            ┆           ┆           ┆           │
│            ┆         ┆         ┆ hylophilu… ┆   ┆            ┆           ┆           ┆           │
│ WP_0480977 ┆ Viperin ┆ Viperin ┆ Candidatus ┆ … ┆ null       ┆ null      ┆ 124.0     ┆ null      │
│ 66.1       ┆         ┆         ┆ Methanomet ┆   ┆            ┆           ┆           ┆           │
│            ┆         ┆         ┆ hylophilu… ┆   ┆            ┆           ┆           ┆           │
│ WP_0480977 ┆ Viperin ┆ Viperin ┆ Candidatus ┆ … ┆ null       ┆ null      ┆ 258.0     ┆ null      │
│ 66.1       ┆         ┆         ┆ Methanomet ┆   ┆            ┆           ┆           ┆           │
│            ┆         ┆         ┆ hylophilu… ┆   ┆            ┆           ┆           ┆           │
│ WP_0480977 ┆ Viperin ┆ Viperin ┆ Candidatus ┆ … ┆ null       ┆ null      ┆ 208.0     ┆ null      │
│ 66.1       ┆         ┆         ┆ Methanomet ┆   ┆            ┆           ┆           ┆           │
│            ┆         ┆         ┆ hylophilu… ┆   ┆            ┆           ┆           ┆           │
│ WP_0480977 ┆ Viperin ┆ Viperin ┆ Candidatus ┆ … ┆ null       ┆ null      ┆ 208.0     ┆ null      │
│ 66.1       ┆         ┆         ┆ Methanomet ┆   ┆            ┆           ┆           ┆           │
│            ┆         ┆         ┆ hylophilu… ┆   ┆            ┆           ┆           ┆           │
└────────────┴─────────┴─────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [41]:
data_ann["data_zorya"]

shape: (99_469, 70)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ accession_ ┆ type  ┆ subtype    ┆ species    ┆ … ┆ Bacterial ┆ Bacterial ┆ Query_Tar ┆ Overlap_r │
│ in_sys     ┆ ---   ┆ ---        ┆ ---        ┆   ┆ _domain_e ┆ _Human_Le ┆ get_Overl ┆ atio      │
│ ---        ┆ str   ┆ str        ┆ str        ┆   ┆ vidence   ┆ n_Ratio   ┆ ap_Length ┆ ---       │
│ str        ┆       ┆            ┆            ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64       │
│            ┆       ┆            ┆            ┆   ┆ str       ┆ f64       ┆ f64       ┆           │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ WP_0631924 ┆ Zorya ┆ Zorya_Type ┆ Geobacillu ┆ … ┆ ['ECO:000 ┆ 0.861933  ┆ 658.0     ┆ 0.75286   │
│ 62.1       ┆       ┆ I          ┆ s sp. JS12 ┆   ┆ 0259|PROS ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ ITE:PS511 ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ 94'…      ┆           ┆           ┆           │
│ WP_0631924 ┆ Zorya ┆ Zorya_Type ┆ Geobacillu ┆ … ┆ ['ECO:000 ┆ 0.861933  ┆ 658.0     ┆ 0.75286   │
│ 62.1       ┆       ┆ I          ┆ s sp. JS12 ┆   ┆ 0259|PROS ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ ITE:PS511 ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ 94'…      ┆           ┆           ┆           │
│ WP_0631924 ┆ Zorya ┆ Zorya_Type ┆ Geobacillu ┆ … ┆ ['ECO:000 ┆ 0.861933  ┆ 658.0     ┆ 0.75286   │
│ 62.1       ┆       ┆ I          ┆ s sp. JS12 ┆   ┆ 0259|PROS ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ ITE:PS511 ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ 94'…      ┆           ┆           ┆           │
│ WP_0631924 ┆ Zorya ┆ Zorya_Type ┆ Geobacillu ┆ … ┆ ['ECO:000 ┆ 0.861933  ┆ 658.0     ┆ 0.75286   │
│ 62.1       ┆       ┆ I          ┆ s sp. JS12 ┆   ┆ 0259|PROS ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ ITE:PS511 ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ 94'…      ┆           ┆           ┆           │
│ WP_0631924 ┆ Zorya ┆ Zorya_Type ┆ Geobacillu ┆ … ┆ ['ECO:000 ┆ 0.861933  ┆ 658.0     ┆ 0.75286   │
│ 62.1       ┆       ┆ I          ┆ s sp. JS12 ┆   ┆ 0259|PROS ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ ITE:PS511 ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ 94'…      ┆           ┆           ┆           │
│ …          ┆ …     ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ WP_0144280 ┆ Zorya ┆ Zorya_Type ┆ Rubrivivax ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 04.1       ┆       ┆ I          ┆ gelatinosu ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ s          ┆   ┆           ┆           ┆           ┆           │
│ WP_0007772 ┆ Zorya ┆ Zorya_Type ┆ Escherichi ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 76.1       ┆       ┆ II         ┆ a coli,Shi ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ gella      ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ flex…      ┆   ┆           ┆           ┆           ┆           │
│ WP_0115132 ┆ Zorya ┆ Zorya_Type ┆ Psychrobac ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 96.1       ┆       ┆ I          ┆ ter cryoha ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ lolentis   ┆   ┆           ┆           ┆           ┆           │
│ WP_0012525 ┆ Zorya ┆ Zorya_Type ┆ Vibrio     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 11.1       ┆       ┆ I          ┆ cholerae   ┆   ┆           ┆           ┆           ┆           │
│ WP_0209595 ┆ Zorya ┆ Zorya_Type ┆ Geobacillu ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 43.1       ┆       ┆ I          ┆ s          ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ genomosp.  ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ 3          ┆   ┆           ┆           ┆           ┆           │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘