In [1]:
import logging
import os
import sys

from dotenv import load_dotenv
from matplotlib.ticker import FuncFormatter
from matplotlib import pyplot as plt
from pathlib import Path
from typing import Tuple

import numpy as np
import polars as pl

# Env
pl.Config.set_tbl_rows(10)
load_dotenv("../.env")
INSTALL_PATH = os.environ["INSTALL_PATH"]
URL_AF = os.environ["API_URL_ALPHAFOLD_STRUCTPRED"]
sys.path.append(str(Path(INSTALL_PATH).resolve()))

# Modules
from modules.pymol_align import get_alphafold_structures, pymol_align_pairs

# Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s:%(name)s:%(message)s"
)
logger = logging.getLogger(__name__)

### Steps

1. Apply preliminary filtering criteria
2. Apply PyMOL alignment
3. Lookup how SMARCA4, KPNA2 fare

<br>

### Questions

1. What is the difference between `evalue` and `evalue_foldseek` cols? (`/hpf/projects/CTrost/ajain/IEI_project`)

In [10]:
# ────────────────────────────────────────────────────────────
#      Args
# ────────────────────────────────────────────────────────────

VAR_NAME_LENGTH_ERROR = "Protein_length_difference"
VAR_NAME_LOG_EVALUE = "neg_log(evalue_foldseek)"
THRESHOLD_LENGTH_ERROR = 0.05
THRESHOLD_OVERLAP_RATIO = 0.0
PYMOL_ALIGN_METHOD = "super"
COL_CLUSTER_ID = "cluster_id"
COL_BACT_PROT_ID = "defense_system_protein_id"
COL_HS_PROT_ID = "protein_id"
COL_EVALUE = "evalue_foldseek"

OUT_DIR = Path(f"{INSTALL_PATH}/results/explore_zorya")
OUT_DIR_AF = Path(f"{INSTALL_PATH}/data_local/alphafold_structures")
OUT_DIR_PM = Path(f"{INSTALL_PATH}/data_local/pymol_alignments/{PYMOL_ALIGN_METHOD}")

data_file = f"{INSTALL_PATH}/data_local/zorya/2025-07-27_zorya_annotated.tsv"

gene_names_to_uniprot = {
    "SMARCA4": "A0A2R8Y866",
    "DDX1": "Q92499",
    "BTAF": "O14981",
}

In [8]:
# ────────────────────────────────────────────────────────────
#      In
# ────────────────────────────────────────────────────────────

OUT_DIR.mkdir(exist_ok=True, parents=True)
OUT_DIR_AF.mkdir(exist_ok=True, parents=True)
OUT_DIR_PM.mkdir(exist_ok=True, parents=True)

df = pl.read_csv(
            data_file,
            has_header=True,
            separator="\t",
            schema_overrides={
                "duplicate_count": pl.Int64,
                "rank": pl.Int64,
                "evalue": pl.Float64,
                "cluFlag": pl.Int64,
                "fident": pl.Float64,
                "alnlen": pl.Int64,
                "mismatch": pl.Int64,
                "gapopen": pl.Float64,
                "qstart": pl.Int64,
                "qend": pl.Int64,
                "tstart": pl.Int64,
                "tend": pl.Int64,
                "evalue_foldseek": pl.Float64,
                "bits": pl.Int64,
                "Query_length": pl.Int64,
                "Human_prot_total_length": pl.Int64,
                "Human_domain_percentage": pl.Float64,
                "Query_percentage": pl.Float64,
                "Query_overlap_w_Human_protein": pl.Float64,
                "Target_length": pl.Int64,
                "Bacterial_prot_total_length": pl.Int64,
                "Bacterial_domain_percentage": pl.Float64,
                "Target_percentage": pl.Float64,
                "Target_overlap_w_Bacterial_protein": pl.Float64,
                "Bacterial_Human_Len_Ratio": pl.Float64,
                "Query_Target_Overlap_Length": pl.Float64,
                "Overlap_ratio": pl.Float64,
            },
            infer_schema_length=10000
        )

df

shape: (99_469, 70)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ accession_ ┆ type  ┆ subtype    ┆ species    ┆ … ┆ Bacterial ┆ Bacterial ┆ Query_Tar ┆ Overlap_r │
│ in_sys     ┆ ---   ┆ ---        ┆ ---        ┆   ┆ _domain_e ┆ _Human_Le ┆ get_Overl ┆ atio      │
│ ---        ┆ str   ┆ str        ┆ str        ┆   ┆ vidence   ┆ n_Ratio   ┆ ap_Length ┆ ---       │
│ str        ┆       ┆            ┆            ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64       │
│            ┆       ┆            ┆            ┆   ┆ str       ┆ f64       ┆ f64       ┆           │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ WP_0631924 ┆ Zorya ┆ Zorya_Type ┆ Geobacillu ┆ … ┆ ['ECO:000 ┆ 0.861933  ┆ 658.0     ┆ 0.75286   │
│ 62.1       ┆       ┆ I          ┆ s sp. JS12 ┆   ┆ 0259|PROS ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ ITE:PS511 ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ 94'…      ┆           ┆           ┆           │
│ WP_0631924 ┆ Zorya ┆ Zorya_Type ┆ Geobacillu ┆ … ┆ ['ECO:000 ┆ 0.861933  ┆ 658.0     ┆ 0.75286   │
│ 62.1       ┆       ┆ I          ┆ s sp. JS12 ┆   ┆ 0259|PROS ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ ITE:PS511 ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ 94'…      ┆           ┆           ┆           │
│ WP_0631924 ┆ Zorya ┆ Zorya_Type ┆ Geobacillu ┆ … ┆ ['ECO:000 ┆ 0.861933  ┆ 658.0     ┆ 0.75286   │
│ 62.1       ┆       ┆ I          ┆ s sp. JS12 ┆   ┆ 0259|PROS ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ ITE:PS511 ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ 94'…      ┆           ┆           ┆           │
│ WP_0631924 ┆ Zorya ┆ Zorya_Type ┆ Geobacillu ┆ … ┆ ['ECO:000 ┆ 0.861933  ┆ 658.0     ┆ 0.75286   │
│ 62.1       ┆       ┆ I          ┆ s sp. JS12 ┆   ┆ 0259|PROS ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ ITE:PS511 ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ 94'…      ┆           ┆           ┆           │
│ WP_0631924 ┆ Zorya ┆ Zorya_Type ┆ Geobacillu ┆ … ┆ ['ECO:000 ┆ 0.861933  ┆ 658.0     ┆ 0.75286   │
│ 62.1       ┆       ┆ I          ┆ s sp. JS12 ┆   ┆ 0259|PROS ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ ITE:PS511 ┆           ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ 94'…      ┆           ┆           ┆           │
│ …          ┆ …     ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ WP_0144280 ┆ Zorya ┆ Zorya_Type ┆ Rubrivivax ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 04.1       ┆       ┆ I          ┆ gelatinosu ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ s          ┆   ┆           ┆           ┆           ┆           │
│ WP_0007772 ┆ Zorya ┆ Zorya_Type ┆ Escherichi ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 76.1       ┆       ┆ II         ┆ a coli,Shi ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ gella      ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ flex…      ┆   ┆           ┆           ┆           ┆           │
│ WP_0115132 ┆ Zorya ┆ Zorya_Type ┆ Psychrobac ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 96.1       ┆       ┆ I          ┆ ter cryoha ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ lolentis   ┆   ┆           ┆           ┆           ┆           │
│ WP_0012525 ┆ Zorya ┆ Zorya_Type ┆ Vibrio     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 11.1       ┆       ┆ I          ┆ cholerae   ┆   ┆           ┆           ┆           ┆           │
│ WP_0209595 ┆ Zorya ┆ Zorya_Type ┆ Geobacillu ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 43.1       ┆       ┆ I          ┆ s          ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ genomosp.  ┆   ┆           ┆           ┆           ┆           │
│            ┆       ┆            ┆ 3          ┆   ┆           ┆           ┆           ┆           │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [18]:
# ────────────────────────────────────────────────────────────
#      Check
# ────────────────────────────────────────────────────────────

df_filt = df.filter(
    pl.col(COL_HS_PROT_ID).is_in(gene_names_to_uniprot.values())
)

df_filt["Entry Name"].unique()

shape: (1,)
Series: 'Entry Name' [str]
[
	"DDX1_HUMAN"
]