### Test automated pairwise alignments with PyMol
### Julian Moran
### 2026-02-20

In [3]:
import logging
import os
import requests
import subprocess
import tempfile
import time

from dotenv import load_dotenv
from pathlib import Path
from typing import Dict

import polars as pl

# Env
load_dotenv("../.env", override=True)
INSTALL_PATH = os.environ["INSTALL_PATH"]
API_URL_ALPHAFOLD_STRUCTPRED = os.environ["API_URL_ALPHAFOLD_STRUCTPRED"]

# Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s:%(name)s:%(message)s"
)
logger = logging.getLogger(__name__)

In [4]:
# ============================================================
#                           Args
# ============================================================

PM_ALIGN_METHOD = "cealign" # set to "align", "cealign", or "super"

args = {
    "data_file_protein_pairs": f"{INSTALL_PATH}/results/explore_aJain_iei_pipeline/defense_proteins_filt_n=297.tsv",
    "col_query_protein_ids": "defense_system_protein_id",
    "col_target_protein_ids": "protein_id",
    "out_dir": Path(f"{INSTALL_PATH}/results/test_pymol_align/"),
    "out_dir_af": Path(f"{INSTALL_PATH}/data_local/alphafold_structures"),
    "out_dir_pm": Path(f"{INSTALL_PATH}/data_local/pymol_alignments/{PM_ALIGN_METHOD}")
}

In [5]:
# ============================================================
#                           In
# ============================================================

args["out_dir"].mkdir(parents=True, exist_ok=True)
args["out_dir_pm"].mkdir(parents=True, exist_ok=True)
args["out_dir_af"].mkdir(parents=True, exist_ok=True)

df_protein_pairs = pl.read_csv(
    args["data_file_protein_pairs"],
    separator="\t",
    has_header=True
)

df_protein_pairs

shape: (297, 71)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ accession_ ┆ type    ┆ subtype   ┆ species   ┆ … ┆ Bacterial ┆ Query_Tar ┆ Overlap_r ┆ GRIID_gen │
│ in_sys     ┆ ---     ┆ ---       ┆ ---       ┆   ┆ _Human_Le ┆ get_Overl ┆ atio      ┆ e         │
│ ---        ┆ str     ┆ str       ┆ str       ┆   ┆ n_Ratio   ┆ ap_Length ┆ ---       ┆ ---       │
│ str        ┆         ┆           ┆           ┆   ┆ ---       ┆ ---       ┆ f64       ┆ str       │
│            ┆         ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆           │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ WP_0745856 ┆ Eleos   ┆ Eleos     ┆ Bacillus  ┆ … ┆ 0.722846  ┆ 574.0     ┆ 0.991364  ┆ Yes       │
│ 35.1       ┆         ┆           ┆ mobilis,B ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆           ┆ acillus   ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆           ┆ cere…     ┆   ┆           ┆           ┆           ┆           │
│ WP_0745856 ┆ Eleos   ┆ Eleos     ┆ Bacillus  ┆ … ┆ 0.716584  ┆ 568.0     ┆ 0.981002  ┆ Yes       │
│ 35.1       ┆         ┆           ┆ mobilis,B ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆           ┆ acillus   ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆           ┆ cere…     ┆   ┆           ┆           ┆           ┆           │
│ WP_0004346 ┆ Eleos   ┆ Eleos     ┆ Escherich ┆ … ┆ 0.762219  ┆ 563.0     ┆ 0.975737  ┆ Yes       │
│ 27.1       ┆         ┆           ┆ ia coli   ┆   ┆           ┆           ┆           ┆           │
│ WP_0745856 ┆ Eleos   ┆ Eleos     ┆ Bacillus  ┆ … ┆ 0.83913   ┆ 547.0     ┆ 0.944732  ┆ Yes       │
│ 35.1       ┆         ┆           ┆ mobilis,B ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆           ┆ acillus   ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆           ┆ cere…     ┆   ┆           ┆           ┆           ┆           │
│ WP_0004346 ┆ Eleos   ┆ Eleos     ┆ Escherich ┆ … ┆ 0.836232  ┆ 556.0     ┆ 0.963605  ┆ Yes       │
│ 27.1       ┆         ┆           ┆ ia coli   ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …       ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ WP_0022877 ┆ Thoeris ┆ Thoeris_I ┆ Enterococ ┆ … ┆ 0.925287  ┆ 141.0     ┆ 0.875776  ┆ No        │
│ 00.1       ┆         ┆           ┆ cus faeca ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆           ┆ lis,Enter ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆           ┆ oco…      ┆   ┆           ┆           ┆           ┆           │
│ WP_0022877 ┆ Thoeris ┆ Thoeris_I ┆ Enterococ ┆ … ┆ 0.925287  ┆ 141.0     ┆ 0.875776  ┆ No        │
│ 00.1       ┆         ┆           ┆ cus faeca ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆           ┆ lis,Enter ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆           ┆ oco…      ┆   ┆           ┆           ┆           ┆           │
│ WP_0807272 ┆ Gao_Qat ┆ Gao_Qat   ┆ Sphingobi ┆ … ┆ 0.923358  ┆ 244.0     ┆ 0.964427  ┆ No        │
│ 48.1       ┆         ┆           ┆ um sp.    ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆           ┆ CAP-1,Sph ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆           ┆ ingob…    ┆   ┆           ┆           ┆           ┆           │
│ WP_0022373 ┆ RM      ┆ RM_Type_I ┆ Neisseria ┆ … ┆ 0.964789  ┆ 338.0     ┆ 0.616788  ┆ Yes       │
│ 77.1       ┆         ┆ I         ┆ meningiti ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆           ┆ dis       ┆   ┆           ┆           ┆           ┆           │
│ WP_0022373 ┆ RM      ┆ RM_Type_I ┆ Neisseria ┆ … ┆ 0.964789  ┆ 338.0     ┆ 0.616788  ┆ Yes       │
│ 77.1       ┆         ┆ I         ┆ meningiti ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆           ┆ dis       ┆   ┆           ┆           ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [6]:
# ============================================================
#                      AlphaFold structures
# ============================================================

def get_alphafold_structure(
        uniprot_id: str,
        out_dir: Path,
        api_endpoint: str,
        wait_time: float = 1.0,
        overwrite: bool = False,
) -> str | None:
    
    # Check if file already exists:
    out_file = f"{out_dir}/{uniprot_id}_AF.pdb"
    if os.path.exists(out_file) and not overwrite:
        logger.warning(f"For {uniprot_id}, ALphaFold structure is already on file at {out_file}.")
        return out_file

    time.sleep(wait_time)
    url = f"{api_endpoint}/{uniprot_id}"
    logger.info(url)
    headers = {"accept": "application/json"}
    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()
    except requests.RequestException as e:
        logger.warning(f"For {uniprot_id}, failed to retrieve: {e}")
        return None
    url_pdb = response.json()[0].get("pdbUrl", None)

    if url_pdb is not None:
        logger.info(f"For {uniprot_id}, retrieving .pdb from {url_pdb}...")
        try:
            response = requests.get(url_pdb)
            response.raise_for_status()
        except requests.RequestException as e:
            logger.warning(f"For {uniprot_id}, failed to retrieve: {e}")
            return None

        with open(out_file, "wb") as f:
            f.write(response.content)
        logger.info(f"For {uniprot_id}, AlphaFold predicted structure written to {out_file}.")
        return out_file
    
    else:
        logger.warning(f"For {uniprot_id}, AlphaFold structure not found.")
        return None


def get_alphafold_structures(
    df_uniprot_ids: pl.DataFrame,
    col_query_uniprot_id: str,
    col_target_uniprot_id: str,
    out_dir: Path,
    api_endpoint: str,
    wait_time: float = 1.0,
    overwrite: bool = False,
) -> pl.DataFrame:
    
    # Initialize column structures
    col_query_structure_file_name = col_query_uniprot_id.replace("_id", "_AF_file")
    col_target_structure_file_name = col_target_uniprot_id.replace("_id", "_AF_file")
    col_query_structure_file, col_target_structure_file = [], []

    for i in range(len(df_uniprot_ids)):

        # Query proteins
        query_protein_structure_file = get_alphafold_structure(
            uniprot_id=df_uniprot_ids[i, col_query_uniprot_id],
            out_dir=out_dir,
            api_endpoint=api_endpoint,
            wait_time=wait_time,
            overwrite=overwrite
        )
        col_query_structure_file.append(query_protein_structure_file)

        # Target proteins
        target_protein_structure_file = get_alphafold_structure(
            uniprot_id=df_uniprot_ids[i, col_target_uniprot_id],
            out_dir=out_dir,
            api_endpoint=api_endpoint,
            wait_time=wait_time
        )
        col_target_structure_file.append(target_protein_structure_file)
    
    # Annotate file name to data
    df = df_uniprot_ids.with_columns(
        pl.Series(col_query_structure_file_name, col_query_structure_file)
    ).with_columns(
        pl.Series(col_target_structure_file_name, col_target_structure_file)
    )
    
    return df, col_query_structure_file_name, col_target_structure_file_name

df_structure_files = df_protein_pairs[args["col_query_protein_ids"], args["col_target_protein_ids"]]
df_structure_files, col_query_struct, col_target_struct = get_alphafold_structures(
    df_uniprot_ids=df_structure_files,
    col_query_uniprot_id=args["col_query_protein_ids"],
    col_target_uniprot_id=args["col_target_protein_ids"],
    out_dir=args["out_dir_af"],
    api_endpoint=API_URL_ALPHAFOLD_STRUCTPRED
)

df_structure_files

WARNING:__main__:For A0A1Y6A5H7, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A1Y6A5H7_AF.pdb.
WARNING:__main__:For A0A6Q8PGV8, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A6Q8PGV8_AF.pdb.
WARNING:__main__:For A0A556BFS8, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A556BFS8_AF.pdb.
WARNING:__main__:For A0A6Q8PFJ4, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A6Q8PFJ4_AF.pdb.
WARNING:__main__:For Q9RFR9, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/Q9RFR9_AF.pdb.
WARNING:__main__:For O95140, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/O95140_AF.pdb.
WARNING:__main__:For A0A556BFS8, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A556BFS8_AF.pdb.
WARNING:__main__:For A0A6Q8PGA3, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A6Q8PGA3_AF.pdb.
WARNING:__main__:For Q9RFR9, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/Q9RFR9_AF.pdb.
WARNING:__main__:For A0A6Q8PGA3, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A6Q8PGA3_AF.pdb.
WARNING:__main__:For Q9RFR9, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/Q9RFR9_AF.pdb.
WARNING:__main__:For A0A6Q8PFJ4, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A6Q8PFJ4_AF.pdb.
WARNING:__main__:For A0A1Y6A5H7, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A1Y6A5H7_AF.pdb.
WARNING:__main__:For A0A6Q8PGA3, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A6Q8PGA3_AF.pdb.
WARNING:__main__:For A0A556BFS8, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A556BFS8_AF.pdb.
WARNING:__main__:For O95140, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/O95140_AF.pdb.
WARNING:__main__:For A0A1Y6A5H7, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A1Y6A5H7_AF.pdb.
WARNING:__main__:For A0A6Q8PFJ4, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A6Q8PFJ4_AF.pdb.
WARNING:__main__:For Q9RFR9, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/Q9RFR9_AF.pdb.
WARNING:__main__:For A0A6Q8PGV8, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A6Q8PGV8_AF.pdb.
WARNING:__main__:For A0A1Y6A5H7, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A1Y6A5H7_AF.pdb.
WARNING:__main__:For O95140, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/O95140_AF.pdb.
WARNING:__main__:For A0A556BFS8, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A556BFS8_AF.pdb.
WARNING:__main__:For A0A6Q8PGV8, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A6Q8PGV8_AF.pdb.
WARNING:__main__:For A0A411A3U6, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A411A3U6_AF.pdb.
WARNING:__main__:For A0A2S1ZR87, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A2S1ZR87_AF.pdb.
WARNING:__main__:For A0A411A3U6, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A411A3U6_AF.pdb.
WARNING:__main__:For Q8IY18, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/Q8IY18_AF.pdb.
WARNING:__main__:For A0A411A3U6, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A411A3U6_AF.pdb.
WARNING:__main__:For Q96SB8, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/Q96SB8_AF.pdb.
WARNING:__main__:For A0A411A3U6, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A411A3U6_AF.pdb.
WARNING:__main__:For A0A2S1ZR79, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A2S1ZR79_AF.pdb.
WARNING:__main__:For A0A5C0DWF7, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A5C0DWF7_AF.pdb.
WARNING:__main__:For Q9HCK5, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/Q9HCK5_AF.pdb.
WARNING:__main__:For A0A7L4ZQB6, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7L4ZQB6_AF.pdb.
WARNING:__main__:For B4DT76, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb.
WARNING:__main__:For A0A7G5XFN1, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7G5XFN1_AF.pdb.
WARNING:__main__:For B4DT76, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb.
WARNING:__main__:For A0A6P1XY11, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A6P1XY11_AF.pdb.
WARNING:__main__:For B4DT76, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb.
WARNING:__main__:For A0A0X3BJA1, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A0X3BJA1_AF.pdb.
WARNING:__main__:For A0A7P0TA11, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb.
WARNING:__main__:For A0A3G3IG56, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A3G3IG56_AF.pdb.
WARNING:__main__:For A0A7P0TA11, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb.
WARNING:__main__:For A0A109D532, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A109D532_AF.pdb.
WARNING:__main__:For A0A7P0TA11, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb.
WARNING:__main__:For A0A3G3IIY6, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A3G3IIY6_AF.pdb.
WARNING:__main__:For A0A7P0TA11, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb.
WARNING:__main__:For A0A3G3IIY6, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A3G3IIY6_AF.pdb.
WARNING:__main__:For B4DT76, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb.
WARNING:__main__:For D1ADX3, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/D1ADX3_AF.pdb.
WARNING:__main__:For B4DT76, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb.
WARNING:__main__:For A0A7L4ZQB6, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7L4ZQB6_AF.pdb.
WARNING:__main__:For A0A7P0TA11, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb.
WARNING:__main__:For A0A0K1EKA3, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A0K1EKA3_AF.pdb.
WARNING:__main__:For B4DT76, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb.
WARNING:__main__:For A0A222EQ20, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A222EQ20_AF.pdb.
WARNING:__main__:For A0A7P0TA11, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb.
WARNING:__main__:For L0L185, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/L0L185_AF.pdb.
WARNING:__main__:For A0A7P0TA11, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb.
WARNING:__main__:For Q73LQ7, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/Q73LQ7_AF.pdb.
WARNING:__main__:For B4DT76, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb.
WARNING:__main__:For D5EID4, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/D5EID4_AF.pdb.
WARNING:__main__:For B4DT76, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb.
WARNING:__main__:For D5EID4, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/D5EID4_AF.pdb.
WARNING:__main__:For A0A7P0TA11, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb.
WARNING:__main__:For Q3A0F3, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/Q3A0F3_AF.pdb.
WARNING:__main__:For A0A7P0TA11, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb.
WARNING:__main__:For A0A2K8UJG1, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A2K8UJG1_AF.pdb.
WARNING:__main__:For B4DT76, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb.
WARNING:__main__:For A0A6P1XY11, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A6P1XY11_AF.pdb.
WARNING:__main__:For A0A7P0TA11, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb.
WARNING:__main__:For A0A5S9F266, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A5S9F266_AF.pdb.
WARNING:__main__:For B4DT76, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb.
WARNING:__main__:For A0A2Z2MWB5, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A2Z2MWB5_AF.pdb.
WARNING:__main__:For A0A7P0TA11, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb.
WARNING:__main__:For A0A7H5CVR4, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7H5CVR4_AF.pdb.
WARNING:__main__:For A0A7P0TA11, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb.
WARNING:__main__:For A0A3Q0KZ59, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A3Q0KZ59_AF.pdb.
WARNING:__main__:For A0A7P0TA11, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb.
WARNING:__main__:For M9SLJ0, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/M9SLJ0_AF.pdb.
WARNING:__main__:For A0A7P0TA11, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb.
WARNING:__main__:For A0A0X3BJA1, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A0X3BJA1_AF.pdb.
WARNING:__main__:For B4DT76, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb.
WARNING:__main__:For A9L1Z3, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A9L1Z3_AF.pdb.
WARNING:__main__:For A0A7P0TA11, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb.
WARNING:__main__:For A0A5S9F266, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A5S9F266_AF.pdb.
WARNING:__main__:For A0A7P0TA11, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb.
WARNING:__main__:For I7LJ27, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/I7LJ27_AF.pdb.
WARNING:__main__:For A0A7P0TA11, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb.
WARNING:__main__:For A0A3Q0KZ59, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A3Q0KZ59_AF.pdb.
WARNING:__main__:For B4DT76, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb.
WARNING:__main__:For A0A7G5XFN1, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7G5XFN1_AF.pdb.
WARNING:__main__:For A0A7P0TA11, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb.
WARNING:__main__:For A0A5B9D673, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A5B9D673_AF.pdb.
WARNING:__main__:For A0A7P0TA11, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb.
WARNING:__main__:For U5Q1R3, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/U5Q1R3_AF.pdb.
WARNING:__main__:For B4DT76, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb.
WARNING:__main__:For D1ADX3, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/D1ADX3_AF.pdb.
WARNING:__main__:For A0A7P0TA11, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb.
WARNING:__main__:For A0A3G3IG56, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A3G3IG56_AF.pdb.
WARNING:__main__:For B4DT76, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb.
WARNING:__main__:For Q73LQ7, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/Q73LQ7_AF.pdb.
WARNING:__main__:For A0A7P0TA11, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb.
WARNING:__main__:For M9SLJ0, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/M9SLJ0_AF.pdb.
WARNING:__main__:For B4DT76, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb.
WARNING:__main__:For Q3A0F3, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/Q3A0F3_AF.pdb.
WARNING:__main__:For B4DT76, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb.
WARNING:__main__:For A0A2Z2MWB5, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A2Z2MWB5_AF.pdb.
WARNING:__main__:For B4DT76, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb.
WARNING:__main__:For A0A222EQ20, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A222EQ20_AF.pdb.
WARNING:__main__:For B4DT76, ALphaFold structure is already on file at /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb.

shape: (297, 4)
┌───────────────────────────┬────────────┬────────────────────────────┬────────────────────────────┐
│ defense_system_protein_id ┆ protein_id ┆ defense_system_protein_AF_ ┆ protein_AF_file            │
│ ---                       ┆ ---        ┆ file                       ┆ ---                        │
│ str                       ┆ str        ┆ ---                        ┆ str                        │
│                           ┆            ┆ str                        ┆                            │
╞═══════════════════════════╪════════════╪════════════════════════════╪════════════════════════════╡
│ A0A1Y6A5H7                ┆ A0A6Q8PGV8 ┆ /home/juliandeanmoran/___g ┆ /home/juliandeanmoran/___g │
│                           ┆            ┆ it_r…                      ┆ it_r…                      │
│ A0A556BFS8                ┆ A0A6Q8PFJ4 ┆ /home/juliandeanmoran/___g ┆ /home/juliandeanmoran/___g │
│                           ┆            ┆ it_r…                      ┆ it_r…                      │
│ Q9RFR9                    ┆ O95140     ┆ /home/juliandeanmoran/___g ┆ /home/juliandeanmoran/___g │
│                           ┆            ┆ it_r…                      ┆ it_r…                      │
│ A0A556BFS8                ┆ A0A6Q8PGA3 ┆ /home/juliandeanmoran/___g ┆ /home/juliandeanmoran/___g │
│                           ┆            ┆ it_r…                      ┆ it_r…                      │
│ Q9RFR9                    ┆ A0A6Q8PGA3 ┆ /home/juliandeanmoran/___g ┆ /home/juliandeanmoran/___g │
│                           ┆            ┆ it_r…                      ┆ it_r…                      │
│ …                         ┆ …          ┆ …                          ┆ …                          │
│ Q3Y0J6                    ┆ O43598     ┆ /home/juliandeanmoran/___g ┆ /home/juliandeanmoran/___g │
│                           ┆            ┆ it_r…                      ┆ it_r…                      │
│ A0A829F2V1                ┆ O43598     ┆ /home/juliandeanmoran/___g ┆ /home/juliandeanmoran/___g │
│                           ┆            ┆ it_r…                      ┆ it_r…                      │
│ A0A6P1GFG5                ┆ Q17R31     ┆ /home/juliandeanmoran/___g ┆ /home/juliandeanmoran/___g │
│                           ┆            ┆ it_r…                      ┆ it_r…                      │
│ A0A0U1RHB2                ┆ A0A669KBB4 ┆ /home/juliandeanmoran/___g ┆ /home/juliandeanmoran/___g │
│                           ┆            ┆ it_r…                      ┆ it_r…                      │
│ X5EGL0                    ┆ A0A669KBB4 ┆ /home/juliandeanmoran/___g ┆ /home/juliandeanmoran/___g │
│                           ┆            ┆ it_r…                      ┆ it_r…                      │
└───────────────────────────┴────────────┴────────────────────────────┴────────────────────────────┘

In [20]:
# ============================================================
#                      PyMol: pairwise alignment
# ============================================================

def pymol_align_pair(
    pdb_query: str,
    pdb_target: str,
    out_path_structure: str,
    pymol_align_method: str,
    overwrite: bool = False,
) -> tuple[str, str]:
    
    # Check if alignment file already exists
    if os.path.exists(out_path_structure) and not overwrite:
        logger.warning(f"For {pdb_query}, {pdb_target} PyMol alignment is already on file at {out_path_structure}. Add overwrite=True if you wish to run alignment again.")
        return None, None

    pymol_script = f"""
from pymol import cmd

cmd.load(r"{pdb_query}", "s1")
cmd.load(r"{pdb_target}", "s2")

cmd.hide("everything")
cmd.show("cartoon", "s1")
cmd.show("cartoon", "s2")
cmd.color("blue", "s1")
cmd.color("red", "s2")

r = cmd.{pymol_align_method}("s1", "s2")

print("METRICS\\t%f\\t%d" % (r[0], r[1]))
cmd.save(r"{out_path_structure}")
cmd.quit()
"""

    # Run alignment
    with tempfile.NamedTemporaryFile("w", suffix=".py", delete=False) as tmp:
        tmp.write(pymol_script)
        script_path = tmp.name
    result = subprocess.run(
        ["pymol", "-cq", script_path],
        capture_output=True,
        text=True,
        check=True,
    )

    logger.info(f"For {pdb_query},{pdb_target}, wrote alignment results to {out_path_structure}.")

    # Capture alignment performance metrics
    rmsd = None
    aligned_atoms = None

    for line in result.stdout.splitlines():
        if line.startswith("METRICS"):
            _, rmsd, aligned_atoms = line.split("\t")
            rmsd = float(rmsd)
            aligned_atoms = int(aligned_atoms)
    return rmsd, aligned_atoms


def pymol_align_pairs(
    df_structure_files: pl.DataFrame,
    col_query_id: str,
    col_query_struct: str,
    col_target_id: str,
    col_target_struct: str,
    out_dir: str,
    pymol_align_method: str,
    overwrite: bool = False,
) -> pl.DataFrame:
    
    col_struct_paths, col_rmsd, col_aligned_atoms = [], [], []

    for i in range(len(df_structure_files)):
        query_id = df_structure_files[i, col_query_id]
        target_id = df_structure_files[i, col_target_id]
        out_path_structure = f"{out_dir}/{query_id}_{target_id}_aligned.pse"

        rmsd, aligned_atoms = pymol_align_pair(
            pdb_query=df_structure_files[i, col_query_struct],
            pdb_target=df_structure_files[i, col_target_struct],
            out_path_structure=out_path_structure,
            pymol_align_method=pymol_align_method,
            overwrite=overwrite
        )
        col_struct_paths.append(out_path_structure)
        col_rmsd.append(rmsd)
        col_aligned_atoms.append(aligned_atoms)
    
    df = df_structure_files.with_columns(
        pl.Series("PyMOL_aligned_filePath", col_struct_paths)
    ).with_columns(
        pl.Series("PyMOL_RMSD", col_rmsd)
    ).with_columns(
        pl.Series("PyMOL_aligned_atoms", col_aligned_atoms)
    )
    return df

df_structures_aligned = pymol_align_pairs(
    df_structure_files=df_structure_files,
    col_query_id=args["col_query_protein_ids"],
    col_query_struct=col_query_struct,
    col_target_id=args["col_target_protein_ids"],
    col_target_struct=col_target_struct,
    pymol_align_method=PM_ALIGN_METHOD,
    out_dir=args["out_dir_pm"]
)

df_structures_aligned

INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A1Y6A5H7_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A6Q8PGV8_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A1Y6A5H7_A0A6Q8PGV8_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A556BFS8_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A6Q8PFJ4_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A556BFS8_A0A6Q8PFJ4_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/Q9RFR9_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/O95140_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/Q9RFR9_O95140_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A556BFS8_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A6Q8PGA3_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A556BFS8_A0A6Q8PGA3_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/Q9RFR9_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A6Q8PGA3_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/Q9RFR9_A0A6Q8PGA3_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/Q9RFR9_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A6Q8PFJ4_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/Q9RFR9_A0A6Q8PFJ4_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A1Y6A5H7_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A6Q8PGA3_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A1Y6A5H7_A0A6Q8PGA3_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A556BFS8_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/O95140_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A556BFS8_O95140_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A1Y6A5H7_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A6Q8PFJ4_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A1Y6A5H7_A0A6Q8PFJ4_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/Q9RFR9_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A6Q8PGV8_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/Q9RFR9_A0A6Q8PGV8_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A1Y6A5H7_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/O95140_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A1Y6A5H7_O95140_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A556BFS8_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A6Q8PGV8_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A556BFS8_A0A6Q8PGV8_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A411A3U6_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A2S1ZR87_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A411A3U6_A0A2S1ZR87_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A411A3U6_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/Q8IY18_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A411A3U6_Q8IY18_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A411A3U6_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/Q96SB8_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A411A3U6_Q96SB8_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A411A3U6_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A2S1ZR79_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A411A3U6_A0A2S1ZR79_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A5C0DWF7_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/Q9HCK5_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A5C0DWF7_Q9HCK5_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7L4ZQB6_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A7L4ZQB6_B4DT76_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7G5XFN1_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A7G5XFN1_B4DT76_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A6P1XY11_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A6P1XY11_B4DT76_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A0X3BJA1_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A0X3BJA1_A0A7P0TA11_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A3G3IG56_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A3G3IG56_A0A7P0TA11_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A109D532_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A109D532_A0A7P0TA11_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A3G3IIY6_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A3G3IIY6_A0A7P0TA11_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A3G3IIY6_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A3G3IIY6_B4DT76_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/D1ADX3_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/D1ADX3_B4DT76_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7L4ZQB6_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A7L4ZQB6_A0A7P0TA11_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A0K1EKA3_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A0K1EKA3_B4DT76_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A222EQ20_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A222EQ20_A0A7P0TA11_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/L0L185_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/L0L185_A0A7P0TA11_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/Q73LQ7_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/Q73LQ7_B4DT76_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/D5EID4_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/D5EID4_B4DT76_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/D5EID4_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/D5EID4_A0A7P0TA11_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/Q3A0F3_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/Q3A0F3_A0A7P0TA11_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A2K8UJG1_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A2K8UJG1_B4DT76_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A6P1XY11_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A6P1XY11_A0A7P0TA11_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A5S9F266_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A5S9F266_B4DT76_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A2Z2MWB5_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A2Z2MWB5_A0A7P0TA11_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7H5CVR4_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A7H5CVR4_A0A7P0TA11_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A3Q0KZ59_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A3Q0KZ59_A0A7P0TA11_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/M9SLJ0_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/M9SLJ0_A0A7P0TA11_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A0X3BJA1_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A0X3BJA1_B4DT76_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A9L1Z3_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A9L1Z3_A0A7P0TA11_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A5S9F266_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A5S9F266_A0A7P0TA11_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/I7LJ27_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/I7LJ27_A0A7P0TA11_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A3Q0KZ59_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A3Q0KZ59_B4DT76_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7G5XFN1_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A7G5XFN1_A0A7P0TA11_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A5B9D673_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A5B9D673_A0A7P0TA11_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/U5Q1R3_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/U5Q1R3_B4DT76_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/D1ADX3_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/D1ADX3_A0A7P0TA11_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A3G3IG56_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/A0A3G3IG56_B4DT76_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/Q73LQ7_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A7P0TA11_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/Q73LQ7_A0A7P0TA11_aligned.pse.
INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/M9SLJ0_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/B4DT76_AF.pdb, wrote alignment results to /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/pymol_alignments/cealign/M9SLJ0_B4DT76_aligned.pse.

shape: (297, 7)
┌──────────────┬────────────┬──────────────┬──────────────┬─────────────┬────────────┬─────────────┐
│ defense_syst ┆ protein_id ┆ defense_syst ┆ protein_AF_f ┆ PyMOL_align ┆ PyMOL_RMSD ┆ PyMOL_align │
│ em_protein_i ┆ ---        ┆ em_protein_A ┆ ile          ┆ ed_filePath ┆ ---        ┆ ed_atoms    │
│ d            ┆ str        ┆ F_file       ┆ ---          ┆ ---         ┆ null       ┆ ---         │
│ ---          ┆            ┆ ---          ┆ str          ┆ str         ┆            ┆ null        │
│ str          ┆            ┆ str          ┆              ┆             ┆            ┆             │
╞══════════════╪════════════╪══════════════╪══════════════╪═════════════╪════════════╪═════════════╡
│ A0A1Y6A5H7   ┆ A0A6Q8PGV8 ┆ /home/julian ┆ /home/julian ┆ /home/julia ┆ null       ┆ null        │
│              ┆            ┆ deanmoran/__ ┆ deanmoran/__ ┆ ndeanmoran/ ┆            ┆             │
│              ┆            ┆ _git_r…      ┆ _git_r…      ┆ ___git_r…   ┆            ┆             │
│ A0A556BFS8   ┆ A0A6Q8PFJ4 ┆ /home/julian ┆ /home/julian ┆ /home/julia ┆ null       ┆ null        │
│              ┆            ┆ deanmoran/__ ┆ deanmoran/__ ┆ ndeanmoran/ ┆            ┆             │
│              ┆            ┆ _git_r…      ┆ _git_r…      ┆ ___git_r…   ┆            ┆             │
│ Q9RFR9       ┆ O95140     ┆ /home/julian ┆ /home/julian ┆ /home/julia ┆ null       ┆ null        │
│              ┆            ┆ deanmoran/__ ┆ deanmoran/__ ┆ ndeanmoran/ ┆            ┆             │
│              ┆            ┆ _git_r…      ┆ _git_r…      ┆ ___git_r…   ┆            ┆             │
│ A0A556BFS8   ┆ A0A6Q8PGA3 ┆ /home/julian ┆ /home/julian ┆ /home/julia ┆ null       ┆ null        │
│              ┆            ┆ deanmoran/__ ┆ deanmoran/__ ┆ ndeanmoran/ ┆            ┆             │
│              ┆            ┆ _git_r…      ┆ _git_r…      ┆ ___git_r…   ┆            ┆             │
│ Q9RFR9       ┆ A0A6Q8PGA3 ┆ /home/julian ┆ /home/julian ┆ /home/julia ┆ null       ┆ null        │
│              ┆            ┆ deanmoran/__ ┆ deanmoran/__ ┆ ndeanmoran/ ┆            ┆             │
│              ┆            ┆ _git_r…      ┆ _git_r…      ┆ ___git_r…   ┆            ┆             │
│ …            ┆ …          ┆ …            ┆ …            ┆ …           ┆ …          ┆ …           │
│ Q3Y0J6       ┆ O43598     ┆ /home/julian ┆ /home/julian ┆ /home/julia ┆ null       ┆ null        │
│              ┆            ┆ deanmoran/__ ┆ deanmoran/__ ┆ ndeanmoran/ ┆            ┆             │
│              ┆            ┆ _git_r…      ┆ _git_r…      ┆ ___git_r…   ┆            ┆             │
│ A0A829F2V1   ┆ O43598     ┆ /home/julian ┆ /home/julian ┆ /home/julia ┆ null       ┆ null        │
│              ┆            ┆ deanmoran/__ ┆ deanmoran/__ ┆ ndeanmoran/ ┆            ┆             │
│              ┆            ┆ _git_r…      ┆ _git_r…      ┆ ___git_r…   ┆            ┆             │
│ A0A6P1GFG5   ┆ Q17R31     ┆ /home/julian ┆ /home/julian ┆ /home/julia ┆ null       ┆ null        │
│              ┆            ┆ deanmoran/__ ┆ deanmoran/__ ┆ ndeanmoran/ ┆            ┆             │
│              ┆            ┆ _git_r…      ┆ _git_r…      ┆ ___git_r…   ┆            ┆             │
│ A0A0U1RHB2   ┆ A0A669KBB4 ┆ /home/julian ┆ /home/julian ┆ /home/julia ┆ null       ┆ null        │
│              ┆            ┆ deanmoran/__ ┆ deanmoran/__ ┆ ndeanmoran/ ┆            ┆             │
│              ┆            ┆ _git_r…      ┆ _git_r…      ┆ ___git_r…   ┆            ┆             │
│ X5EGL0       ┆ A0A669KBB4 ┆ /home/julian ┆ /home/julian ┆ /home/julia ┆ null       ┆ null        │
│              ┆            ┆ deanmoran/__ ┆ deanmoran/__ ┆ ndeanmoran/ ┆            ┆             │
│              ┆            ┆ _git_r…      ┆ _git_r…      ┆ ___git_r…   ┆            ┆             │
└──────────────┴────────────┴──────────────┴──────────────┴─────────────┴────────────┴─────────────┘

In [21]:
# ============================================================
#                             Out
# ============================================================

df_structures_aligned.write_csv(
    f"{args['out_dir']}/pymol_alignment_performance_{PM_ALIGN_METHOD}.tsv",
    separator="\t",
    include_header=True
)

In [24]:
rmsd, aligned_atoms = pymol_align_pair(
    pdb_query=df_structure_files[0, col_query_struct],
    pdb_target=df_structure_files[0, col_target_struct],
    pymol_align_method="super",
    out_path_structure="./tmp.pse"
)

INFO:__main__:For /home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A1Y6A5H7_AF.pdb,/home/juliandeanmoran/___git_repos/BISSH/results/test_pymol_align/alphafold_structures/A0A6Q8PGV8_AF.pdb, wrote alignment results to ./tmp.pse.