In [1]:
import logging
import os

from adjustText import adjust_text
from dotenv import load_dotenv
from gprofiler import GProfiler
from pathlib import Path
from typing import List, Tuple

import matplotlib.pyplot as plt
import pandas as pd
import polars as pl

# Env
load_dotenv("../.env")
INSTALL_PATH = os.environ["INSTALL_PATH"]

# Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s:%(name)s:%(message)s"
)
logger = logging.getLogger(__name__)

In [4]:
# ────────────────────────────────────────────────────────────
#      Args
# ────────────────────────────────────────────────────────────

DATA_FILE = f"{INSTALL_PATH}/results/explore_zorya/zorya_pymol_ann_n=300.tsv"
NEGLOG_EVALUE_COL = "neg_log(evalue_foldseek)"
PM_RMSD_COL = "PyMOL_RMSD"

In [3]:
# ────────────────────────────────────────────────────────────
#      In
# ────────────────────────────────────────────────────────────

df = pl.read_csv(
    DATA_FILE,
    separator="\t",
    has_header=True
)

df

shape: (300, 77)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ accession_ ┆ type  ┆ subtype    ┆ species    ┆ … ┆ protein_A ┆ PyMOL_ali ┆ PyMOL_RMS ┆ PyMOL_ali │
│ in_sys     ┆ ---   ┆ ---        ┆ ---        ┆   ┆ F_file    ┆ gned_file ┆ D         ┆ gned_atom │
│ ---        ┆ str   ┆ str        ┆ str        ┆   ┆ ---       ┆ Path      ┆ ---       ┆ s         │
│ str        ┆       ┆            ┆            ┆   ┆ str       ┆ ---       ┆ f64       ┆ ---       │
│            ┆       ┆            ┆            ┆   ┆           ┆ str       ┆           ┆ i64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ WP_0881344 ┆ Zorya ┆ Zorya_Type ┆ Vibrio     ┆ … ┆ /home/jul ┆ /home/jul ┆ 18.0215   ┆ 1734      │
│ 50.1       ┆       ┆ I          ┆ gazogenes  ┆   ┆ iandeanmo ┆ iandeanmo ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ ran/___gi ┆ ran/___gi ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ t_r…      ┆ t_r…      ┆           ┆           │
│ WP_0488843 ┆ Zorya ┆ Zorya_Type ┆ Aurantiaci ┆ … ┆ /home/jul ┆ /home/jul ┆ 24.708685 ┆ 567       │
│ 41.1       ┆       ┆ I          ┆ bacter     ┆   ┆ iandeanmo ┆ iandeanmo ┆           ┆           │
│            ┆       ┆            ┆ atlanticus ┆   ┆ ran/___gi ┆ ran/___gi ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ t_r…      ┆ t_r…      ┆           ┆           │
│ WP_0132208 ┆ Zorya ┆ Zorya_Type ┆ Nitrosococ ┆ … ┆ /home/jul ┆ /home/jul ┆ 55.255081 ┆ 1707      │
│ 29.1       ┆       ┆ I          ┆ cus        ┆   ┆ iandeanmo ┆ iandeanmo ┆           ┆           │
│            ┆       ┆            ┆ watsonii   ┆   ┆ ran/___gi ┆ ran/___gi ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ t_r…      ┆ t_r…      ┆           ┆           │
│ WP_1977438 ┆ Zorya ┆ Zorya_Type ┆ Candidatus ┆ … ┆ /home/jul ┆ /home/jul ┆ 53.588127 ┆ 2672      │
│ 02.1       ┆       ┆ II         ┆ Nitrosacid ┆   ┆ iandeanmo ┆ iandeanmo ┆           ┆           │
│            ┆       ┆            ┆ ococcus t… ┆   ┆ ran/___gi ┆ ran/___gi ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ t_r…      ┆ t_r…      ┆           ┆           │
│ WP_0132930 ┆ Zorya ┆ Zorya_Type ┆ Gallionell ┆ … ┆ /home/jul ┆ /home/jul ┆ 21.680252 ┆ 1781      │
│ 76.1       ┆       ┆ I          ┆ a capsifer ┆   ┆ iandeanmo ┆ iandeanmo ┆           ┆           │
│            ┆       ┆            ┆ riformans  ┆   ┆ ran/___gi ┆ ran/___gi ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ t_r…      ┆ t_r…      ┆           ┆           │
│ …          ┆ …     ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ WP_0153267 ┆ Zorya ┆ Zorya_Type ┆ Halobacter ┆ … ┆ /home/jul ┆ /home/jul ┆ 1.861909  ┆ 1104      │
│ 83.1       ┆       ┆ I          ┆ oides      ┆   ┆ iandeanmo ┆ iandeanmo ┆           ┆           │
│            ┆       ┆            ┆ halobius   ┆   ┆ ran/___gi ┆ ran/___gi ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ t_r…      ┆ t_r…      ┆           ┆           │
│ WP_2013401 ┆ Zorya ┆ Zorya_Type ┆ Isorropodo ┆ … ┆ /home/jul ┆ /home/jul ┆ 44.232727 ┆ 558       │
│ 71.1       ┆       ┆ II         ┆ n fossajap ┆   ┆ iandeanmo ┆ iandeanmo ┆           ┆           │
│            ┆       ┆            ┆ onicum     ┆   ┆ ran/___gi ┆ ran/___gi ┆           ┆           │
│            ┆       ┆            ┆ sym…       ┆   ┆ t_r…      ┆ t_r…      ┆           ┆           │
│ WP_1000243 ┆ Zorya ┆ Zorya_Type ┆ Fusobacter ┆ … ┆ /home/jul ┆ /home/jul ┆ 65.689865 ┆ 2999      │
│ 72.1       ┆       ┆ II         ┆ ium pseudo ┆   ┆ iandeanmo ┆ iandeanmo ┆           ┆           │
│            ┆       ┆            ┆ periodonti ┆   ┆ ran/___gi ┆ ran/___gi ┆           ┆           │
│            ┆       ┆            ┆ …          ┆   ┆ t_r…      ┆ t_r…      ┆           ┆           │
│ WP_0055981 ┆ Zorya ┆ Zorya_Type ┆ Actinobaci ┆ … ┆ /home/jul ┆ /home/jul ┆ 79.761932 ┆ 2489      │
│ 33.1       ┆       ┆ II         ┆ llus pleur ┆   ┆ iandeanmo ┆ iandeanmo ┆           ┆           │
│            ┆       ┆            ┆ opneumonia ┆   ┆ ran/___gi ┆ ran/___gi ┆           ┆           │
│            ┆       ┆            ┆ …          ┆   ┆ t_r…      ┆ t_r…      ┆           ┆           │
│ WP_1411696 ┆ Zorya ┆ Zorya_Type ┆ Janthinoba ┆ … ┆ /home/jul ┆ /home/jul ┆ 5.353301  ┆ 1410      │
│ 18.1       ┆       ┆ I          ┆ cterium    ┆   ┆ iandeanmo ┆ iandeanmo ┆           ┆           │
│            ┆       ┆            ┆ tructae    ┆   ┆ ran/___gi ┆ ran/___gi ┆           ┆           │
│            ┆       ┆            ┆            ┆   ┆ t_r…      ┆ t_r…      ┆           ┆           │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [9]:
# ────────────────────────────────────────────────────────────
#      Isolate point of interest (-30, 3.4)
# ────────────────────────────────────────────────────────────

poi_1 = df.filter(
    (pl.col(PM_RMSD_COL) <= 1.5) &
    (pl.col(NEGLOG_EVALUE_COL) >= 30)
)

poi_1_val = poi_1["PyMOL_aligned_filePath"].item()
print(str(poi_1_val))

/home/juliandeanmoran/___git_repos/BISSH/data_local/pymol_alignments/super/A0A0H4VDC2_X5D2E5_aligned.pse

In [16]:
# ────────────────────────────────────────────────────────────
#      Isolate point of interest (-26, 1.7)
# ────────────────────────────────────────────────────────────

poi_2 = df.filter(
    (pl.col(PM_RMSD_COL) <= 1.6) &
    (pl.col(PM_RMSD_COL) >= 1.5) &
    (pl.col(NEGLOG_EVALUE_COL) >= 26) &
    (pl.col(NEGLOG_EVALUE_COL) <= 28)
)

poi_2_val = poi_2["PyMOL_aligned_filePath"].item()
print(str(poi_2_val))

/home/juliandeanmoran/___git_repos/BISSH/data_local/pymol_alignments/super/A0A5B8XTL3_A0A0A0MSH9_aligned.pse

In [21]:
# ────────────────────────────────────────────────────────────
#      Isolate point of interest (-26, 1.7)
# ────────────────────────────────────────────────────────────

poi_3 = df.filter(
    (pl.col(PM_RMSD_COL) <= 1.4) &
    (pl.col(NEGLOG_EVALUE_COL) >= 12.2) &
    (pl.col(NEGLOG_EVALUE_COL) <= 13)
)

poi_3

poi_3_val = poi_3["PyMOL_aligned_filePath"].item()
print(str(poi_3_val))

/home/juliandeanmoran/___git_repos/BISSH/data_local/pymol_alignments/super/A0A4Y6RC84_B4DLS6_aligned.pse

In [26]:
# ────────────────────────────────────────────────────────────
#      Isolate point of interest (-30, 3.4)
# ────────────────────────────────────────────────────────────

poi_4 = df.filter(
    (pl.col(PM_RMSD_COL) >= 3.0) &
    (pl.col(NEGLOG_EVALUE_COL) >= 30)
)

poi_4

poi_4_val = poi_4["PyMOL_aligned_filePath"].item()
print(str(poi_4_val))

/home/juliandeanmoran/___git_repos/BISSH/data_local/pymol_alignments/super/A0A6L8M512_Q8N6J1_aligned.pse

In [29]:
poi_4["alnlen"]

shape: (1,)
Series: 'alnlen' [i64]
[
	553
]