In [1]:
import boto3
import io
import glob
import logging
import math
import os
import requests
import s3fs
import subprocess
import tempfile
import time

import matplotlib.pyplot as plt
import numpy as np
import polars as pl

from dotenv import load_dotenv
from pathlib import Path

# Env
load_dotenv("../.env", override=True)
REPO_ROOT = os.environ["INSTALL_PATH"]
MINIO_KEY = os.environ["MINIO_KEY"]
MINIO_SECRET = os.environ["MINIO_SECRET"]

# Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s:%(name)s:%(message)s"
)
logger = logging.getLogger(__name__)

In [4]:
# ============================================================
#       Args
# ============================================================

# File intake
FILE_GENE_LIST = f"{REPO_ROOT}/results/2026-10-07_for_c_marshal.tsv"
FILE_MARSHALL_AI = f"{REPO_ROOT}/data_sync/c_marshal_ai_panel_genes.xlsx"

# Dirs
OUT_DIR = f"{REPO_ROOT}/results"

In [9]:
# ============================================================
#       In -- gene list
# ============================================================

df_gene_list = pl.read_csv(
    FILE_GENE_LIST,
    separator="\t",
    has_header=True,
    infer_schema_length=None,
    null_values="NA"
)

df_gene_list

shape: (1_848, 77)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ defense_u ┆ defense_f ┆ defense_t ┆ human_uni ┆ … ┆ blastp_ss ┆ blastp_se ┆ blastp_ev ┆ blastp_b │
│ niprot_ac ┆ oldseek_r ┆ axId      ┆ prot_ac   ┆   ┆ tart      ┆ nd        ┆ alue      ┆ itscore  │
│ ---       ┆ epId      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ i64       ┆ str       ┆   ┆ i64       ┆ i64       ┆ f64       ┆ f64      │
│           ┆ str       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Q47ZY9    ┆ A0A2E5CU0 ┆ 167879    ┆ Q8IZH9    ┆ … ┆ 2         ┆ 176       ┆ 7.3000e-8 ┆ 227.0    │
│           ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆          │
│ A0A5B9E1W ┆ A0A7C2NS9 ┆ 582702    ┆ Q5QP19    ┆ … ┆ 1         ┆ 376       ┆ 5.3700e-1 ┆ 326.0    │
│ 6         ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆ 14        ┆          │
│ Q47ZY9    ┆ A0A2E5CU0 ┆ 167879    ┆ Q8IZH8    ┆ … ┆ 2         ┆ 135       ┆ 1.2400e-6 ┆ 180.0    │
│           ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆ 3         ┆          │
│ Q47ZY9    ┆ A0A2E5CU0 ┆ 167879    ┆ P30793    ┆ … ┆ 75        ┆ 249       ┆ 1.1400e-8 ┆ 227.0    │
│           ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆ 0         ┆          │
│ W5Y3L4    ┆ A0A6P6EXW ┆ 1224164   ┆ H0YG54    ┆ … ┆ 1         ┆ 166       ┆ 3.5600e-5 ┆ 161.0    │
│           ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆ 5         ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ A0A250IWT ┆ A0A2M7FZE ┆ 43        ┆ B7ZLM5    ┆ … ┆ 264       ┆ 542       ┆ 8.6700e-2 ┆ 79.7     │
│ 1         ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆ 0         ┆          │
│ L0D6C1    ┆ T1EGN3    ┆ 886293    ┆ Q14498    ┆ … ┆ 501       ┆ 515       ┆ 5.1       ┆ 14.2     │
│ A0A858SRR ┆ A0A1A7C61 ┆ 1891787   ┆ P20231    ┆ … ┆ 61        ┆ 76        ┆ 0.05      ┆ 21.2     │
│ 4         ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ B0N6M2    ┆ A0A523LUS ┆ 445974    ┆ A0A140T9X ┆ … ┆ 1         ┆ 179       ┆ 6.8100e-2 ┆ 84.7     │
│           ┆ 4         ┆           ┆ 9         ┆   ┆           ┆           ┆ 4         ┆          │
│ A0A517ZL3 ┆ A0A517SMJ ┆ 2527995   ┆ E9PC47    ┆ … ┆ 348       ┆ 518       ┆ 5.1000e-1 ┆ 64.7     │
│ 3         ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆ 5         ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
# ============================================================
#       In -- C Marshall panel
# ============================================================

df_marshall_panel = pl.concat([
    pl.read_excel(
        FILE_MARSHALL_AI,
        sheet_name=sheet
    ).with_columns(
        pl.lit(sheet).alias("source_sheet")
    )
    for sheet in ["RFS", "HLH", "AI", "AG"]
])

df_marshall_panel

shape: (53, 4)
┌──────────┬─────────────┬───────────────┬──────────────┐
│ Subpanel ┆ snpEff_gene ┆ snpEff_refseq ┆ source_sheet │
│ ---      ┆ ---         ┆ ---           ┆ ---          │
│ str      ┆ str         ┆ str           ┆ str          │
╞══════════╪═════════════╪═══════════════╪══════════════╡
│ RFS      ┆ MEFV        ┆ NM_000243.2   ┆ RFS          │
│ RFS      ┆ MVK         ┆ NM_000431.3   ┆ RFS          │
│ RFS      ┆ NLRP12      ┆ NM_144687.3   ┆ RFS          │
│ RFS      ┆ NLRP3       ┆ NM_004895.4   ┆ RFS          │
│ RFS      ┆ TNFRSF1A    ┆ NM_001065.3   ┆ RFS          │
│ …        ┆ …           ┆ …             ┆ …            │
│ AG       ┆ RNASEH2A    ┆ NM_006397.2   ┆ AG           │
│ AG       ┆ RNASEH2B    ┆ NM_024570.3   ┆ AG           │
│ AG       ┆ RNASEH2C    ┆ NM_032193.3   ┆ AG           │
│ AG       ┆ SAMHD1      ┆ NM_015474.3   ┆ AG           │
│ AG       ┆ TREX1       ┆ NM_033629.4   ┆ AG           │
└──────────┴─────────────┴───────────────┴──────────────┘