### Get gene list from composite scoring results
### Julian Moran
### 2026-09-02

In [24]:
import boto3
import glob
import logging
import math
import os
import requests
import s3fs
import time

import matplotlib.pyplot as plt
import numpy as np
import polars as pl

from dotenv import load_dotenv
from pathlib import Path

# Env
load_dotenv("../.env", override=True)
REPO_ROOT = os.environ["INSTALL_PATH"]
MINIO_KEY = os.environ["MINIO_KEY"]
MINIO_SECRET = os.environ["MINIO_SECRET"]

# Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s:%(name)s:%(message)s"
)
logger = logging.getLogger(__name__)

In [23]:
# ============================================================
#       Args
# ============================================================

# Notebook variables
COMP_THRESHOLD = 0.825

# File intake
BUCKET = "iei-project"
PREFIX_GOLD = "03_gold/defense_finder/"
PREFIX_SILVER = "02_silver/defense_finder/"
FILE_COMPOSITE = "composite_score.parquet/part-00000-ac5574c4-cf3c-48a9-98b6-077d4db394f9-c000.snappy.parquet"
FILE_FINAL_OUTPUT = "final_output_spark.parquet/part-00000-bb778272-db05-479f-a79a-2d18e89fe363-c000.snappy.parquet"

FILE_IMMPORT = f"{REPO_ROOT}/data_sync/ImmPort_all_gene_lists.gmt"

# Dirs
OUT_DIR_PLOT = f"{REPO_ROOT}/vis/plots"

# Check live objects in MinIO silver
client = boto3.client(
    "s3",
    endpoint_url="http://eagle.tcag.ca:9000",
    aws_access_key_id=MINIO_SECRET,
    aws_secret_access_key=MINIO_KEY,
)
response = client.list_objects_v2(
    Bucket=BUCKET,
    Prefix=PREFIX_GOLD
)
live_objects = [
    obj["Key"]
    for obj in response.get("Contents", [])
]
live_objects

['03_gold/defense_finder/composite_score.parquet/_SUCCESS',
 '03_gold/defense_finder/composite_score.parquet/part-00000-ac5574c4-cf3c-48a9-98b6-077d4db394f9-c000.snappy.parquet',
 '03_gold/defense_finder/defense_human_domain_annotated.parquet',
 '03_gold/defense_finder/final_output_spark.parquet/_SUCCESS',
 '03_gold/defense_finder/final_output_spark.parquet/part-00000-bb778272-db05-479f-a79a-2d18e89fe363-c000.snappy.parquet',
 '03_gold/defense_finder/griid_gene_subset.parquet',
 '03_gold/defense_finder/human_bacteria_structural_analogs_enriched.parquet',
 '03_gold/defense_finder/human_bacteria_structural_analogs_with_scores.parquet/_SUCCESS',
 '03_gold/defense_finder/human_bacteria_structural_analogs_with_scores.parquet/part-00000-275fe83c-840b-476e-bf63-c47165847863-c000.snappy.parquet']

In [27]:
# ============================================================
#       In
# ============================================================

df_final_output = pl.read_parquet(
    f"s3://{BUCKET}/{PREFIX_GOLD}{FILE_FINAL_OUTPUT}",
    storage_options={
        "aws_endpoint_url": "http://eagle.tcag.ca:9000",
        "aws_access_key_id": MINIO_SECRET,
        "aws_secret_access_key": MINIO_KEY,
    }
)

df_comp_score = pl.read_parquet(
    f"s3://{BUCKET}/{PREFIX_GOLD}{FILE_COMPOSITE}",
    storage_options={
        "aws_endpoint_url": "http://eagle.tcag.ca:9000",
        "aws_access_key_id": MINIO_SECRET,
        "aws_secret_access_key": MINIO_KEY,
    }
)

data_immport = {}
with Path(FILE_IMMPORT).open() as f:
    for line in f:
        fields = line.rstrip("\n").split("\t")
        data_immport[fields[0]] = fields[2:]

df_comp_score

shape: (1_097_291, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ defense_u ┆ human_ent ┆ composite ┆ foldseek_ ┆ … ┆ tm_score_ ┆ tm_score_ ┆ plddt_hum ┆ plddt_ba │
│ niprot_ac ┆ ryId      ┆ _score    ┆ evalue    ┆   ┆ human     ┆ bacteria  ┆ an        ┆ cteria   │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ f32       ┆ f32       ┆ f32       ┆ f32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ A0A5C5QGP ┆ A0A024R9P ┆ 0.2646    ┆ 0.000087  ┆ … ┆ null      ┆ null      ┆ null      ┆ 83.48000 │
│ 9         ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ A0A2R3IRC ┆ A0A0D9SF9 ┆ 0.8315    ┆ 1.2070e-7 ┆ … ┆ 0.8169    ┆ 0.1028    ┆ 83.199997 ┆ 77.44999 │
│ 4         ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ A0A4D8PF3 ┆ A0A140VK7 ┆ 0.2883    ┆ 0.003094  ┆ … ┆ 0.2908    ┆ 0.1539    ┆ 80.290001 ┆ 83.05000 │
│ 3         ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ A0A7S9D46 ┆ A0A140VK7 ┆ 0.8986    ┆ 5.6920e-1 ┆ … ┆ 0.535     ┆ 0.7678    ┆ 80.290001 ┆ 89.62999 │
│ 1         ┆ 0         ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆ 7        │
│ A0A2K9LJD ┆ A0A1B0GVC ┆ 0.2795    ┆ 0.007862  ┆ … ┆ 0.2428    ┆ 0.29      ┆ 67.610001 ┆ 91.37999 │
│ 6         ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ A0A1D7XM1 ┆ Q9H4E3    ┆ 0.6409    ┆ 0.000001  ┆ … ┆ 0.6556    ┆ 0.327     ┆ 84.879997 ┆ 82.36000 │
│ 3         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ A0A7D6CQE ┆ Q9H4E3    ┆ 0.5814    ┆ 0.000001  ┆ … ┆ 0.6733    ┆ 0.3337    ┆ 84.879997 ┆ 75.23000 │
│ 3         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ A0A5P3ALB ┆ Q9H4E3    ┆ 0.8713    ┆ 1.2930e-1 ┆ … ┆ 0.739     ┆ 0.4786    ┆ 84.879997 ┆ 89.01999 │
│ 7         ┆           ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆ 7        │
│ A0A0U0WN1 ┆ Q9H4E3    ┆ 0.7745    ┆ 2.0010e-1 ┆ … ┆ 0.6593    ┆ 0.3919    ┆ 84.879997 ┆ 83.30000 │
│ 8         ┆           ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆ 3        │
│ A0A2I5KM7 ┆ V9GXZ4    ┆ 0.8666    ┆ 3.4560e-1 ┆ … ┆ 0.2633    ┆ 0.3695    ┆ 73.169998 ┆ 80.98999 │
│ 4         ┆           ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆ 8        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [15]:
col = "Gene Names (primary)"
n = df_final_output.height
non_null = df_final_output[col].is_not_null().sum()
p_w_gene_name = round(non_null / n, 2)

logger.info(f"Pipeline output with annotated gene names {p_w_gene_name}")
logger.info(f"Missing {round(1 - p_w_gene_name, 2)} likely due to accessions being only in UniParc")

df_final_output

INFO:__main__:Pipeline output with annotated gene names 0.67
INFO:__main__:Missing 0.33 likely due to accessions being only in UniParc

shape: (1_097_291, 34)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ defense_u ┆ cluster_r ┆ defense_t ┆ human_ent ┆ … ┆ RefSeq    ┆ human_dom ┆ defense_t ┆ defense_ │
│ niprot_ac ┆ epId      ┆ axId      ┆ ryId      ┆   ┆ ---       ┆ ains      ┆ ype       ┆ subtype  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆           ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ D5H7G1    ┆ A0A2P4VLT ┆ 761659    ┆ A0A024QZ2 ┆ … ┆ null      ┆ null      ┆ Gao_TerY  ┆ Gao_TerY │
│           ┆ 1         ┆           ┆ 0         ┆   ┆           ┆           ┆           ┆          │
│ A0A0S2KJ8 ┆ A0A858BYG ┆ 76123     ┆ A0A024R74 ┆ … ┆ null      ┆ null      ┆ CBASS     ┆ CBASS_II │
│ 9         ┆ 8         ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆          │
│ A0A1L3LSP ┆ A0A858BYG ┆ 194963    ┆ A0A024R74 ┆ … ┆ null      ┆ null      ┆ CBASS     ┆ CBASS_I  │
│ 8         ┆ 8         ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆          │
│ A0A2G9LHY ┆ A0A858BYG ┆ 573       ┆ A0A024R74 ┆ … ┆ null      ┆ null      ┆ CBASS     ┆ CBASS_II │
│ 5         ┆ 8         ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆          │
│ A0A2K9Z6V ┆ A0A858BYG ┆ 384       ┆ A0A024R74 ┆ … ┆ null      ┆ null      ┆ CBASS     ┆ CBASS_I  │
│ 0         ┆ 8         ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ A0A5P8W2P ┆ A0A3S9MKD ┆ 2653204   ┆ X5D2R5    ┆ … ┆ NP_079428 ┆ null      ┆ PsyrTA    ┆ PsyrTA   │
│ 0         ┆ 2         ┆           ┆           ┆   ┆ .2;       ┆           ┆           ┆          │
│ A7HKC7    ┆ A0A3S9MKD ┆ 381764    ┆ X5D2R5    ┆ … ┆ NP_079428 ┆ null      ┆ PsyrTA    ┆ PsyrTA   │
│           ┆ 2         ┆           ┆           ┆   ┆ .2;       ┆           ┆           ┆          │
│ E4TBU2    ┆ A0A3S9MKD ┆ 693978    ┆ X5D2R5    ┆ … ┆ NP_079428 ┆ null      ┆ ShosTA    ┆ ShosTA   │
│           ┆ 2         ┆           ┆           ┆   ┆ .2;       ┆           ┆           ┆          │
│ J9R5B4    ┆ A0A3S9MKD ┆ 1228997   ┆ X5D2R5    ┆ … ┆ NP_079428 ┆ null      ┆ ShosTA    ┆ ShosTA   │
│           ┆ 2         ┆           ┆           ┆   ┆ .2;       ┆           ┆           ┆          │
│ E3FIT8    ┆ A0A6N2D3T ┆ 378806    ┆ X5D7J4    ┆ … ┆ null      ┆ DOMAIN    ┆ Pycsar    ┆ Pycsar   │
│           ┆ 8         ┆           ┆           ┆   ┆           ┆ 125..170; ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ /note="UB ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ A"; …     ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [29]:
logger.info(f"N ImmPort immune system pathways: {len(data_immport)}")
data_immport

INFO:__main__:N ImmPort immune system pathways: 153

{'Activation of innate immune response': ['AIM2',
  'ALPK1',
  'AP3B1',
  'BCL10',
  'BECN1',
  'BTK',
  'CASP1',
  'CASP6',
  'CD14',
  'CD274',
  'CD300LF',
  'CGAS',
  'CHUK',
  'CLEC4E',
  'CLEC6A',
  'CLEC7A',
  'CLPB',
  'COLEC10',
  'COLEC11',
  'COLEC12',
  'CREBBP',
  'CTSS',
  'CYLD',
  'DHX58',
  'ECSIT',
  'EP300',
  'EPG5',
  'FCN1',
  'FCN2',
  'FCN3',
  'FFAR2',
  'FOSL1',
  'FYN',
  'GBP2',
  'GBP5',
  'HAVCR2',
  'HCK',
  'HEXIM1',
  'HMGB1',
  'HSP90AA1',
  'HSPD1',
  'IFI16',
  'IFIH1',
  'IKBKB',
  'INAVA',
  'IPO5',
  'IRAK1',
  'IRAK2',
  'IRAK3',
  'IRAK4',
  'IRF3',
  'IRF7',
  'IRGM',
  'ITCH',
  'KIR2DS2',
  'KLRC1',
  'KLRC2',
  'KLRC3',
  'KLRC4',
  'KLRC4-KLRK1',
  'KLRD1',
  'KLRK1',
  'LACC1',
  'LBP',
  'LILRA2',
  'LRRC19',
  'LSM14A',
  'LY96',
  'LYN',
  'MAP2K6',
  'MAP3K7',
  'MAPKAPK2',
  'MAPKAPK3',
  'MATR3',
  'MAVS',
  'MBL2',
  'MEFV',
  'MNDA',
  'MYD88',
  'NAGLU',
  'NAIP',
  'NFKBIA',
  'NFKBIZ',
  'NLRC4',
  'NLRP1',
  'NLRP10',
  'NLRP3',
  'NMI',
  'NOD1',
  'NOD2',
  'NONO',
  'NR1H4',
  'OAS1',
  'OAS3',
  'OTULIN',
  'PAK1',
  'PAK2',
  'PAK3',
  'PHB1',
  'PHB2',
  'PIK3AP1',
  'PLCG2',
  'PQBP1',
  'PRKCE',
  'PRKDC',
  'PSPC1',
  'PYCARD',
  'PYHIN1',
  'RAB11FIP2',
  'RBM14',
  'REG3G',
  'RELA',
  'RFTN1',
  'RIGI',
  'RIPK2',
  'RNF135',
  'RNF144A',
  'RNF34',
  'RPS6KA3',
  'S100A14',
  'SCIMP',
  'SFPQ',
  'SIN3A',
  'SRC',
  'STING1',
  'SYK',
  'TBK1',
  'TICAM1',
  'TICAM2',
  'TIFA',
  'TIFAB',
  'TIRAP',
  'TLR1',
  'TLR10',
  'TLR2',
  'TLR3',
  'TLR4',
  'TLR5',
  'TLR6',
  'TLR7',
  'TLR8',
  'TLR9',
  'TMEM126A',
  'TNF',
  'TNFAIP3',
  'TNIP1',
  'TNIP2',
  'TNIP3',
  'TOMM70',
  'TRAF3',
  'TRAF3IP3',
  'TRAF6',
  'TRIL',
  'TRIM25',
  'TRIM5',
  'TYROBP',
  'UNC93B1',
  'XIAP',
  'XRCC5',
  'XRCC6',
  'YWHAE',
  'ZBP1',
  'ZCCHC3',
  'ZNFX1'],
 'Adaptive immune memory response': ['CD27', 'CD70', 'EBAG9'],
 'Adaptive immune memory response involving T cells and B cells': ['CD27',
  'CD70',
  'EBAG9'],
 'Adaptive immune response based on somatic recombination of immune receptors built from immunoglobulin superfamily domains': ['ADA',
  'ADAM17',
  'AIRE',
  'B2M',
  'BACH2',
  'BCL10',
  'BCL3',
  'BCL6',
  'BTN3A2',
  'BTN3A3',
  'C4BPA',
  'CARD9',
  'CD19',
  'CD27',
  'CD40',
  'CD46',
  'CD70',
  'CD74',
  'CD81',
  'CD8A',
  'CLEC4G',
  'CR1',
  'CR1L',
  'CR2',
  'CSF2RB',
  'CTSC',
  'CTSH',
  'CXCL13',
  'EBAG9',
  'EBI3',
  'EMP2',
  'EXO1',
  'FCER1A',
  'FCER1G',
  'FCGR1A',
  'FCGR1BP',
  'FCGR2A',
  'FCGR2B',
  'FCGR2C',
  'FCGR3A',
  'FCGR3B',
  'FCMR',
  'FOXP3',
  'GNL1',
  'GZMM',
  'HLA-A',
  'HLA-DRB1',
  'HLA-G',
  'HPRT1',
  'HRAS',
  'IGHD',
  'IGHG1',
  'IGHV1-18',
  'IGHV1-24',
  'IGHV1-3',
  'IGHV1-38-4',
  'IGHV1-45',
  'IGHV1-58',
  'IGHV1-69',
  'IGHV1-69-2',
  'IGHV1-69D',
  'IGHV1-8',
  'IGHV2-26',
  'IGHV2-5',
  'IGHV2-70',
  'IGHV2-70D',
  'IGHV3-11',
  'IGHV3-13',
  'IGHV3-15',
  'IGHV3-16',
  'IGHV3-20',
  'IGHV3-21',
  'IGHV3-23',
  'IGHV3-30',
  'IGHV3-30-3',
  'IGHV3-30-5',
  'IGHV3-33',
  'IGHV3-35',
  'IGHV3-38',
  'IGHV3-38-3',
  'IGHV3-43',
  'IGHV3-43D',
  'IGHV3-48',
  'IGHV3-49',
  'IGHV3-53',
  'IGHV3-64',
  'IGHV3-64D',
  'IGHV3-66',
  'IGHV3-7',
  'IGHV3-72',
  'IGHV3-73',
  'IGHV3-74',
  'IGHV3-9',
  'IGHV4-28',
  'IGHV4-30-4',
  'IGHV4-31',
  'IGHV4-34',
  'IGHV4-38-2',
  'IGHV4-39',
  'IGHV4-4',
  'IGHV4-59',
  'IGHV4-61',
  'IGHV5-10-1',
  'IGHV5-51',
  'IGHV6-1',
  'IGHV7-4-1',
  'IGHV7-81',
  'IGHV8-51-1',
  'IGKC',
  'IGLC1',
  'IGLC2',
  'IGLC3',
  'IGLC6',
  'IGLC7',
  'IGLL1',
  'IGLL5',
  'IL12B',
  'IL13RA2',
  'IL17RA',
  'IL18',
  'IL18BP',
  'IL21R',
  'IL2RB',
  'IL4R',
  'IL7R',
  'IL9',
  'IL9R',
  'INPP5D',
  'IRF7',
  'JAG1',
  'KLHL6',
  'MEF2C',
  'MICA',
  'MPL',
  'MSH2',
  'MYD88',
  'MYO1G',
  'NFKB2',
  'NFKBIZ',
  'NOTCH1',
  'P2RX7',
  'PHB1',
  'PPP3CB',
  'PRF1',
  'PRKCD',
  'PSG9',
  'SCART1',
  'SLA2',
  'STAT3',
  'TAP2',
  'TCIRG1',
  'TGFB1',
  'TLR4',
  'TLR8',
  'TNFSF13B',
  'TRA',
  'TRAF3IP2',
  'TRAF6',
  'TRB',
  'TREX1',
  'UNC13D',
  'ZP3'],
 'Advanced glycosylation endproduct receptor signaling': ['AGER',
  'APP',
  'CAPZA1',
  'CAPZA2',
  'DDOST',
  'HMGB1',
  'LGALS3',
  'MAPK1',
  'MAPK3',
  'PRKCSH',
  'S100A12',
  'S100B',
  'SAA1'],
 'Alpha-beta T cell activation': ['ABL1',
  'ADA',
  'ANXA1',
  'ARMC5',
  'ASCL2',
  'ATF2',
  'ATP7A',
  'BATF',
  'BCL11B',
  'BCL3',
  'BCL6',
  'BRAF',
  'CARD11',
  'CBLB',
  'CD247',
  'CD28',
  'CD3D',
  'CD3E',
  'CD3G',
  'CD83',
  'CDH26',
  'CLEC2B',
  'CLEC4A',
  'CLEC4G',
  'DOCK2',
  'ELF4',
  'ENTPD7',
  'EOMES',
  'FOSL2',
  'FOXP1',
  'FOXP3',
  'FUT7',
  'GATA3',
  'GLI3',
  'GPR18',
  'GPR183',
  'HLA-A',
  'HLA-E',
  'HLX',
  'HMGB1',
  'IL12B',
  'IL15',
  'IL18R1',
  'IL21',
  'IL2RG',
  'IL4R',
  'IL6',
  'INS',
  'IRF1',
  'ITCH',
  'ITK',
  'KLRF1',
  'KMT2A',
  'LEF1',
  'MEN1',
  'MYB',
  'NDFIP1',
  'NFKBIZ',
  'NKG7',
  'NKX2-3',
  'PDP2',
  'PLA2G2D',
  'PRKCQ',
  'PRR7',
  'PSMB11',
  'PTGER4',
  'PTPRC',
  'RC3H1',
  'RC3H2',
  'RELB',
  'RIPK2',
  'RORA',
  'RORC',
  'RPL22',
  'RSAD2',
  'SASH3',
  'SEMA4A',
  'SHH',
  'STAT4',
  'STOML2',
  'TCIRG1',
  'TMEM98',
  'TNFSF4',
  'TNFSF8',
  'TRAC',
  'TRBC1',
  'TRBC2',
  'WDFY4',
  'ZBTB7B'],
 'Alpha-protein kinase 1 signaling pathway': ['ALPK1',
  'MAP3K7',
  'RPS27A',
  'TAB1',
  'TAB2',
  'TAB3',
  'TIFA',
  'TRAF6',
  'UBA52',
  'UBB',
  'UBC'],
 'Antibacterial innate immune response': ['DEFB136',
  'MARCHF2',
  'MIRLET7B',
  'MPEG1',
  'NFKB1',
  'NOD2',
  'RASGRP4',
  'SLC15A2',
  'TFEB',
  'UMOD'],
 'Antibody-dependent cellular cytotoxicity': ['FCGR1A',
  'FCGR1BP',
  'FCGR2A',
  'FCGR2B',
  'FCGR2C',
  'FCGR3A',
  'FCGR3B',
  'IGHG1'],
 'Antifungal innate immune response': ['BCL10',
  'CARD9',
  'CLEC4A',
  'CLEC4C',
  'CLEC4D',
  'CLEC4E',
  'CLEC6A',
  'CLEC7A',
  'CX3CR1',
  'DEFB106A',
  'DEFB106B',
  'DEFB114',
  'DEFB119',
  'DEFB136',
  'DEFB4A',
  'PLCG2',
  'RARRES2',
  'RNASE8'],
 'Antigen processing and presentation': ['ACE',
  'AP3B1',
  'AP3D1',
  'ARL8B',
  'ATG5',
  'B2M',
  'CD1A',
  'CD1B',
  'CD1C',
  'CD1D',
  'CD1E',
  'CD209',
  'CD74',
  'CD8A',
  'CLEC4A',
  'CLEC4M',
  'CTSD',
  'CTSE',
  'CTSF',
  'CTSH',
  'CTSL',
  'CTSS',
  'CTSV',
  'DNM2',
  'ERAP1',
  'ERAP2',
  'EXT1',
  'FCER1G',
  'FCER2',
  'FCGR1A',
  'FCGR2B',
  'GBA1',
  'HFE',
  'HLA-A',
  'HLA-B',
  'HLA-C',
  'HLA-DMA',
  'HLA-DMB',
  'HLA-DOA',
  'HLA-DOB',
  'HLA-DPA1',
  'HLA-DPB1',
  'HLA-DQA1',
  'HLA-DQA2',
  'HLA-DQB1',
  'HLA-DQB2',
  'HLA-DRA',
  'HLA-DRB1',
  'HLA-DRB3',
  'HLA-DRB4',
  'HLA-DRB5',
  'HLA-E',
  'HLA-F',
  'HLA-G',
  'HLA-H',
  'ICAM1',
  'IDE',
  'IFI30',
  'IKBKB',
  'KDM5D',
  'LGMN',
  'LNPEP',
  'MARCHF1',
  'MARCHF8',
  'MFSD6',
  'MICA',
  'MICB',
  'MPEG1',
  'MR1',
  'PIKFYVE',
  'PSMB8',
  'PSME1',
  'RAB10',
  'RAB27A',
  'RAB32',
  'RAB33A',
  'RAB34',
  'RAB35',
  'RAB3B',
  'RAB3C',
  'RAB4A',
  'RAB5B',
  'RAB6A',
  'RAB8B',
  'RAET1E',
  'RAET1G',
  'RAET1L',
  'RELB',
  'RFTN1',
  'SAR1B',
  'SLC11A1',
  'TAP1',
  'TAP2',
  'TAPBP',
  'TRAF6',
  'TREX1',
  'ULBP1',
  'ULBP2',
  'ULBP3',
  'UNC93B1',
  'WDFY4'],
 'Antigen receptor-mediated signaling pathway': ['ABL1',
  'ADA',
  'BANK1',
  'BAX',
  'BCAR1',
  'BCL10',
  'BCL2',
  'BLK',
  'BLNK',
  'BMX',
  'BRAF',
  'BTK',
  'BTN1A1',
  'BTN2A1',
  'BTN2A2',
  'BTN2A3P',
  'BTN3A1',
  'BTN3A2',
  'BTN3A3',
  'BTNL10P',
  'BTNL2',
  'BTNL3',
  'BTNL8',
  'BTNL9',
  'CACNB3',
  'CACNB4',
  'CBLB',
  'CD19',
  'CD247',
  'CD276',
  'CD28',
  'CD2AP',
  'CD38',
  'CD3D',
  'CD3E',
  'CD3G',
  'CD79A',
  'CD79B',
  'CD8A',
  'CD8B',
  'CRKL',
  'CSK',
  'CTLA4',
  'DENND1B',
  'EIF2B1',
  'EIF2B2',
  'EIF2B3',
  'EIF2B4',
  'EIF2B5',
  'ERMAP',
  'FCHO1',
  'FOSL2',
  'FOXP3',
  'FYB1',
  'FYB2',
  'FYN',
  'GATA3',
  'GRB2',
  'HHLA2',
  'HLA-A',
  'HLA-DPB1',
  'HLA-DQB1',
  'HLA-DRB1',
  'HLA-DRB3',
  'HRAS',
  'ICOSLG',
  'IGHA1',
  'IGHA2',
  'IGHD',
  'IGHE',
  'IGHG1',
  'IGHG2',
  'IGHG3',
  'IGHG4',
  'IGHM',
  'IGKC',
  'IGLC1',
  'IGLC3',
  'IGLC6',
  'IGLC7',
  'IKBKB',
  'IKBKG',
  'INPP5D',
  'ITK',
  'KHDRBS1',
  'KLHL6',
  'LAT',
  'LAT2',
  'LAX1',
  'LCK',
  'LCP2',
  'LIME1',
  'LYN',
  'MALT1',
  'MAP3K7',
  'MAPK1',
  'MEF2C',
  'MNDA',
  'MOG',
  'MS4A1',
  'NCKAP1L',
  'NFAM1',
  'NFATC2',
  'NFKB1',
  'NFKBIA',
  'NFKBID',
  'NFKBIZ',
  'PDE4B',
  'PDE4D',
  'PIK3CA',
  'PIK3CD',
  'PLCG1',
  'PLCG2',
  'PLEKHA1',
  'PRAM1',
  'PRKCB',
  'PRKD2',
  'PSEN1',
  'PTPN22',
  'PTPN6',
  'PTPRC',
  'PTPRJ',
  'RBCK1',
  'RC3H1',
  'RC3H2',
  'RFTN1',
  'RIPK2',
  'RNF31',
  'SH2B2',
  'SHB',
  'SKAP1',
  'SLA2',
  'SLC39A6',
  'SOS1',
  'SPG21',
  'SPPL3',
  'STK11',
  'STOML2',
  'SYK',
  'TEC',
  'THEMIS',
  'THEMIS2',
  'THY1',
  'TMIGD2',
  'TNFRSF21',
  'TRAC',
  'TRAF6',
  'TRBC1',
  'TRBC2',
  'TRDC',
  'TRGC1',
  'TRGC2',
  'TXK',
  'UBE2N',
  'VAV3',
  'VTCN1',
  'WNK1',
  'ZAP70',
  'ZC3H12A'],
 'Antimicrobial humoral response': ['ANG',
  'AZU1',
  'BCL3',
  'BPIFA1',
  'CAMP',
  'CCL1',
  'CCL11',
  'CCL13',
  'CCL14',
  'CCL15',
  'CCL16',
  'CCL17',
  'CCL18',
  'CCL19',
  'CCL2',
  'CCL20',
  'CCL21',
  'CCL22',
  'CCL23',
  'CCL24',
  'CCL25',
  'CCL26',
  'CCL3',
  'CCL3L1',
  'CCL3L3',
  'CCL4',
  'CCL4L1',
  'CCL5',
  'CCL7',
  'CCL8',
  'COLEC11',
  'CST9',
  'CST9L',
  'CST9LP1',
  'CTSG',
  'CX3CL1',
  'CXCL1',
  'CXCL10',
  'CXCL11',
  'CXCL13',
  'CXCL14',
  'CXCL2',
  'CXCL3',
  'CXCL5',
  'CXCL6',
  'CXCL8',
  'CXCL9',
  'DEFA1',
  'DEFA1B',
  'DEFA3',
  'DEFA4',
  'DEFA5',
  'DEFA6',
  'DEFB1',
  'DEFB118',
  'DEFB126',
  'DEFB127',
  'DEFB4A',
  'DMBT1',
  'F2',
  'FAM3A',
  'FAU',
  'FGA',
  'FGB',
  'GALP',
  'GAPDH',
  'GNLY',
  'H2BC10',
  'H2BC11',
  'H2BC12',
  'H2BC12L',
  'H2BC21',
  'H2BC4',
  'H2BC6',
  'H2BC7',
  'H2BC8',
  'HLA-A',
  'HLA-E',
  'HMGN2',
  'HRG',
  'IGHA1',
  'IGHA2',
  'IGHE',
  'IGHG1',
  'IGHG2',
  'IGHG3',
  'IGHG4',
  'IGHM',
  'IGKV3-20',
  'IL36RN',
  'JCHAIN',
  'KRT6A',
  'LEAP2',
  'LTF',
  'LYZ',
  'MUC7',
  'NCR3LG1',
  'PF4',
  'PF4V1',
  'PGLYRP1',
  'PGLYRP3',
  'PGLYRP4',
  'PI3',
  'PLA2G1B',
  'PLA2G6',
  'PPBP',
  'PRSS2',
  'PRSS3',
  'PRTN3',
  'RARRES2',
  'REG1A',
  'REG1B',
  'REG3A',
  'REG3G',
  'RNASE3',
  'RNASE4',
  'RNASE6',
  'RNASE7',
  'ROMO1',
  'RPL30',
  'RPL39',
  'RPS19',
  'S100A12',
  'S100A7',
  'S100A9',
  'SEMG1',
  'SEMG2',
  'SLC11A1',
  'SLPI',
  'SPAG11A',
  'SPAG11B',
  'SPON2',
  'SPRR2A',
  'TF',
  'TSLP',
  'WFDC10A',
  'WFDC10B',
  'WFDC11',
  'WFDC12',
  'WFDC13',
  'WFDC2',
  'WFDC3',
  'WFDC5',
  'WFDC9',
  'XCL1',
  'XCL2'],
 'Antimicrobial peptides': ['ART1',
  'ATOX1',
  'ATP7A',
  'BPI',
  'BPIFA1',
  'BPIFA2',
  'BPIFB1',
  'BPIFB2',
  'BPIFB4',
  'BPIFB6',
  'CAMP',
  'CCR2',
  'CCR6',
  'CD4',
  'CHGA',
  'CLU',
  'CTSG',
  'DCD',
  'DEFA1',
  'DEFA1B',
  'DEFA3',
  'DEFA4',
  'DEFA5',
  'DEFA6',
  'DEFB1',
  'DEFB103A',
  'DEFB103B',
  'DEFB104A',
  'DEFB104B',
  'DEFB105A',
  'DEFB105B',
  'DEFB106A',
  'DEFB106B',
  'DEFB107A',
  'DEFB107B',
  'DEFB108B',
  'DEFB110',
  'DEFB113',
  'DEFB114',
  'DEFB115',
  'DEFB116',
  'DEFB118',
  'DEFB119',
  'DEFB121',
  'DEFB123',
  'DEFB124',
  'DEFB125',
  'DEFB126',
  'DEFB127',
  'DEFB128',
  'DEFB129',
  'DEFB130A',
  'DEFB130B',
  'DEFB131A',
  'DEFB132',
  'DEFB134',
  'DEFB135',
  'DEFB136',
  'DEFB4A',
  'DEFB4B',
  'ELANE',
  'EPPIN',
  'EPPIN-WFDC6',
  'GNLY',
  'HTN1',
  'HTN3',
  'ITLN1',
  'LCN2',
  'LEAP2',
  'LTF',
  'LYZ',
  'PDZD11',
  'PGLYRP1',
  'PGLYRP2',
  'PGLYRP3',
  'PGLYRP4',
  'PI3',
  'PLA2G2A',
  'PRSS2',
  'PRSS3',
  'PRTN3',
  'REG3A',
  'REG3G',
  'RNASE3',
  'RNASE6',
  'RNASE7',
  'RNASE8',
  'S100A7',
  'S100A7A',
  'S100A8',
  'S100A9',
  'SEMG1',
  'SLC11A1',
  'TLR1',
  'TLR2'],
 'Antiviral innate immune response': ['AKAP1',
  'ATAD3A',
  'CARD8',
  'CLPB',
  'CXCL10',
  'DHX15',
  'DHX16',
  'DHX58',
  'DUS2',
  'EIF2AK2',
  'HCFC2',
  'IFIH1',
  'IFIT1',
  'IFIT2',
  'IFIT3',
  'MARCHF2',
  'MAVS',
  'MBL2',
  'MORC3',
  'MX1',
  'NCK1',
  'NLRP1',
  'NLRP6',
  'NMB',
  'NMBR',
  'OAS1',
  'PDE12',
  'PHB1',
  'PHB2',
  'PRKRA',
  'RELA',
  'RIGI',
  'RNF135',
  'RPSA',
  'SENP7',
  'SMARCA5',
  'STING1',
  'TBK1',
  'TNF',
  'TRAF6',
  'TRIM25',
  'TRIM31',
  'TRIM6',
  'TRIM65',
  'TRIM7',
  'UAP1',
  'UBE2N',
  'UBE2W',
  'USP18',
  'USP20',
  'USP44',
  'ZBP1',
  'ZDHHC1',
  'ZDHHC11'],
 'Antiviral mechanism by IFN-stimulated genes': ['AAAS',
  'ABCE1',
  'ADAR',
  'ARIH1',
  'BECN1',
  'CDK1',
  'CENPS',
  'CENPS-CORT',
  'CENPX',
  'CHUK',
  'DHX9',
  'DNAJC3',
  'DUS2',
  'EIF2AK2',
  'EIF2S1',
  'EIF2S2',
  'EIF2S3',
  'EIF4A1',
  'EIF4A2',
  'EIF4A3',
  'EIF4E',
  'EIF4E2',
  'EIF4E3',
  'EIF4G1',
  'EIF4G2',
  'EIF4G3',
  'FAAP100',
  'FAAP20',
  'FAAP24',
  'FANCA',
  'FANCB',
  'FANCC',
  'FANCE',
  'FANCF',
  'FANCG',
  'FANCL',
  'FANCM',
  'FLNA',
  'FLNB',
  'HERC5',
  'HSPA1A',
  'HSPA1B',
  'HSPA1L',
  'HSPA2',
  'HSPA8',
  'IFIT1',
  'IKBKB',
  'IKBKG',
  'ILF2',
  'ILF3',
  'IRF3',
  'ISG15',
  'JAK1',
  'KPNA1',
  'KPNA2',
  'KPNA3',
  'KPNA4',
  'KPNA5',
  'KPNA7',
  'KPNB1',
  'MAP2K6',
  'MAPK3',
  'MAPT',
  'MAVS',
  'MX1',
  'MX2',
  'NCK1',
  'NDC1',
  'NEDD4',
  'NPM1',
  'NUP107',
  'NUP133',
  'NUP153',
  'NUP155',
  'NUP160',
  'NUP188',
  'NUP205',
  'NUP210',
  'NUP214',
  'NUP35',
  'NUP37',
  'NUP42',
  'NUP43',
  'NUP50',
  'NUP54',
  'NUP58',
  'NUP62',
  'NUP85',
  'NUP88',
  'NUP93',
  'NUP98',
  'OAS1',
  'OAS2',
  'OAS3',
  'OASL',
  'PDE12',
  'PIN1',
  'PLCG1',
  'POM121',
  'PPM1B',
  'PPP2CA',
  'PPP2CB',
  'PPP2R1A',
  'PPP2R1B',
  'PPP2R5A',
  'PRKRA',
  'PTPN2',
  'RAE1',
  'RANBP2',
  'RIGI',
  'RNASEL',
  'RPS27A',
  'SEC13',
  'SEH1L',
  'SNCA',
  'SPHK1',
  'STAT1',
  'STAT3',
  'SUMO1',
  'TARBP2',
  'TP53',
  'TPR',
  'TRIM25',
  'TUBA1A',
  'TUBA1B',
  'TUBA1C',
  'TUBA3C',
  'TUBA3D',
  'TUBA3E',
  'TUBA4A',
  'TUBA8',
  'TUBAL3',
  'TUBB1',
  'TUBB2A',
  'TUBB2B',
  'TUBB3',
  'TUBB4A',
  'TUBB4B',
  'TUBB6',
  'TUBB8',
  'UBA52',
  'UBA7',
  'UBB',
  'UBC',
  'UBE2E1',
  'UBE2I',
  'UBE2L6',
  'UBE2N',
  'USP18'],
 'B cell activation': ['ABL1',
  'ADA',
  'ADAM17',
  'ADGRG3',
  'AICDA',
  'AKAP17A',
  'AQP8',
  'ATAD5',
  'BANK1',
  'BATF',
  'BAX',
  'BCL2',
  'BCL3',
  'BCL6',
  'BLNK',
  'BST2',
  'BTK',
  'C17orf99',
  'CARD11',
  'CASP8',
  'CCR6',
  'CD180',
  'CD19',
  'CD22',
  'CD38',
  'CD40',
  'CD40LG',
  'CD70',
  'CD79A',
  'CD79B',
  'CD86',
  'CDH17',
  'CEBPG',
  'CHRNA4',
  'CHRNB2',
  'CLCF1',
  'CMTM7',
  'CR2',
  'CTPS1',
  'CXCR5',
  'DCAF1',
  'DCLRE1C',
  'DLL1',
  'DNAJB9',
  'DOCK10',
  'DOCK11',
  'EP300',
  'EPHB2',
  'ERCC1',
  'EXO1',
  'EXOSC3',
  'EXOSC6',
  'EZH2',
  'FCGR2B',
  'FCRL1',
  'FLT3',
  'FNIP1',
  'FOSL2',
  'FOXP3',
  'FZD9',
  'GAPT',
  'GPR183',
  'GPS2',
  'HDAC4',
  'HDAC5',
  'HDAC9',
  'HHEX',
  'HSPD1',
  'ICOSLG',
  'IFNA1',
  'IFNA10',
  'IFNA13',
  'IFNA14',
  'IFNA16',
  'IFNA17',
  'IFNA2',
  'IFNA21',
  'IFNA4',
  'IFNA5',
  'IFNA6',
  'IFNA7',
  'IFNA8',
  'IFNB1',
  'IFNE',
  'IFNK',
  'IFNW1',
  'IGBP1',
  'IKZF3',
  'IL10',
  'IL11',
  'IL21',
  'IL2RG',
  'IL4',
  'IL6',
  'IL7',
  'IL7R',
  'IL9',
  'IRF2BP2',
  'IRF8',
  'ITFG2',
  'ITGA4',
  'ITGB1',
  'ITM2A',
  'JAK3',
  'KIT',
  'KLF6',
  'LAT2',
  'LAX1',
  'LEF1',
  'LFNG',
  'LGALS1',
  'LIG4',
  'LRRC8A',
  'LYL1',
  'MALT1',
  'MEF2C',
  'MFNG',
  'MIR19A',
  'MLH1',
  'MS4A1',
  'MSH2',
  'MSH6',
  'NBN',
  'NFAM1',
  'NFKBIZ',
  'NHEJ1',
  'NKX2-3',
  'NOTCH2',
  'NTRK1',
  'ONECUT1',
  'PAX5',
  'PHB1',
  'PHB2',
  'PHF14',
  'PIK3CD',
  'PIK3R1',
  'PIK3R2',
  'PIK3R3',
  'PLCG2',
  'PLCL2',
  'POU2AF1',
  'PRKCB',
  'PRKCD',
  'PRKDC',
  'PTK2B',
  'PTPN2',
  'PTPRC',
  'PTPRJ',
  'RABL3',
  'RAG1',
  'RAG2',
  'RASGRP1',
  'RBPJ',
  'RNF168',
  'RNF8',
  'SANBR',
  'SASH3',
  'SHB',
  'SKAP2',
  'SLC25A5',
  'SLC39A7',
  'SP3',
  'ST3GAL1',
  'STAT5B',
  'STAT6',
  'SWAP70',
  'SYK',
  'SYVN1',
  'TBC1D10C',
  'TCF3',
  'TCIRG1',
  'TICAM1',
  'TLR4',
  'TNFSF13B',
  'TOP2B',
  'TPD52',
  'TRAF3IP2',
  'TXLNA',
  'UNG',
  'VCAM1',
  'WNT3A',
  'YY1',
  'ZAP70',
  'ZBTB1',
  'ZBTB7A'],
 'B cell costimulation': ['CD320', 'TNFRSF13C', 'TNFSF13B'],
 'B cell differentiation': ['ABL1',
  'ADA',
  'ADAM17',
  'ADGRG3',
  'AICDA',
  'AQP8',
  'BCL3',
  'BCL6',
  'BLNK',
  'C17orf99',
  'CARD11',
  'CD19',
  'CD40LG',
  'CD79A',
  'CD79B',
  'CDH17',
  'CEBPG',
  'CLCF1',
  'CMTM7',
  'CR2',
  'DCAF1',
  'DCLRE1C',
  'DLL1',
  'DNAJB9',
  'DOCK10',
  'DOCK11',
  'EP300',
  'EZH2',
  'FCGR2B',
  'FLT3',
  'FNIP1',
  'FOSL2',
  'FZD9',
  'GPR183',
  'GPS2',
  'HDAC4',
  'HDAC5',
  'HDAC9',
  'HHEX',
  'IFNA1',
  'IFNA10',
  'IFNA13',
  'IFNA14',
  'IFNA16',
  'IFNA17',
  'IFNA2',
  'IFNA21',
  'IFNA4',
  'IFNA5',
  'IFNA6',
  'IFNA7',
  'IFNA8',
  'IFNB1',
  'IFNE',
  'IFNK',
  'IFNW1',
  'IKZF3',
  'IL10',
  'IL11',
  'IL21',
  'IL2RG',
  'IL4',
  'IL6',
  'IL9',
  'IRF2BP2',
  'IRF8',
  'ITFG2',
  'ITGA4',
  'ITGB1',
  'ITM2A',
  'JAK3',
  'KIT',
  'KLF6',
  'LFNG',
  'LGALS1',
  'LRRC8A',
  'LYL1',
  'MALT1',
  'MFNG',
  'MS4A1',
  'MSH2',
  'NFAM1',
  'NFKBIZ',
  'NHEJ1',
  'NKX2-3',
  'NOTCH2',
  'NTRK1',
  'ONECUT1',
  'PAX5',
  'PHF14',
  'PIK3CD',
  'PIK3R1',
  'PIK3R2',
  'PIK3R3',
  'PLCG2',
  'PLCL2',
  'POU2AF1',
  'PRKDC',
  'PTK2B',
  'PTPN2',
  'PTPRC',
  'PTPRJ',
  'RABL3',
  'RAG1',
  'RAG2',
  'RBPJ',
  'SLC25A5',
  'SLC39A7',
  'SP3',
  'ST3GAL1',
  'STAT5B',
  'SYK',
  'SYVN1',
  'TCF3',
  'TCIRG1',
  'TNFSF13B',
  'TOP2B',
  'TPD52',
  'TRAF3IP2',
  'VCAM1',
  'YY1',
  'ZBTB1',
  'ZBTB7A'],
 'B cell receptor apoptotic signaling pathway': ['BAX', 'NFKBIZ'],
 'B cell selection': ['BAK1', 'BAX', 'BTK', 'TRAF3IP2'],
 'Butyrophilin (BTN) family interactions': ['BTN1A1',
  'BTN2A1',
  'BTN2A2',
  'BTN3A1',
  'BTN3A2',
  'BTN3A3',
  'BTNL2',
  'BTNL8',
  'BTNL9',
  'CD209',
  'PPL',
  'XDH'],
 'Cell activation involved in immune response': ['ABL1',
  'ADA',
  'AICDA',
  'APBB1IP',
  'APP',
  'ASCL2',
  'ATAD5',
  'ATP7A',
  'BATF',
  'BCL3',
  'BCL6',
  'C17orf99',
  'CCR6',
  'CD180',
  'CD19',
  'CD1C',
  'CD244',
  'CD40LG',
  'CD74',
  'CDH17',
  'CLEC4D',
  'CLEC4E',
  'CX3CR1',
  'DLL1',
  'DNASE1',
  'DNASE1L3',
  'DOCK10',
  'DOCK11',
  'DOCK2',
  'DYSF',
  'EIF2AK4',
  'ENPP3',
  'ENTPD7',
  'EOMES',
  'ERCC1',
  'EXO1',
  'EXOSC3',
  'EXOSC6',
  'F2RL1',
  'FCER1G',
  'FCGR2B',
  'FGL2',
  'FOXP1',
  'FOXP3',
  'GAPT',
  'GATA3',
  'GBF1',
  'GPR183',
  'GRN',
  'HAVCR2',
  'HLX',
  'HMGB1',
  'HSPD1',
  'ICAM1',
  'IFI35',
  'IFNA1',
  'IFNA10',
  'IFNA13',
  'IFNA14',
  'IFNA16',
  'IFNA17',
  'IFNA2',
  'IFNA21',
  'IFNA4',
  'IFNA5',
  'IFNA6',
  'IFNA7',
  'IFNA8',
  'IFNB1',
  'IFNE',
  'IFNG',
  'IFNK',
  'IFNW1',
  'IL12B',
  'IL18R1',
  'IL2',
  'IL21',
  'IL33',
  'IL4R',
  'IL6',
  'IRF8',
  'ITFG2',
  'ITGAL',
  'ITM2A',
  'KARS1',
  'KMT2A',
  'LBP',
  'LCP1',
  'LEF1',
  'LFNG',
  'LGALS1',
  'LIG4',
  'LILRA2',
  'LILRB1',
  'LRP1',
  'MDK',
  'MEN1',
  'MFNG',
  'MLH1',
  'MSH2',
  'MSH6',
  'MYB',
  'MYD88',
  'NBN',
  'NFKBIZ',
  'NKX2-3',
  'NMI',
  'NOTCH2',
  'PDP2',
  'PHF14',
  'PLCG2',
  'PLCL2',
  'POU2AF1',
  'PRKCE',
  'PSEN1',
  'PTGER4',
  'PTK2B',
  'PYCARD',
  'RAG2',
  'RC3H1',
  'RC3H2',
  'RELB',
  'RNF168',
  'RNF8',
  'RORA',
  'RORC',
  'RPS6',
  'SANBR',
  'SBNO2',
  'SCNN1B',
  'SEMA4A',
  'SH2D1B',
  'SLAMF1',
  'SLC11A1',
  'ST3GAL1',
  'STAT4',
  'STAT6',
  'SUCNR1',
  'SWAP70',
  'SYK',
  'TCIM',
  'TICAM1',
  'TLR4',
  'TMEM98',
  'TNF',
  'TNFSF18',
  'TP53',
  'TREM2',
  'TREX1',
  'TSC1',
  'TYROBP',
  'UNG'],
 'Cellular extravasation': ['AZU1',
  'CCL2',
  'CCR2',
  'CD177',
  'CD99',
  'F11R',
  'ICAM1',
  'ITGA1',
  'ITGAL',
  'JAM2',
  'JAML',
  'PECAM1',
  'PIK3CD',
  'PIK3CG',
  'PRTN3',
  'SIRPA',
  'XG'],
 'Class I MHC mediated antigen processing & presentation': ['ANAPC1',
  'ANAPC10',
  'ANAPC11',
  'ANAPC13',
  'ANAPC2',
  'ANAPC4',
  'ANAPC5',
  'AREL1',
  'ARIH2',

In [19]:
# ============================================================
#       Annotate, filter df_comp_score
# ============================================================

df_comp_score_ann = df_comp_score.join(
    df_final_output.select([
        "defense_uniprot_ac",
        "human_entryId",
        "Gene Names (primary)",
        "defense_type",
        "defense_subtype",
    ]),
    on=["defense_uniprot_ac", "human_entryId"],
    how="left",
)
df_comp_score_filt = df_comp_score_ann.filter(
    pl.col("composite_score") >= COMP_THRESHOLD
)
df_comp_score_filt

shape: (49_936, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ defense_u ┆ human_ent ┆ composite ┆ foldseek_ ┆ … ┆ plddt_bac ┆ Gene      ┆ defense_t ┆ defense_ │
│ niprot_ac ┆ ryId      ┆ _score    ┆ evalue    ┆   ┆ teria     ┆ Names     ┆ ype       ┆ subtype  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ (primary) ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ f32       ┆ ---       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ A0A7S9D46 ┆ A0A140VK7 ┆ 0.8986    ┆ 5.6920e-1 ┆ … ┆ 89.629997 ┆ null      ┆ CBASS     ┆ CBASS_II │
│ 1         ┆ 0         ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆ I        │
│ A0A0Q2ZX7 ┆ B4DED6    ┆ 0.8503    ┆ 1.9270e-2 ┆ … ┆ 88.099998 ┆ null      ┆ PsyrTA    ┆ PsyrTA   │
│ 6         ┆           ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ Q96Z85    ┆ Q7Z3Z4    ┆ 0.85      ┆ 2.3030e-3 ┆ … ┆ 84.760002 ┆ PIWIL4    ┆ pAgo      ┆ pAgo_Lon │
│           ┆           ┆           ┆ 3         ┆   ┆           ┆           ┆           ┆ gB       │
│ A0A0F7KBN ┆ A0A2R8Y4Y ┆ 0.8635    ┆ 3.4060e-3 ┆ … ┆ 90.230003 ┆ SPG7      ┆ CBASS     ┆ CBASS_II │
│ 7         ┆ 7         ┆           ┆ 0         ┆   ┆           ┆           ┆           ┆ I        │
│ A0A2H4ZHC ┆ I3L4J1    ┆ 0.8655    ┆ 4.3450e-1 ┆ … ┆ 90.93     ┆ null      ┆ CBASS     ┆ CBASS_II │
│ 4         ┆           ┆           ┆ 7         ┆   ┆           ┆           ┆           ┆ I        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ A0A2S2F9C ┆ Q8TBC4    ┆ 0.9009    ┆ 1.7690e-1 ┆ … ┆ 90.879997 ┆ UBA3      ┆ CBASS     ┆ CBASS_II │
│ 8         ┆           ┆           ┆ 3         ┆   ┆           ┆           ┆           ┆          │
│ A0A857GPF ┆ K0J110    ┆ 0.8611    ┆ 1.9270e-2 ┆ … ┆ 88.459999 ┆ mcdrh     ┆ PsyrTA    ┆ PsyrTA   │
│ 0         ┆           ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ A0A250IWT ┆ Q9BVC4    ┆ 0.871     ┆ 2.0190e-1 ┆ … ┆ 53.220001 ┆ MLST8     ┆ Septu     ┆ Septu    │
│ 1         ┆           ┆           ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│ A0A5P3ALB ┆ Q9H4E3    ┆ 0.8713    ┆ 1.2930e-1 ┆ … ┆ 89.019997 ┆ E4-DBP    ┆ Shango    ┆ Shango   │
│ 7         ┆           ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ A0A2I5KM7 ┆ V9GXZ4    ┆ 0.8666    ┆ 3.4560e-1 ┆ … ┆ 80.989998 ┆ FPGT-TNNI ┆ PD-T4-6   ┆ PD-T4-6  │
│ 4         ┆           ┆           ┆ 5         ┆   ┆           ┆ 3K        ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Gene list

Additional filtering criteria:
1. Has UniProtKB ID (p = 0.66)
2. Has composite score >= 0.825

In [ ]:
# ============================================================
#       Get gene names
# ============================================================

df_comp_genes = df_comp_score_filt.unique(subset=["Gene Names (primary)"], keep="first")
df_comp_genes

shape: (721, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ defense_u ┆ human_ent ┆ composite ┆ foldseek_ ┆ … ┆ plddt_bac ┆ Gene      ┆ defense_t ┆ defense_ │
│ niprot_ac ┆ ryId      ┆ _score    ┆ evalue    ┆   ┆ teria     ┆ Names     ┆ ype       ┆ subtype  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ (primary) ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ f32       ┆ ---       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ A0A0B5NK2 ┆ Q9NUV7    ┆ 0.8594    ┆ 2.7210e-1 ┆ … ┆ 95.639999 ┆ SPTLC3    ┆ Dnd       ┆ Dnd_ABCD │
│ 0         ┆           ┆           ┆ 3         ┆   ┆           ┆           ┆           ┆ EFGH     │
│ A0A191YQ4 ┆ Q6P1N9    ┆ 0.9158    ┆ 7.4450e-1 ┆ … ┆ 97.5      ┆ TATDN1    ┆ Gao_Qat   ┆ Gao_Qat  │
│ 1         ┆           ┆           ┆ 3         ┆   ┆           ┆           ┆           ┆          │
│ A0A6J5KGR ┆ O95352    ┆ 0.8835    ┆ 6.5330e-1 ┆ … ┆ 90.110001 ┆ ATG7      ┆ CBASS     ┆ CBASS_II │
│ 0         ┆           ┆           ┆ 3         ┆   ┆           ┆           ┆           ┆          │
│ A0A0K2E48 ┆ U6FVB0    ┆ 0.8501    ┆ 1.2090e-1 ┆ … ┆ 79.769997 ┆ CD74-Ntrk ┆ PD-T4-6   ┆ PD-T4-6  │
│ 4         ┆           ┆           ┆ 6         ┆   ┆           ┆ 1 fusion  ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ gene      ┆           ┆          │
│ A0A6M4GS2 ┆ Q460N3    ┆ 0.8541    ┆ 9.0660e-1 ┆ … ┆ 81.129997 ┆ PARP15    ┆ DarTG     ┆ DarTG    │
│ 3         ┆           ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ A0A0H3JWT ┆ F8WCQ3    ┆ 0.8724    ┆ 1.7160e-1 ┆ … ┆ 89.510002 ┆ DAPK1     ┆ Stk2      ┆ Stk2     │
│ 2         ┆           ┆           ┆ 0         ┆   ┆           ┆           ┆           ┆          │
│ R9RJ65    ┆ E9PMM7    ┆ 0.888     ┆ 4.3560e-1 ┆ … ┆ 80.139999 ┆ RPS6KA1   ┆ PD-T4-6   ┆ PD-T4-6  │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ A0A167BUW ┆ Q7Z2V5    ┆ 0.8826    ┆ 1.0980e-1 ┆ … ┆ 89.199997 ┆ DKFZp686J ┆ Shango    ┆ Shango   │
│ 9         ┆           ┆           ┆ 7         ┆   ┆           ┆ 01190     ┆           ┆          │
│ A0A822VZF ┆ A0A1W2PPJ ┆ 0.875     ┆ 1.5390e-2 ┆ … ┆ 80.580002 ┆ STRADA    ┆ PD-T4-6   ┆ PD-T4-6  │
│ 9         ┆ 9         ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ A0A517ZL3 ┆ Q32ND9    ┆ 0.8664    ┆ 1.4200e-1 ┆ … ┆ 74.099998 ┆ IKBKB     ┆ PD-T4-6   ┆ PD-T4-6  │
│ 3         ┆           ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘