### Get gene list from composite scoring results
### Julian Moran
### 2026-09-02

In [1]:
import boto3
import glob
import logging
import math
import os
import requests
import s3fs
import time

import matplotlib.pyplot as plt
import numpy as np
import polars as pl

from dotenv import load_dotenv

# Env
load_dotenv("../.env", override=True)
REPO_ROOT = os.environ["INSTALL_PATH"]
MINIO_KEY = os.environ["MINIO_KEY"]
MINIO_SECRET = os.environ["MINIO_SECRET"]

# Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s:%(name)s:%(message)s"
)
logger = logging.getLogger(__name__)

In [6]:
# ============================================================
#       Args
# ============================================================

# MinIO
BUCKET = "iei-project"
PREFIX_GOLD = "03_gold/defense_finder/"
PREFIX_SILVER = "02_silver/defense_finder/"
FILE_COMPOSITE = "composite_score.parquet/part-00000-ac5574c4-cf3c-48a9-98b6-077d4db394f9-c000.snappy.parquet"
FILE_FINAL_OUTPUT = "final_output_spark.parquet/part-00000-bb778272-db05-479f-a79a-2d18e89fe363-c000.snappy.parquet"

# Dirs
OUT_DIR_PLOT = f"{REPO_ROOT}/vis/plots"

# Check live objects in MinIO silver
client = boto3.client(
    "s3",
    endpoint_url="http://eagle.tcag.ca:9000",
    aws_access_key_id=MINIO_SECRET,
    aws_secret_access_key=MINIO_KEY,
)
response = client.list_objects_v2(
    Bucket=BUCKET,
    Prefix=PREFIX_GOLD
)
live_objects = [
    obj["Key"]
    for obj in response.get("Contents", [])
]
live_objects

['03_gold/defense_finder/composite_score.parquet/_SUCCESS',
 '03_gold/defense_finder/composite_score.parquet/part-00000-ac5574c4-cf3c-48a9-98b6-077d4db394f9-c000.snappy.parquet',
 '03_gold/defense_finder/defense_human_domain_annotated.parquet',
 '03_gold/defense_finder/final_output_spark.parquet/_SUCCESS',
 '03_gold/defense_finder/final_output_spark.parquet/part-00000-bb778272-db05-479f-a79a-2d18e89fe363-c000.snappy.parquet',
 '03_gold/defense_finder/griid_gene_subset.parquet',
 '03_gold/defense_finder/human_bacteria_structural_analogs_enriched.parquet',
 '03_gold/defense_finder/human_bacteria_structural_analogs_with_scores.parquet/_SUCCESS',
 '03_gold/defense_finder/human_bacteria_structural_analogs_with_scores.parquet/part-00000-275fe83c-840b-476e-bf63-c47165847863-c000.snappy.parquet']

In [7]:
# ============================================================
#       In
# ============================================================

df_final_output = pl.read_parquet(
    f"s3://{BUCKET}/{PREFIX_GOLD}{FILE_FINAL_OUTPUT}",
    storage_options={
        "aws_endpoint_url": "http://eagle.tcag.ca:9000",
        "aws_access_key_id": MINIO_SECRET,
        "aws_secret_access_key": MINIO_KEY,
    }
)

df_comp_score = pl.read_parquet(
    f"s3://{BUCKET}/{PREFIX_GOLD}{FILE_COMPOSITE}",
    storage_options={
        "aws_endpoint_url": "http://eagle.tcag.ca:9000",
        "aws_access_key_id": MINIO_SECRET,
        "aws_secret_access_key": MINIO_KEY,
    }
)
df_comp_score

shape: (1_097_291, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ defense_u ┆ human_ent ┆ composite ┆ foldseek_ ┆ … ┆ tm_score_ ┆ tm_score_ ┆ plddt_hum ┆ plddt_ba │
│ niprot_ac ┆ ryId      ┆ _score    ┆ evalue    ┆   ┆ human     ┆ bacteria  ┆ an        ┆ cteria   │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ f32       ┆ f32       ┆ f32       ┆ f32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ A0A5C5QGP ┆ A0A024R9P ┆ 0.2646    ┆ 0.000087  ┆ … ┆ null      ┆ null      ┆ null      ┆ 83.48000 │
│ 9         ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ A0A2R3IRC ┆ A0A0D9SF9 ┆ 0.8315    ┆ 1.2070e-7 ┆ … ┆ 0.8169    ┆ 0.1028    ┆ 83.199997 ┆ 77.44999 │
│ 4         ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ A0A4D8PF3 ┆ A0A140VK7 ┆ 0.2883    ┆ 0.003094  ┆ … ┆ 0.2908    ┆ 0.1539    ┆ 80.290001 ┆ 83.05000 │
│ 3         ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ A0A7S9D46 ┆ A0A140VK7 ┆ 0.8986    ┆ 5.6920e-1 ┆ … ┆ 0.535     ┆ 0.7678    ┆ 80.290001 ┆ 89.62999 │
│ 1         ┆ 0         ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆ 7        │
│ A0A2K9LJD ┆ A0A1B0GVC ┆ 0.2795    ┆ 0.007862  ┆ … ┆ 0.2428    ┆ 0.29      ┆ 67.610001 ┆ 91.37999 │
│ 6         ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ A0A1D7XM1 ┆ Q9H4E3    ┆ 0.6409    ┆ 0.000001  ┆ … ┆ 0.6556    ┆ 0.327     ┆ 84.879997 ┆ 82.36000 │
│ 3         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ A0A7D6CQE ┆ Q9H4E3    ┆ 0.5814    ┆ 0.000001  ┆ … ┆ 0.6733    ┆ 0.3337    ┆ 84.879997 ┆ 75.23000 │
│ 3         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ A0A5P3ALB ┆ Q9H4E3    ┆ 0.8713    ┆ 1.2930e-1 ┆ … ┆ 0.739     ┆ 0.4786    ┆ 84.879997 ┆ 89.01999 │
│ 7         ┆           ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆ 7        │
│ A0A0U0WN1 ┆ Q9H4E3    ┆ 0.7745    ┆ 2.0010e-1 ┆ … ┆ 0.6593    ┆ 0.3919    ┆ 84.879997 ┆ 83.30000 │
│ 8         ┆           ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆ 3        │
│ A0A2I5KM7 ┆ V9GXZ4    ┆ 0.8666    ┆ 3.4560e-1 ┆ … ┆ 0.2633    ┆ 0.3695    ┆ 73.169998 ┆ 80.98999 │
│ 4         ┆           ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆ 8        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
df_final_output

shape: (1_097_291, 34)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ defense_u ┆ cluster_r ┆ defense_t ┆ human_ent ┆ … ┆ RefSeq    ┆ human_dom ┆ defense_t ┆ defense_ │
│ niprot_ac ┆ epId      ┆ axId      ┆ ryId      ┆   ┆ ---       ┆ ains      ┆ ype       ┆ subtype  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆           ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ D5H7G1    ┆ A0A2P4VLT ┆ 761659    ┆ A0A024QZ2 ┆ … ┆ null      ┆ null      ┆ Gao_TerY  ┆ Gao_TerY │
│           ┆ 1         ┆           ┆ 0         ┆   ┆           ┆           ┆           ┆          │
│ A0A0S2KJ8 ┆ A0A858BYG ┆ 76123     ┆ A0A024R74 ┆ … ┆ null      ┆ null      ┆ CBASS     ┆ CBASS_II │
│ 9         ┆ 8         ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆          │
│ A0A1L3LSP ┆ A0A858BYG ┆ 194963    ┆ A0A024R74 ┆ … ┆ null      ┆ null      ┆ CBASS     ┆ CBASS_I  │
│ 8         ┆ 8         ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆          │
│ A0A2G9LHY ┆ A0A858BYG ┆ 573       ┆ A0A024R74 ┆ … ┆ null      ┆ null      ┆ CBASS     ┆ CBASS_II │
│ 5         ┆ 8         ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆          │
│ A0A2K9Z6V ┆ A0A858BYG ┆ 384       ┆ A0A024R74 ┆ … ┆ null      ┆ null      ┆ CBASS     ┆ CBASS_I  │
│ 0         ┆ 8         ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ A0A5P8W2P ┆ A0A3S9MKD ┆ 2653204   ┆ X5D2R5    ┆ … ┆ NP_079428 ┆ null      ┆ PsyrTA    ┆ PsyrTA   │
│ 0         ┆ 2         ┆           ┆           ┆   ┆ .2;       ┆           ┆           ┆          │
│ A7HKC7    ┆ A0A3S9MKD ┆ 381764    ┆ X5D2R5    ┆ … ┆ NP_079428 ┆ null      ┆ PsyrTA    ┆ PsyrTA   │
│           ┆ 2         ┆           ┆           ┆   ┆ .2;       ┆           ┆           ┆          │
│ E4TBU2    ┆ A0A3S9MKD ┆ 693978    ┆ X5D2R5    ┆ … ┆ NP_079428 ┆ null      ┆ ShosTA    ┆ ShosTA   │
│           ┆ 2         ┆           ┆           ┆   ┆ .2;       ┆           ┆           ┆          │
│ J9R5B4    ┆ A0A3S9MKD ┆ 1228997   ┆ X5D2R5    ┆ … ┆ NP_079428 ┆ null      ┆ ShosTA    ┆ ShosTA   │
│           ┆ 2         ┆           ┆           ┆   ┆ .2;       ┆           ┆           ┆          │
│ E3FIT8    ┆ A0A6N2D3T ┆ 378806    ┆ X5D7J4    ┆ … ┆ null      ┆ DOMAIN    ┆ Pycsar    ┆ Pycsar   │
│           ┆ 8         ┆           ┆           ┆   ┆           ┆ 125..170; ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ /note="UB ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ A"; …     ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
print(df_final_output.columns)

['defense_uniprot_ac', 'cluster_repId', 'defense_taxId', 'human_entryId', 'foldseek_evalue', 'Entry', 'Reviewed', 'Entry Name', 'Protein names', 'Gene Names', 'Organism', 'Length', 'Gene Names (ordered locus)', 'Gene Names (ORF)', 'Gene Names (primary)', 'Gene Names (synonym)', 'Proteomes', 'Gene Ontology (biological process)', 'Gene Ontology (cellular component)', 'Gene Ontology (molecular function)', 'Gene Ontology (GO)', 'Gene Ontology IDs', 'FunFam', 'CDD', 'Gene3D', 'InterPro', 'PANTHER', 'Pfam', 'PROSITE', 'SMART', 'RefSeq', 'human_domains', 'defense_type', 'defense_subtype']